### ISSUE TITLE
Blog post on recent Policy work

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#100]
- Recommendations for the Task Force on Community Engagement
- Recommendations for the City Clerk on Agenda Management RFP
- Overall updates to Policy Priorities 
- outline of what's next, council questionaries' etc

**Comment by mscarey** [comment]
I blogged about  Leslie Pool, Fred Lewis, and the city council lobbyist bill, plus the stuff happening in the lobbyist-campaign slack channel.
