### ISSUE TITLE
ACC Highland Campus for hack nights

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#106]
Brian McCullough suggested ACC's extended Highland Campus as a location for future hack nights. We should get in touch with them.

http://www.austincc.edu/board-of-trustees

http://www.austincc.edu/highland-campus/accelerator/staff

**Comment by mateoclarke** [comment]
Ellen Lazaretti made an introduction for us with 2 professors in the UX program. Apparently they are planning a student hackathon for this spring. Waiting on their response.

David Correa <dcorrea@austincc.edu>
Marc Bonasso <marc.bonasso@austincc.edu>

**Comment by mateoclarke** [comment]
meeting up with David and Marc on 4/12 at 6pm at ACC Northridge campus

**Comment by mateoclarke** [comment]
anyone interested in how we can partner more with ACC, come along or feed me some ideas.

**Comment by VictoriaODell** [comment]
How did the meeting go for this?

**Comment by VictoriaODell** [comment]
@mateoclarke 
When you talked to Marc did having hack nights at ACC highland or Northridge seem like an option? 
Is that something we want to/can do?

If so we should roll it into issue #65 and put it in our spreadsheet

Maybe we should talk more about this at our huddle. Seems like space planning is something we need to look into more with our free passes running out. 📆

**Comment by mateoclarke** [comment]
ACC Northridge is very far north. ACC Highland didn't seem like an obvious possibility. His department offices are at Northridge. I could ask explicitly if we could host an event there, but my gut says getting reoccurring space there would be hard since we aren't a student org.
