### ISSUE TITLE
AC4D Partnered Event

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#107]
We've talked about a co-hosted event with AC4D, "Designing for Social Impact Workshop"
https://open-austin.slack.com/archives/eventplanning/p1455379930000061

Here are some todos:
- [x] Figure out a rough date.
   - End of April so not to conflict with other pre-ATXH4C workshops?
- [x] Decide what problem statement we want to focus in on? 
  - [Safety & Justice](http://www.codeforamerica.org/focus/safety-justice/), [Health](http://www.codeforamerica.org/focus/health/), [Economic Development](http://www.codeforamerica.org/focus/economic-development/), [Communications & Engagement](http://www.codeforamerica.org/focus/communications-engagement/). 
- [x] Have a convo with Eric, to talk details. (SCHEDULED)
- [x] How many max attendees?
  - Is it based on the amount of facilitators from AC4D that are available ?
- 40 People is the max
- [x] Book a venue (here's a good [list](https://github.com/open-austin/iced-coffee/issues/88) to start)
- we currently have the Library booked but also will check out the Y

**Comment by VictoriaODell** [comment]
Hey @mateoclarke, is that the best list of Venues we have? If so, I'd like to create a spreadsheet of that. If not, can you point me to another list?

**Comment by mateoclarke** [comment]
Yes, its the best we've got but I'm sure there are some missing.

**Comment by mateoclarke** [comment]
Here's a few more: https://library.austintexas.gov/sites/default/files/u20/meeting_spaces_2015.pdf

**Comment by mateoclarke** [comment]
Got an email response from For the City Center (we had reached out to them regarding CodeAcross). Their venue rental fees for non profits are reasonable.

[2015 FTCC Rental Information - NonProfit & General Use.pdf](https://github.com/open-austin/iced-coffee/files/135333/2015.FTCC.Rental.Information.-.NonProfit.General.Use.pdf)

**Comment by VictoriaODell** [comment]
That does seem reasonable. 

If you find/have any more venue docs can you put them in here: 
[https://drive.google.com/drive/u/1/folders/0BwKb2oghmQldMDlLVnNIQk9tTEU](https://drive.google.com/drive/u/1/folders/0BwKb2oghmQldMDlLVnNIQk9tTEU)

**Comment by mateoclarke** [comment]
So this event has spawned several other issues. Going to close this one for now but I added it under the Design Workshop Milestone.
