### ISSUE TITLE
Civic Hack Night Partners/Donors

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#108]
We've started outreach to sponsors for CodeAcross, but we also need to look forward and try to secure partners for Civic Hack Nights so I don't have to pay for Chipotle every month.

I started this donor prospectus doc that we can push this out more broadly:
https://docs.google.com/document/d/1jB7Z4Bh0JBRjv8i-G5ACvrSt9f0sGqXe5C8_DofYsTc/edit

**Important Note** I'm using the term Donor/Partner instead of sponsor for a reason. One of the benefits of donating is that it is tax deductible through CfA. Sponsorships are quid-pro-quo agreements that are not tax deductible.
### Reached Out to:
- [x] DevBootcamp - Whitney O'Banner

**Comment by mateoclarke** [comment]
List of Potential Sponsors: https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit

**Comment by VictoriaODell** [comment]
Working on putting this on a sheet also: 
https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=0

I haven't started laying out this section though.

**Comment by mateoclarke** [comment]
closing this out bc its old but I captured some of these links in a new wiki page
https://github.com/open-austin/iced-coffee/wiki/Donors-&-Sponsors
