### ISSUE TITLE
[Code Across] Draft a Outreach email template

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#111]

**Comment by mateoclarke** [comment]
@VictoriaODell, Here's the sample message from last year:

```
I want to let you know about an event that Open Austin is hosting of February -

Code Across Austin V: Civic Hack Summit
http://code-across.open-austin.org
Date: Sat, Feb 28, 2015
Time: 10:00 am – 4:00 pm
Location: The Iron Yard, 3601 South Congress Ave

This is not a hacking event per se, but rather (as we call it) the hack before the hack. We're inviting community members and hackers to come together, identify a set of community needs/issues that are amenable to a hack solution, and put together actionable plans for hack projects around these issues.

Open Austin then plans to move these projects forward through events such as ATX Hack for Change, tentatively scheduled for early June at St. Edward's.

I'm wondering if you could publicize this event to your group and invite people who are interested in civic hacking (developers, designers, analysts, project managers, tech writers, etc.) to participate?

If so, we'd like to list your group as one of the community supporters for the event. Just let me know how the group name should be listed, and where we should link to.

P.S. Please feel free to forward this email to any other community group (meetups, clubs, etc.) leaders that you think might be interested in civic hacking events.
```

**Comment by mateoclarke** [comment]
We need to move forward this email outreach template so we can start spammin' it up and inviting people. @VictoriaODell can you give suggestions to the template below?

> I want to let you know about an event that Open Austin is hosting the first weekend in March -
> 
> CodeAcross Austin 2016
> http://codeacrossaustin2016.eventbrite.com
> Date: Sat, March 5, 2015
> Time: 10:00 am – 4:00 pm
> Location: St. Edward's University, Munday Library, 3001 South Congress Avenue Austin, TX 78704
> 
> This is not a hacking event per se, but rather a facilitated design-thinking workshop that will lay the foundation for future civic tech projects. We're inviting community members and hackers to come together, identify a set of community needs/issues that are amenable to a hack solution, and put together actionable plans for hack projects around these issues.
> 
> Open Austin then plans to move these projects forward through events such as our monthly [Civic Hack Nights](http://www.meetup.com/Open-Austin/) and the 4th annual [ATX Hack for Change](http://atxhackforchange.org/), scheduled for the first weekend in June at St. Edward's.

> I'm wondering if you could publicize this event to your group and invite people who are interested in civic hacking (developers, designers, analysts, project managers, tech writers, urbanists, civic activists, etc.) to participate?
> 
> If so, we'd like to list your group as one of the community supporters for the event. Just let me know how the group name should be listed, and where we should link to.
> 
> P.S. Please feel free to forward this email to any other community group (meetups, clubs, etc.) leaders that you think might be interested in civic hacking events.

**Comment by VictoriaODell** [comment]
Yes I have edits but won't be able to do anything until 7:30pm tonight. 

Can we schedule some emails to go out in the am?

**Comment by mateoclarke** [comment]
I don't have email scheduling software. Do you use something?

**Comment by VictoriaODell** [comment]
I've used this before: 

https://www.streak.com/email-tracking-in-gmail

It does other stuff too

**Comment by VictoriaODell** [comment]
Who are we sending this to. 
:eyes:

**Comment by mateoclarke** [comment]
these groups: https://github.com/open-austin/iced-coffee/issues/109#issue-134489168

**Comment by VictoriaODell** [comment]
Suggestion-sh? I think it's kind of the same but different. Lol I added an intro part. I hate emailing :skull: 

> Hello and good morning!
>
>This is Vickie, Marketing Lead of Open Austin, and I'm emailing to let you know about our upcoming event. 
>
>CodeAcross Austin 2016
>http://codeacrossaustin2016.eventbrite.com
>Date: Sat, March 5, 2015
>Time: 10:00 am – 4:00 pm
>Location: St. Edward's University, Munday Library, 3001 South Congress Avenue Austin, TX 78704
>
>Contrary to the name, there won't be much coding. We will be identifying issues in our community, framing them, and prepping for actionable solutions.We're inviting community members, designers, developers, analyst, project managers, non-profits, and activist to come together for our city. 
>
>This event will lay the foundation for ongoing civic tech projects that can continue to be worked on at our monthly Civic Hack Nights. It will also serve as prep for the 4th annual ATX Hack for Change scheduled fo early June at St. Edward's. 
>
>I would appreciate if you could publicize this event to your group and invite people who are interested in civic hacking to participate.
>
>In return, we'd like to list your group as a community supporter for the event. Will you let me know how the group name should be listed and where we should link to if you're able to help spread the word?
>
>Also, feel free to forward this email to other community groups or individuals that may be interested
>
>Thanks and reach out if you have any questions or concerns!

**Comment by mateoclarke** [comment]
works for me
