### ISSUE TITLE
[Code Across] Blog Post

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#117]
per John Clary's recommendation. Basically the same info as the Eventbrite but with some more details. 

EX: https://www.open-austin.org/article/1390

**Comment by VictoriaODell** [comment]
@mateoclarke do we have the address of the library?

**Comment by VictoriaODell** [comment]
@mateoclarke womp. JK I found it..... :see_no_evil:

**Comment by VictoriaODell** [comment]
Published.
