### ISSUE TITLE
11/13 Stickers

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#12]
- [x] Look up Sticker Mule prices and delivery time for stickers ordered
- [x] Decide what imagery should be on the sticker
- [x] Confirm ordering with Mateo 
- [x] Order tha dang stickers

**Comment by VictoriaODell** [comment]
StickerMule has a 5 round turnaround time with FREE shipping
If we want these by FU Weekend then we should order them on Friday the 13th. 
[StickerMule Website] (https://www.stickermule.com/custom-stickers)

**Comment by mateoclarke** [comment]
Once you finalize what imagery goes on the stickers, you can reassign this to me and I can order.

If we finish the Logo Redesign by 11/13, I'd vote for ordering logos with the new logo. If not, we can fall back on the current logo or a FUWeekend logo. Does that sound right?

**Comment by VictoriaODell** [comment]
That is correct! Sounds good. I'm changing the due date to 11/13 since that would be the last day we would want to order them from Sticker Mule.

**Comment by VictoriaODell** [comment]
@mateoclarke ordered~
