### ISSUE TITLE
[Code Across] Make slides for convocation intro

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#121]
[Link to planning document
](https://docs.google.com/document/d/18WwQ0ttA_M73nk16jkCcU7afIGPZjkkXOBNxOPmFPB8/edit#)

## Intro
"Explaining what success looks like for people new to the civic hack conversation. 
Examples of last years projects and models of the success that begins today.
Short overview of what to expect through the breakout sessions & down selection process."

## Policy Theme examples
Current policy, photographs.  
	Codeforamerica.org/focus
  - Health and Human services
  - Public Safety & Justice
  - Economic Development
  - Communication and Engagement
  - Transportation
  - Broadband and Digital Opportunities- digital divide & accessibility 
  - Sustainability- water, env, parks, recycling, waste management
  - Planning and Land Use
“Any suggestions? Anything we missed that could also serve as a theme for this event?” 

## Additional Hack Canvas Questions
Slide of things to think about
The goal for this sprint is take a problem statement and define the scope of the problem by answering questions like: 
What do we know about this problem? Do we have a story or example?
Who is affected by this problem?
What is the constituent/user trying to achieve that they can’t?
When does this problem occur? All the time, at night, during special events?
Is the challenge limited to a specific geography?
Are there existing systems that are trying to address this problem?
What don’t you understand, what are you still curious about, what would you ask a crystal ball?
[other guiding questions]

**Comment by VictoriaODell** [comment]
Lol nothing really here yet. 
[Slide Deck](https://docs.google.com/presentation/d/1aWNB5wWr9ZIjwvMNEZR2uoGJcK9zDKuFw0_B1JIhFBk/edit#slide=id.p)

I'll probably be working on this more during Hack Night.
