### ISSUE TITLE
[Code Across] After event, migrate todo's and discussion to Google Doc for next year's reference

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#123]
https://docs.google.com/document/d/1b1ng9rSpwC1NauI4-mpGEbi1sKDh1Cvc8sghOB3c5Gk/edit

**Comment by VictoriaODell** [comment]
It'd be nice if we could review the feedback responses and go over some things that went well and what could be improved on. 

Where is the feedback form hosted? I tried looking for it 👀

**Comment by amaliebarras** [comment]
There was this one from last year? https://drive.google.com/open?id=1jOYC2r1eT1Dn7rCor1qlMcLHfJ5pfZNY8K0T27WoMVE unless y'all made another

**Comment by VictoriaODell** [comment]
@mateoclarke sent out one for feedback on this year's event I believe.

**Comment by mateoclarke** [comment]
Only one response:
https://docs.google.com/spreadsheets/d/1rG6p_l3THR8kRLhqKwsxeC65_Vnw0FfHh1LXdpJ5TWQ/edit?usp=sharing

**Comment by mateoclarke** [comment]
Added link to Github for all the closed issues to the main playbook under the pre-event planning section.
