### ISSUE TITLE
[Code Across] Send Email with FAQs, Program, and Parking Map to Attendees

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#124]
## FAQs
Do you have to enter with a team?
- No we will not pre-selected teams. Activities will start in larger groups and converge into smaller groups throughout the day, but you should not expect to work with the same team throughout the event.

Can you go solo and be placed on a team? 
- Groups will form organically around issues or problem statements that folks want to work on.

What is the expectation of your background? 
- There are no prerequisites in your background. I guess we are assuming that participants live or work in Austin/Travis County and have some ideas to share about pain points or challenges our community faces. But the challenges could also be more global than our community.

Can you join as an interested visual/ux designer? 
- Designers are very much encouraged to attend!

Should I come with a project pitch?
- This event is not a typical pitch/hack/present hackathon. We'll collaborate as a group to identity problem statements and lay the groundwork for these problems to turn into project ideas that can be pitched at the ATX Hack for Change or other hackathon events.

This isn't a typical "hackathon." We don't expect groups to make much progress towards prototyping solutions. At this event, we want to focus on "problem statements." So the activities will be more in line with a facilitated design-thinking workshop. It will be very beginner friendly and will lay the ground work for more involved civic hacking through design and development to occur at Civic Hack Nights and at the ATX Hack for Change on June 3-5.

##  Program
[Google Doc](https://docs.google.com/document/d/1zg3RE5ue203FxL01eSn3m3Nx81IdZs0TUz6YPnfymA4/edit?usp=sharing)

## Parking Map
![image](https://cloud.githubusercontent.com/assets/5697474/13386403/b092157a-de71-11e5-9d60-a96bc42ab289.png)

**Comment by luqmaan** [comment]
Is this a hackathon?

- No, Code Across Austin is not a hackathon in the sense of shipping code. CodeAcross is about bringing in dev, designers, etc that would normally come out to our events ​*plus*​ non-profits, city staff, community organizers etc that normally would not come to our hack events. Our bimonthly hack nights are more focused on shipping code. Find the next Open Austin hack night at http://www.meetup.com/Open-Austin/.

**Comment by mateoclarke** [comment]
- sent FAQ email.
- scheduled parking and bus info email for 1 day 6 hours before event.
