### ISSUE TITLE
What should we do with the existing Open Austin webapps?

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#125]
These webapps are running on the Open Austin server.

- austin-recycles.open-austin.org
- bike-buddy.open-austin.org
- data.open-austin.org
- tec-filer.open-austin.org
- cute pets atx

We need to decide what to do with them:

- Enhance them
- Leave them running as is
- Archive them

**Comment by mateoclarke** [comment]
Are there any negatives to leaving them running as is on the CH3 Data server that Chip has managed?

I think Data and Cute Pets are the two that have the most priority. But would like the other 3 to stay running for archival reference if the cost isn't too high.
