### ISSUE TITLE
[Code Across] Follow up emails with more info

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#126]
- [Google Slides](https://drive.google.com/open?id=1aWNB5wWr9ZIjwvMNEZR2uoGJcK9zDKuFw0_B1JIhFBk)
- Link to Slack
- Link to Github issues with Code Across tag
- Upcoming events

**Comment by luqmaan** [comment]
Can I get a link to the slides? I want to post them to Meetup.

**Comment by mateoclarke** [comment]
https://drive.google.com/open?id=1aWNB5wWr9ZIjwvMNEZR2uoGJcK9zDKuFw0_B1JIhFBk

**Comment by VictoriaODell** [comment]
Here is the view only link: https://docs.google.com/presentation/d/1aWNB5wWr9ZIjwvMNEZR2uoGJcK9zDKuFw0_B1JIhFBk/edit?usp=sharing

**Comment by mateoclarke** [comment]
<img width="475" alt="screen shot 2016-03-07 at 9 18 34 am" src="https://cloud.githubusercontent.com/assets/5697474/13573515/a83e3802-e445-11e5-988e-fc0501d72e83.png">
