### ISSUE TITLE
[Code Across] blog post summary

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#127]

**Comment by mateoclarke** [comment]
Content from the thank you email:

```
We hope you enjoyed spending your Saturday as a "Civic Hacker" at CodeAcross. As we gear up for the ATX Hack for Change on June 3-5, there are some opportunities to hack you projects forward. We encourage you to find us on Meetup.com and check our website for the next Open Austin events. You can also join us on Slack to chat about your project ideas and create a #channel for your team to collaborate online.

Upcoming Events:

Saturday, March 19: Civic Hack Saturday @ Urban Co-Lab
Tuesday, April 5: Civic Hack Night @ WeWork
Here are a couple things we wanted to share to recap the event and help your projects going forward.

CodeAcross Austin 2016 Slides
Monique's Code for America Slides
Github Project Ideas
Open Austin Slack Group
Tweets from #codeacrossatx
We'd appreciate your input on how to make this event better in the future. Here's an optional feedback form. Your honest input is appreciated!
```

**Comment by VictoriaODell** [comment]
I can work on this tonight + add photos in.
Where would I post it though?

**Comment by mateoclarke** [comment]
@VictoriaODell good question on how to post to the new Jekyll site. 

A couple options:
1. _(Easiest)_ Draft it in Google docs and send it to me or @luqmaan
2. _(Hardest)_ Clone the `open-austin-org` repo to your local computer and submit your draft via a Pull Request to `master`. I use an app called [MacDown](http://macdown.uranusjr.com/) to edit Markdown files. Advantage to this is you can preview what the post will look like on you local machine before deploying.
2. _(Recommended)_ Draft it on Github.com
  - Go to: https://github.com/open-austin/open-austin.github.io/tree/master/_posts
  - Create a new file (see image)
<img width="1117" alt="screen shot 2016-03-07 at 2 36 01 pm" src="https://cloud.githubusercontent.com/assets/5697474/13582507/664d0c70-e472-11e5-81b1-7cf8bba3ad40.png">

  - name the file `YYYY-MM-DD-title-of-article.md` 
    - EX: `open-austin.github.io/_posts/2016-02-27-uzbekistani-delegation-shares-their-experiences-with-open-data-on-austin-visit.html`
  - Use the template below at the top of your new markdown file. (It's called [YML Front Matter](https://jekyllrb.com/docs/frontmatter/)). 
  - Draft the body of the post below the `---` in markdown and/or HTML (Markdown compiles to HTML)
  - Don't forget to upload the thumbnail image you specified in the front matter to `https://github.com/open-austin/open-austin.github.io/tree/master/assets/images`. You should be able to click the "Upload files" button.
    - All other photos you should be able to drag and drop directly into the github WYSIWIG.
  - Save your file creating a new branch, opening a pull request and requesting someone to review and merge. 
    - OR Publish it straight to `master`. Do this if you feel brave.
<img width="872" alt="screen shot 2016-03-07 at 2 54 17 pm" src="https://cloud.githubusercontent.com/assets/5697474/13582973/ae1a74be-e474-11e5-9a2a-6acf1ded30a4.png">

```
---
layout: post
title: Title of your article
date: YYYY-MM-DD
type: post
published: true
thumb: filename.jpg
thumbalt: Alt text describing the thumbnial
author:
  first_name: First
  last_name: Last
---
```

**Comment by mateoclarke** [comment]
btw, its totally on the todo list to better document this process. that was just a first stab. curious to hear what challenges you run into

https://github.com/open-austin/open-austin.github.io/issues/48

**Comment by amaliebarras** [comment]
Noiiiiiice!

**Comment by VictoriaODell** [comment]
Ok, putting something together now.

**Comment by VictoriaODell** [comment]
Link to draft.

https://docs.google.com/document/d/1wPTwPrGtF1H6XdX7vN-J80s_O1RePQoQveulimjyVcU/edit

**Comment by VictoriaODell** [comment]
I need to update what was posted with social sponsors + donor shoutouts
