### ISSUE TITLE
Make a Google Spreadsheet of Donors

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#129]
![screen shot 2016-03-15 at 11 00 15 pm](https://cloud.githubusercontent.com/assets/5697474/13801645/e36593f4-eb01-11e5-9125-65dca47a4ecc.png)

**Comment by mateoclarke** [comment]
or maybe I'll give AirTables a shot.

**Comment by mateoclarke** [comment]
https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=1121272520

**Comment by VictoriaODell** [comment]
@mateoclarke does a google doc seem okay? I'm not sure what the best solution is but we have a few things we need to document. I think 1 sheet with pages could work but I haven't used AirTables before.

**Comment by mateoclarke** [comment]
yeah, I like what you're doing. Let's go with that.

**Comment by VictoriaODell** [comment]
ok!

**Comment by mateoclarke** [comment]
The spreadsheet has been made. Going to close out this issue.
