### ISSUE TITLE
Find a Event Core Team Member

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#13]
- [x] Description of role
- [x] Announce at December meetup

**Comment by amaliebarras** [comment]
Possible responsibilities: 

- drafting out 2016 budget based on strategic plan
- procuring in-kind donations for meetups and hackathons 
- forming partnerships with companies around austin that would want to donate to our mission
- occasionally, tactfully asking members on the mailing list for donations when we need them
- attending CFA fundraising workshops :)

**Comment by amaliebarras** [comment]
https://github.com/open-austin/iced-coffee/issues/41
Per Dec 15 Core Team Huddle
Maybe fundraising position should be part of an events position. Make sure everything goes smoothly event wise. 


Description lives here: 
https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit 

"The Events Lead is responsible for organizing and facilitating the physical space at meetups, hack nights, and hackathons. They will work with their committee to draft out our budget based on facilities needs, partnering with organizations to secure food, space, and funds for events, and occasionally asking for donations on social media and from other invested parties. They would also work with the CFA fundraising team to attend workshops to help with these activities. "

**Comment by mapineda** [comment]
Interested in contributing as Events Lead. Will be at the meetup this weekend to discuss details.

**Comment by VictoriaODell** [comment]
@mapineda sweet!

**Comment by VictoriaODell** [comment]
Is this done then? :dancers:

**Comment by mateoclarke** [comment]
yeah!
