### ISSUE TITLE
Social Mixers

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#131]
What: 
Social mixers at coffee shops &/or bars with other local meetup groups and organizations.

When:
A monthly social hour would be ideal. Possibly starting in May to allow some time for organization and outreach. 

Why: 
A lot of our current events have our members pretty engaged in a presentation or projects and they don't allow much time for socializing(aside from after events). 

Also, this would allow us to reach communities that could help us close skill and demographic gaps. 

Ideally, they would also facilitate conversations about collaboration and help build a more cohesive tech community in Austin. 

Next Steps: 
- Find out what skills/demographics we could better reach out to.
- Assemble a list of meetups and organizations that could plug into Open Austin naturally
- Find a date in May to start the social hours
- Figure out which groups to reach out to first and invite them 
- Promote!

**Comment by mateoclarke** [comment]
Couple feelings on this:

- Social/happy hour meetups are cool and I agree, a good way to chat with our frequent members more. We've done a few, 18f, Monique in town, etc. Down to do more.
- "Social mixer" reminds me of college greek life, drinking, etc. Think this should be phrased differently.
- If the goal is to reach other communities, cross pollenate, get them involved in our work, why not open this to be at a venue that has wifi + coffee/beer/wine options for others that want to be more productive than social.

Maybe a good first step is to crash some Happy Hours that other groups host?

**Comment by VictoriaODell** [comment]
Despite my mention of continuing this conversation, This is actually a really weird week for me and I'm going to lay low. I currently don't want to discuss this further and am closing the issue for now.
