### ISSUE TITLE
Add ATXH4C workshops to calendar

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#134]
April 7: Hackathon 101
[event URL](https://dabble.co/austin/coding/classes/hackathon-101-with-open-austin-st-edward-s-university-and-city-of-austin-s-innovation-office)
- [x] Schedule tweets
- [x] Add to Google Cal
- [x] [Meetup.com](http://www.meetup.com/Open-Austin/events/230103725/)

May 5: Intro to Hackathon Tech + Tools
[event URL](https://dabble.co/austin/coding--3/classes/intro-to-hackathon-tech-tools-with-open-austin-st-edward-s-university-and-city-of-austin-s-innovation-office)
- [x] Schedule tweets
- [x] Add to Google Cal
- [x] [Meetup.com](http://www.meetup.com/Open-Austin/events/230103949/)

**Comment by mateoclarke** [comment]
and schedule some tweets!

**Comment by VictoriaODell** [comment]
👌🏼

**Comment by VictoriaODell** [comment]
I put some tweets in buffer for the event this Thursday. I'll promote it on our Facebook tomorrow and post it a few groups that may be interested. 

Once that's done we can start pushing the event that is in May. :bird:

**Comment by mateoclarke** [comment]
Added these to the Google Calendar. 

Should we add them to Meetup.com as well?

**Comment by VictoriaODell** [comment]
I think we should post to meetup. We get a lot of visibility there and I don't believe the others have a meetup account/ org.

**Comment by mateoclarke** [comment]
added meetup event...

**Comment by VictoriaODell** [comment]
I put a couple of tweets in the buffer but it's full now~
I scheduled some post for Facebook too. I think once we get a little closer we promote it more.
