### ISSUE TITLE
blog post idea: we gave the city these recommendations about agenda records and here is what they published

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#135]
https://docs.google.com/document/d/1FOLuCR6kRRTLQD5dyJCuIquRkEoaGi0aqAVlBFwVuPY/edit

https://data.austintexas.gov/Government/Austin-City-Council-Agenda-Items/es7e-878h?utm_content=buffer7d894&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by mscarey** [comment]
OK

http://www.open-austin.org/blog/2016/04/02/austin-city-council-agendas-become-open-data

**Comment by mateoclarke** [comment]
Hey @mscarey! Thanks for jumping in and handling this! Great job with the blog! :tada:
