### ISSUE TITLE
[Designing Mobility Workshop] Location time-checks

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#136]
- [x] Check if we can get in the library an hour early
- [x] Check YMCA availability + hours + cost
- [ ] Check in with the Lutheran church as a host space
- [x] Avoid knee activities!

Eric said ideally 9am - 4:30ish ...I think >.>  <.<

**Comment by mateoclarke** [comment]
I have an email out to the YMCA for availability and cost.

**Comment by amaliebarras** [comment]
I sent an email out to Karly this morning too, asking about Iron Yard, it might be a free space. April 24 is like week 9 or 10 for us so I will be in town and able to at least open up and lock up, if not attend.

Ill keep ya posted!

**Comment by mateoclarke** [comment]
Just called the library. No flexibility to start early. 10am is when the open. PERIOD.

**Comment by amaliebarras** [comment]
Iron Yard offered up their space for this event: 

> I will tentatively put it on our calendar until you get more details. Once you get the details, we'll make a Meetup event with the information you provide below. If you could confirm/send the information by April 11th, that'd be great. 
> Title
> Description
> Who is this for 
> Requirements
> Max: 40 students 
> 
> Let me know what you think!

**Comment by VictoriaODell** [comment]
Hey @amaliebarras that's neat~ At no charge? 

Right now I believe we are focused on staying around the Rundberg area since that's what we've scoped out and have started planning around. I think that has some flexibility since the workshop is centered around mobility but I'm unfamiliar with the Iron Yard campus and surrounding area.

**Comment by amaliebarras** [comment]
I saw that conversation, but saw a few comments that you weren’t having any luck with library / church venues, and we’re coming up close to the date if we want to include the location in promo, etc.. 

Iron Yard would be free. It’s right across Woodland from St. Eds, is bike able from my house (central) has a bus stop close by, and has parking.

**Comment by mateoclarke** [comment]
Thanks for making moves on this @amaliebarras!

Iron Yard is a great venue. And I'm totally interested in making an event work there. But for this particular event, I'm worried about whether there are many places within walking distance that are conducive to man-on-the-street style interviews. A big component of the morning is ethnography/interviews in the field. So we need to be close to a place where 10 groups of 4 people can spread out, make observations, and ask people questions. Not sure if Penn Field has much to offer there. Even a walk to St. Ed's wouldn't give groups very much diversity in subjects. 

That kinda make sense? Am I wrong @VictoriaODell?

**Comment by VictoriaODell** [comment]
No, that sound right @mateoclarke. 

We do still need a spot for our upcoming Civic Hack Saturdays though. Isn't this month our last at Urban Co-lab before we would have to pay?

**Comment by amaliebarras** [comment]
I get what you mean, but I think there are a few areas around here that
would have people hanging out on a Saturday that would be good enough for
an interview. You wouldn't think so because Iron Yard is tucked in, but
Penn Field as a complex is a very short drive to that giant Ben White
shopping center w/ Target / Wheatsville, biking distance to Radio and that
whole area, and a walk from Opal Divines / apartment complexes with shops
underneath, & yeah, also St. Eds.

I get why Rundberg would be more ideal, but I do think south would be good
enough for our purposes. And the date is close, and I think it makes sense
to save on cost too.

If yall are sure-sure I'll tell Karly nvm, but wanted to try to convince
yall one last time since it's a guaranteed free space if we want it?

**Comment by mateoclarke** [comment]
Yeah, I hear all that @amaliebarras. The places you listed would work well. I think maybe @VictoriaODell should scout it out when she has a chance. And maybe loop in Eric once you have a better impression. 

From an initial conversation I had with him way back when this event was just an idea, I think I recall that he didn't really like the idea of groups having to drive to do ethnography. And its a big assumption that folks would bike to the event and thus be able to bike as groups. But a nicer space with more flexible start and stop times might be the trade-off we make for not as accessible ethnography subjects.

**Comment by VictoriaODell** [comment]
I can try to swing by the area tonight after work to check it out. Tomorrow I want to be at our Civic Hack night and Wed-Fri I'll be in SA for the NNIP conference. 

I'll update ya'll this evening.

**Comment by amaliebarras** [comment]
Yeah @victoriaOdell come scope it out and eat lunch with me 😻

Even if it was in Rundberg, I was thinking that the only people who wouldn't be able to drive were those who walked and biked to the event, which would probably be people who lived in Rundberg. And we will have at least a few OAers there with cars. But it's also awkward logistically to drive by interview hahah

**Comment by VictoriaODell** [comment]
@amaliebarras it's almost dinner time! lol. Javier is going to pick me up from work and we'll drive by the area to check it out here in a few.

**Comment by amaliebarras** [comment]
Haha I sent that before you said you were going tonight. But ok enjoy!

**Comment by VictoriaODell** [comment]
Hey~
I checked out the area. Torn between the trade-offs.

 X_X

**Comment by VictoriaODell** [comment]
Talked to Eric this past week. 
He spoke with his design team and the library should work with the times we have now.~

Thanks again, @amaliebarras for looking out for us too!
