### ISSUE TITLE
[Designing Mobility Workshop] Sponsorship/ Prosepctus

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#137]
### [Donor Partner Prospectus: Designing for Civic Solutions Workshop](https://docs.google.com/document/d/1Fc2awKqL2YTEHrjiN_iKomradNqiNbhJUp1y40hDj1U/edit)

- [Email template](https://github.com/open-austin/iced-coffee/issues/137#issuecomment-207855424)
- [Eventbrite](https://www.eventbrite.com/e/designing-for-civic-solutions-workshop-tickets-24534044989)

### Donors Logos
![austin-cityup-logo-official-small](https://cloud.githubusercontent.com/assets/5697474/14416435/b525f15a-ff6f-11e5-8393-1a7362107c6f.png)
![hubciti](https://cloud.githubusercontent.com/assets/5697474/14416438/b6543d5c-ff6f-11e5-8572-e54e1c167692.png)
<img width="378" alt="ibm-design" src="https://cloud.githubusercontent.com/assets/5697474/14720771/af22cc68-07c8-11e6-9eb1-d9699a33c934.png">
<img width="360" alt="austin-b-cycle" src="https://cloud.githubusercontent.com/assets/5697474/14720772/af2da8ea-07c8-11e6-87cb-7d3eee713605.png">
![usaa](https://cloud.githubusercontent.com/assets/5697474/14720773/af32ac32-07c8-11e6-9ad1-236835c4dd1e.png)

### Potential donors:
- [x] Austin City Up partners (Vizias & Hubciti have stepped up so far)
- [x] IBM Design (probably getting supplies, waiting for followup)
- [x] IBM Bluemix - mateo emailed Kay
- [x] Ridescout- Now Moovel. The email bounced (mateo emailed Meg Merritt)
- [x] B-cycle - mateo emailed ED and Marketing seperately
- [x] USAA - mateo emailed contacts who supported Ship It Weekend
- [x] Spokefly / winter
- [x] Tech Pines / So cold 
- [ ] Car2Go
- [ ] Silvercar
- [ ] _Add more..._

**Comment by VictoriaODell** [comment]
Potential contacts to reach out to should be posted on the [Master contact list](https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=516533352)

@mateoclarke you had some recommendations for people to reach out to. Can you post them here, identify them on the list/add them? 

I know we identified IBM design.

**Comment by mateoclarke** [comment]
Here is the potential sponsors doc we started earlier this year:
[Potential 2016 Sponsors](https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit)

For this event, I think it makes sense to focus on orgs that have a specific interest in Mobility and/or Design (not just straight up tech companies, at least at first). @VictoriaODell, please let me know as soon as you have the sponsorship prospectus drafted. That will be really important. I plan to share it via the Austin City Up email group because they are super focused on transportation right now with Austin being announced as a finalist for the [Department of Transportation Smart Cities grant](https://www.transportation.gov/smartcity). That listserv includes groups like RideScout, CapMetro, Living Planet, Vizias, etc.

I'll reach out to my buddies (_cough_: @techtolentino & @chrsfshr) about any connects they might have at IBM Design who know who to ask about community donations to help use cover the cost of lunch boxes, Post It Notes, and other materials.

**Comment by VictoriaODell** [comment]
@mateoclarke will do. I'll work on it some tonight!


:star2:

**Comment by VictoriaODell** [comment]
Rough first draft here: https://docs.google.com/document/d/1Fc2awKqL2YTEHrjiN_iKomradNqiNbhJUp1y40hDj1U/edit

I left comments for myself to come back and edit. I pulled some of the language from the AC4D workshop page. Kinda busy since I'm with family in Galveston but want to get this done tomorrow if possible. 

@mateoclarke had some things that need to be discussed~
A few comments directed towards you.

**Comment by mateoclarke** [comment]
Thanks for getting that started @VictoriaODell!

I just added my comments. Lmk what's next. We should also pass it to Eric for review before we send it out. Want to make sure he's cool with us calling out AC4D alumni. Think he will be but just in case.

**Comment by mateoclarke** [comment]
Also, are we set on the name "Designing Mobility Workshop"? I kind of just threw that out as a random place holder.

some others ideas started with the pair Eric threw out:
- Civic Design Workshop/Bootcamp
- Design-led Innovation Impact Lab
- Human-Centered Design Workshop/Bootcamp
- Mobility Innovations Workshop
- Designing Innovations for Mobility

haha these all sounds so buzzwordy :bee: 

cc/ @VictoriaODell

**Comment by VictoriaODell** [comment]
Yeah, a little buzzy. :bee: 

What about 

- Designing for Austin Workshop
- Designing for Civic Solutions Workshop


I was just thinking we should probably follow up with Daniela and let her know what we decided on too. I can do that.

**Comment by mateoclarke** [comment]
I like those better! :smile: 

Of the two I vote "Designing for Civic Solutions Workshop"

**Comment by VictoriaODell** [comment]
Sweet.  Making the changes in the document now.

**Comment by VictoriaODell** [comment]
I think it's good to send to Eric to review now. :eyes: :page_facing_up:

**Comment by VictoriaODell** [comment]
@mateoclarke Have you sent this to anyone yet? If so who? I don't want to duplicate efforts. I can send some stuff out today.

**Comment by mateoclarke** [comment]
Behind on email so much I'm dreading it. 😖

Will start a list up a the top :arrow_up: with folks I reach out to.

**Comment by VictoriaODell** [comment]
~Email party~

**Comment by mateoclarke** [comment]
## Email template:
---
Hello {person/company}!

Open Austin is partnering with alumni from the Austin Center for Design to host a free to attend workshop on using design thinking and ethnographic research for civic problem solving. 

Our upcoming event on Saturday, April 23rd will focus on addressing civic issues under the theme of Mobility. We are asking for donations to help us pay for coffee, lunch, and post it notes for our attendees. Donors will be recognized in the lead up to and during the event. They will also be recognized in our event recap.

Would you or your company be interested in participating as a donor partner for this community event?

Here are more details:
https://docs.google.com/document/d/1Fc2awKqL2YTEHrjiN_iKomradNqiNbhJUp1y40hDj1U/edit?usp=sharing


Thanks!

**Comment by mateoclarke** [comment]
We have donor commitments from Vizias and HubCiti! I've added their logos up top :arrow_up:. We should start including the logos as we move forward with the event page and slides.

There might be a few more via the City Up consortium so I'll keep the door open on that and wait a few more days before I finalize the amount that each of those companies are willing to give.

**Comment by VictoriaODell** [comment]
Added both logos to the Eventbrite page and slide deck. Need to update the blog post. >,>

**Comment by VictoriaODell** [comment]
@mateo
So HubCiti donated $100, Vizias donated $100, b-cycle donated $100 and IBM donated supplies correct?

**Comment by mateoclarke** [comment]
and USAA donated $300 just today. I've added all their logos to

- the Google slide deck
- the Eventbrite
- the event blog post
- the Press Release blog (no logos, just listed)
- the Press Release Google Doc  (no logos, just listed)

**Comment by mateoclarke** [comment]
forgot to add the logos to the program, just did that.

**Comment by VictoriaODell** [comment]
💰 💸
