### ISSUE TITLE
[Designing Mobility Workshop] Make Event Program

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#138]
This is what we did for Code Across:
https://docs.google.com/document/d/1zg3RE5ue203FxL01eSn3m3Nx81IdZs0TUz6YPnfymA4/edit

This is the DR worksheet that we'll run participants through:
http://library.ac4d.com/d/AC4D_designlibrary_worksheet_DesignResearch.pdf

And here is the rough agenda:
9:00AM – Introductions and Introduction to Design Research
10:00AM – Focus Generation
10:30AM – Field Research
12:00PM – Break and Lunch
1:00 PM – Synthesis
2:00 PM – Ideation and Down Selection
3:00 PM – Story Boarding as Prototyping Tool
4:00 PM – Next Steps and Closing

**Comment by VictoriaODell** [comment]
Sent an email to Eric to check up on this since time has changed.

**Comment by VictoriaODell** [comment]
Updated Agenda from Eric: 
Need to input this in the program 
10:00AM – Introductions and Introduction to Design Methods (Vickie/Mateo for 5-15 minutes, then Eric)

11:00AM – Research, Focus Review + Field Research (Bhavini)

12:30PM – Break and Lunch

1:30 PM – Synthesis (Laura)

2:45 PM -- Break

3:00 PM – Ideation & Down Selection (Samara)

3:45 PM – Story Boarding as Prototyping Tool (James)

4:40 PM – Next Steps and Closing (Vickie/Mateo - we can adjust back to 4:35 or 4:30 as needed for a closing

**Comment by VictoriaODell** [comment]
Sent to Eric and Daniela to review!

**Comment by VictoriaODell** [comment]
I think this should be good to go. 
https://docs.google.com/document/d/1z9QM_Ne5mQFhcL-P8GWIaD4oGPdTa-TkHwecdYnsLYg/edit#

**Comment by VictoriaODell** [comment]
🙌
