### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#140]
### [Eventbrite page](http://www.eventbrite.com/e/designing-for-civic-solutions-workshop-tickets-24534044989)

- [x] Working on the event page on Eventbrite page, Right now. 
- [x] I know Eric mentioned bios. I'll check in with him on that. 
- [x] Create a blog post announcement on open-austin.org

**Comment by VictoriaODell** [comment]
@mateoclarke should I keep this question? 
"Would you like to receive updates about the ATX Hack for Change hosted by St. Edward's the first weekend in June?"

**Comment by VictoriaODell** [comment]
Event page here: http://www.eventbrite.com/e/designing-for-civic-solutions-workshop-tickets-24534044989

I'm going to share it with Eric and check in about the bios.

**Comment by mateoclarke** [comment]
yeah, i would keep the question. It doesn't hurt.

**Comment by VictoriaODell** [comment]
@mateoclarke Q: How do you make the event image big and at the top? I can't figure it out :cat2:

**Comment by mateoclarke** [comment]
It has to do with which version of their WSYIWYG editor you pick. I switched it to their "Standard Editor"

![screen shot 2016-04-09 at 5 01 40 pm](https://cloud.githubusercontent.com/assets/5697474/14406692/ef055f88-fe74-11e5-98ec-1788ae09a41b.png)

**Comment by mateoclarke** [comment]
Added todo up top to create a page on our site.

**Comment by VictoriaODell** [comment]
Blog post live: http://www.open-austin.org/blog/2016/04/12/designing-for-civic-solutions-workshop

**Comment by VictoriaODell** [comment]
*foams at mouth*
