### ISSUE TITLE
Open Austin Sponsorship packet

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#142]
We should work on a partnership packet to help us with our outreach for $$$
## Here are some great resources to get us started

[NDoCH Kickoff presentation that includes slides about sponsorship
](https://docs.google.com/presentation/d/1XgZZin13bPW0Xep7iTemRfJnJ9T-3TRDp6uul0bab_Y/edit#slide=id.g85f3b8d0c_4_0)[Recording of presentation ](https://slack-redir.net/link?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Do9m9W13rg28)
[Sponsorship packet example](https://drive.google.com/file/d/0B-GJy0IrL0gMTWVBY01vQnplcUk/view)

This template is editable and we can plug in all our info. We just need to gather it. No need to reinvent the wheel. 
## Here is the unique content we need.:

Once we get this content I can flow it into the indesign document and make styling changes so it better reflects the Open Austin brand. **_[Google doc where this stuff lives](https://docs.google.com/document/d/1Q2of58M4zLPnNQAM8fybtlMo7LI7z_4dWyJdQyzLrMg/edit)_**
### One page letter
- [ ] Brigade’s mission
- [ ] Highlight upcoming event
- [ ] Summarize needs
### Brigade overview
- [x] Brigade’s mission
- [ ] 2016 Theme
- [x] Target Audiences
- [x] Supporters
- [ ] Press
### Ongoing Projects x3 - @luqmaan can you help fool these out in the document?
- [ ] Name x3
- [ ] Description x3
- [ ] Image x3
- [ ] Project Owner x3
- [ ] Url link x3
### Sponsorship packages
- [ ] Level ($$)
- [ ] Value of package level
- [ ] Description
- [ ] Address or Url (where can sponsor donate)

**Comment by VictoriaODell** [comment]
Goals would be to get this done by the end of the month/2 weeks so we can send this out and get taco money and stuff~ @luqmaan

**Comment by mateoclarke** [comment]
How is this coming along? Feel like we could probably find a sponsor for tacos at the June 7 if we have an ask ready by the end of this week, or next?

**Comment by VictoriaODell** [comment]
EOW next week is more reasonable. 
I cant start flowing what we have into the template.

**Comment by VictoriaODell** [comment]
Here is a prospectus I made for work: 
[AnacondaCon_Prospectus_preview_v25.pdf](https://github.com/open-austin/iced-coffee/files/287771/AnacondaCon_Prospectus_preview_v25.pdf)


@mateoclarke would be great to get a letter similar to the one on page 4 but for Open Austin. It would not have to be as long. I'm making this prospectus horizontal since It'll likely just be living digitally.

**Comment by VictoriaODell** [comment]
Super WIP But here is the current iteration of the prospectus
[OA_sponsorship package_v2.pdf](https://github.com/open-austin/iced-coffee/files/287812/OA_sponsorship.package_v2.pdf)

**Comment by mateoclarke** [comment]
added a personal letter. It probably sucks. Sorry, open to suggestions.

**Comment by VictoriaODell** [comment]
@amaliebarras I'm working on this and I think it would be cool if we had some stats on membership or somethind. Do we have anything we can use? I know you made that one infographic but idk where it is
>.>
<.<

**Comment by amaliebarras** [comment]
https://drive.google.com/drive/folders/0B9wiW10zDGPCMm44R2NPRTZpeEE Infographic filez here bb

**Comment by mateoclarke** [comment]
From the 6/1 coreteam huddle:

Add to prospectus: (Vickie)
http://www.open-austin.org/projects/atx-buildings-osm-import.html

**Comment by mateoclarke** [comment]
Do we want to do this still for the original reason stated? We've been able to raise funds without a fancy packet.

But, I really love the layout of https://github.com/open-austin/iced-coffee/files/287812/OA_sponsorship.package_v2.pdf

Maybe we could repurpose this for a year end report to print for donors and key partners?

**Comment by jonplaca** [comment]
Seems like I might be late to the party here, but I am happy to help out on with respect to this (after we form an official nonprofit and establish proper accounting). Happy to discuss in more detail about how we can develop a financial model and track out fundraising progress throughout the year (helping us plan for executable, future events).

**Comment by mateoclarke** [comment]
A simple example from another brigade:
[sponsorship.pdf](https://github.com/open-austin/iced-coffee/files/777419/sponsorship.pdf)

**Comment by VictoriaODell** [comment]
Vicky Prigden mentioned being able to help with Biz dev and potentially this. I just reached out to see if she would be interested in pushing this forward.

**Comment by VictoriaODell** [comment]
Here is a another template that Sarah started: 
https://docs.google.com/document/d/1CG1Td5KrQF6tnjwr_hthKyrnCi4Sd7xmQWDket9YuyI/edit?usp=sharing

**Comment by VictoriaODell** [comment]
@sortizsh and @jonplaca and I met today to go over this again. I'm getting a google doc together today. 

https://docs.google.com/document/d/1Q2of58M4zLPnNQAM8fybtlMo7LI7z_4dWyJdQyzLrMg/edit?usp=sharing

We will then send this out to folks we know that can review before prettying things up.
