### ISSUE TITLE
Press release

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#143]
Create a Press release for our event Next Saturday. 

I can start drafting.

**Comment by VictoriaODell** [comment]
@mapineda you said you could help get this out correct?

**Comment by mapineda** [comment]
Yes

Marco Pineda

**Comment by mapineda** [comment]
Is there a google doc draft we can work on together? Also, is do we have a  list of media correspondents to send this out to after it is finished?

**Comment by VictoriaODell** [comment]
[There is now!](https://docs.google.com/document/d/1OggfmlmVulXgbnBaSnaS8CETE1xfKdNJBF2BpYwOp3w/edit?usp=sharing)

I think we do have a list in another issue that has news contacts we just need to fish around for it. :eyes:

**Comment by mateoclarke** [comment]
I think I moved all the old press contacts that Chip collected into the [Master Contact List](https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=516533352). We definitely should add more contacts from places like Built In Austin, Austin Monitor and 512 tech.

**Comment by VictoriaODell** [comment]
Okay, I think we have a pretty good start. 

I'm sending Eric and Daniela an email update about with the program today and will ask if we can get a quick quote to include in our press release.

**Comment by VictoriaODell** [comment]
Updated to include quotes. Super excited for how this is turning out @mapineda ! 

https://docs.google.com/document/d/1OggfmlmVulXgbnBaSnaS8CETE1xfKdNJBF2BpYwOp3w/edit

**Comment by mateoclarke** [comment]
@VictoriaODell: maybe we should add one sentence recognizing our donors?

**Comment by mateoclarke** [comment]
added a line, but it bumps the ### to the second page, oops.

**Comment by VictoriaODell** [comment]
@mateoclarke Awesome. I just add the ### to the page footer. 
Will post this on our blog now and we can tweet/ start emailing it out.

**Comment by VictoriaODell** [comment]
Posted on the website: http://www.open-austin.org/blog/2016/04/18/open-austin-collaborates-with-ac4d-alumni-to-host-workshop

Heh, maybe should have found another picture but I'm at work right now💻

**Comment by VictoriaODell** [comment]
📄
