### ISSUE TITLE
[Designing for Civic Solutions] Gather supplies

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#144]
- [x] 40 Pen, Pencil, Sharpie, Highlighter (1 per participant) - each will need these for note taking during research, as well as drawing during the storyboarding time.
- [x] Clipboards - 2 per group for note taking in the field
- [x] Pins/Easels/Tape - Participants will need to put their research - namely, hand scribed notes from cut outs from 8.5x11 sheets of paper, onto "something" - whether that's wall space, an easel, or pin board for easy movement around. 4' x 8' foam boards that we lean against walls would work
- [x] Scissors, 1 pair per group
- [x] Stickie Notes - Per group, a stack of 3 colors, ideally green/blue/yellow, but it doesn't matter as long as there is 3 colors.

**Comment by VictoriaODell** [comment]
We have 
- 51 sharpies with Fine points
- 25 "flip chart"/fat sharpies
-  ~ 79 pens
- 2 pairs of scissors
- 3 small things of tape
- 5 rolls of duct/large tape
- 48 pencils 

Post its
Stacks= The amount I would feel okay giving 1 person/ group depending on the activity. I should check with Eric about consistency of the colors. ;_;
- 6 stacks of teal
- 11 stacks of coral
- 5 stacks of hot pink
- 5 stacks of green
- 13 stacks of orange
- 7 stacks of baby blue
-11 stacks of light pink 
- 6 stacks of light yellow
-9 stacks of green

**Comment by VictoriaODell** [comment]
✏️ 📃
