### ISSUE TITLE
Blog post for Open Gov meetup

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#145]
[I started a post ] (https://docs.google.com/document/d/1TBvnvRl1MZRj7DK9o6Y_2Ep92bQ0FuB3lHusHaMavdM/edit) but it's kinda incoherent right now. >.>

@mateoclarke and @amaliebarras ya'll take notes too? 👀

**Comment by amaliebarras** [comment]
I took no notes :( :( :( 
I took pics though :) You can also use my ones on twittah

**Comment by VictoriaODell** [comment]
No problem! I know you did last time that's why I'm asking. I'll likely use some tweets. 🐤🐦

**Comment by VictoriaODell** [comment]
Ann is sending her slides tonight and will send the scans of our maps tomorrow. 🗺 

I'll work on cleaning this post up some tonight.

**Comment by mateoclarke** [comment]
I got some notes. I can add stuff and post today.

**Comment by VictoriaODell** [comment]
Ann just sent me the slides and scans I can post them once I get to my computer.

**Comment by VictoriaODell** [comment]
[Austin's Atlas Scans.pdf](https://github.com/open-austin/iced-coffee/files/233603/Austin.s.Atlas.Scans.pdf)

**Comment by VictoriaODell** [comment]
[April 18 presentation_smaller.pdf](https://github.com/open-austin/iced-coffee/files/233605/April.18.presentation_smaller.pdf)

**Comment by mateoclarke** [comment]
✅ 
http://www.open-austin.org/blog/2016/04/24/open-gov-civic-tech-austin-atlas-recap
