### ISSUE TITLE
Post event blog post

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#147]
Write up with:

- [x] links to [opening-closing slide deck](https://drive.google.com/open?id=0BwKb2oghmQldd3o1RWxEQjh5RlU)
- [x] [link to AC4D resources](http://library.ac4d.com/)/ Won't be getting their slide deck 
- [x] Tweets from participants
```
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Doing some ethnography with Open Austin! <a href="https://twitter.com/vegangrrl">@vegangrrl</a> <a href="https://twitter.com/ramirezal3">@ramirezal3</a> <a href="https://t.co/taQf9RkFx4">pic.twitter.com/taQf9RkFx4</a></p>&mdash; mae (@maebees) <a href="https://twitter.com/maebees/status/723922394889379842">April 23, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```
```
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/Empathy?src=hash">#Empathy</a> needed in human-centered design - Eric Boggs, <a href="https://twitter.com/AC4D">@AC4D</a> w/ <a href="https://twitter.com/openaustin">@openaustin</a> <a href="https://twitter.com/hashtag/mobility?src=hash">#mobility</a> <a href="https://t.co/TAtIonPw6P">pic.twitter.com/TAtIonPw6P</a></p>&mdash; Daniela (@vegangrrl) <a href="https://twitter.com/vegangrrl/status/723899500662661125">April 23, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

- [x] [Workshop images](https://drive.google.com/open?id=0BwKb2oghmQldd3o1RWxEQjh5RlU)
- [x] Special thanks and shout out to sponsors
- [x] Special thanks + shout outs to Facilitators

**Comment by VictoriaODell** [comment]
I reached out to Ellen to do a separate blog post about her experience as a participant/ what she took away from the event. Hopefully, we can get that by Sunday. 

Workin on putting this post together now.

**Comment by VictoriaODell** [comment]
WIP: https://docs.google.com/document/d/1FwSmxSotPZiQUllNeXrBghny9f7I0Yt6GfXhC4uhywE/edit#

**Comment by mateoclarke** [comment]
we should make sure to post this blog to https://cfa.slack.com/messages/brigade-wins/

**Comment by VictoriaODell** [comment]
📆 📆 📆 💀 
Publishing tomorrow
https://github.com/open-austin/open-austin.github.io/blob/Workshop-Recap-Draft/_posts/2016-05-28-Recap-Designing-for-Civic-Solutions.md
