### ISSUE TITLE
Post Event Retrospective

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#149]
@mateoclarke @luqmaan After/if we get some feedback on from the survey we should make some notes on what went right and what went wrong.

**Comment by mateoclarke** [comment]
sounds good. Would love to hear how things went in the afternoon!

**Comment by mateoclarke** [comment]
feel like this is long enough past and the outcomes of this guiding our decision to focus on weekly events back in late May/June. If we want to retrospect on this further, we should add it to a core team huddle or reopen here. Closing this now...
