### ISSUE TITLE
New Project Idea Onboarding / MOU

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#15]

**Comment by mateoclarke** [comment]
Here's an MOU template for sponsors we can build on:
https://docs.google.com/document/d/1lr7DO2c6Y-32HndZSyOr9khttJq9pbNf_pPNZkJlSrY/edit

**Comment by mateoclarke** [comment]
Moved this link into a wiki page. 
https://github.com/open-austin/iced-coffee/wiki/Templates-and-Docs

Closing this out...
