### ISSUE TITLE
5/28 Civic Hack Saturday

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#154]
- [x] Confirm location: Chicon Collective, 301 Chicon. Thanks @mapineda!
- [x] [Meetup](http://www.meetup.com/Open-Austin/events/wwjktlyvhblc/)
- [x] Google Calendar
- [x] Twitter

**Comment by mateoclarke** [comment]
@VictoriaODell Will you help us throw some tweets into the twitter machine next week before the Hack Saturday?

**Comment by VictoriaODell** [comment]
Posted on Facebook and have some tweets in buffer~
