### ISSUE TITLE
OA Table at ATX H4C

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#157]
## The plan
- Amalie to run table as needed on Saturday (with help from any other OA coreteam and members)
- Mateo to run table as needed on Sunday (with help from any other OA coreteam and members)

### Important Times:

Saturday:
- 7 a.m. In-Kind Sponsor Setup Alumni Gym
- 8 a.m. Breakfast Alumni Gym
- 9 a.m. Project Pitches Alumni Gym
- 12 p.m. Lunch Alumni Gym
- 6 p.m. Dinner Alumni Gym
- 10 p.m. Event Takedown Alumni Gym

Sunday:
- 8 a.m. Breakfast Alumni Gym
- 12 p.m. Lunch Alumni Gym
- 1 p.m. Project Reports Alumni Gym
- 2 p.m. Event Takedown Alumni Gym
- 3:30 p.m. In-Kind Sponsor Takedown Deadline Alumni Gym

Todo:
- [ ] Decide what materials are needed
- [ ] Set up table Saturday morning.
- [x] When are the key times to be at the table? _(waiting on Sarah)_

### Previous Discussion:
Sarah to us:
> I just wanted to share that you will have a table (Sat+Sun) to do with what you will at the event - if you wish to donate that space to another organization or showcase yourselves, feel free. I know you have some fun shirts and stickers!

Mateo to coreteam:
> What do y'all think about this offer from Sarah in regards to a table at the hackathon? Should we try to staff the table? Or just leave our stickers, banners, buttons and other marketing materials out, maybe with just a sign-up for more info sheet?

> I will have to miss most of the day Saturday because of my little brother's graduation ceremony so I'll leave this up to y'all.

> Are any of y'all planning NOT to attend the ATX Hack for Change?

Todo:
- [x] Decide if we want the table. 
- [x] Decide who will be there and at what times. 
    - _We don't necessarily need it occupied at all times._
    - I can take some time Sunday
- [x] Respond back to Sarah with our response.

**Comment by amaliebarras** [comment]
As long as it’s okay if it goes unmanned for a little bit, we should take the table. I’ll be the point person. & I’m more than down to be there when I’m not doing administratey things (like presenting and trello boarding or standups).

**Comment by mateoclarke** [comment]
cool we have a plan, added some notes above

**Comment by mateoclarke** [comment]
Details in PDF:
[SponsorPacket2016.pdf](https://github.com/open-austin/iced-coffee/files/273344/SponsorPacket2016.pdf)

**Comment by mateoclarke** [comment]
Added the important times above.

![](http://dsh.re/69f0d)

**Comment by VictoriaODell** [comment]
I don't believe I'm committed to anything yet and should also be able to help with the table as needed.

**Comment by luqmaan** [comment]
I'll do it.

**Comment by mscarey** [comment]
I'm only semi-committed to a project so far, so I can also be at the table if needed. (probably not Sat. PM though)
