### ISSUE TITLE
Onboard Gus

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#160]
Administrative
- [ ] send announcement
  - [ ] email
  - [x] slack
- [x] set up with hack@open-austin.org email
- [x] invite to #coreteam
- [x] invite to #icedcoffee
- [x] add to @coreteam slack group
- [x] access to open austin google drive
- [x] link to the [open austin strategic plan](https://docs.google.com/document/d/12EGMSZL2wGKpxwcxCFCTMoeRfx95h4eF493Bh5kdkkA/edit)
- [x] link to [core team roles](https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit#heading=h.lfkg13polpyn)
- [x] aws credentials
- [x] github credentials
- [x] access to lastpass
- [x] access to google calendar
- [x] schedule a core team meeting
- [ ] write up AWS usage instructions

For gus
- [ ] read strategic plan and update description of the role
- [ ] what do we need to do for the project process stuff?
- [ ] update leadership section http://www.open-austin.org/about/#our-leadership

**Comment by mateoclarke** [comment]
I added Gus to Google Drive and Calendar. 
I also updated the [email config](https://github.com/open-austin/server-configs/blob/master/email/virtual)
Guess we need to coordinate with Chip about updating the config on the email server.

**Comment by mateoclarke** [comment]
[Core Team Roles](https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit#heading=h.lfkg13polpyn)

**Comment by mateoclarke** [comment]
haha, I think gus has been onboarded and then...idk. This turned into a good coreteam onboarding list tho.
