### ISSUE TITLE
Publish ATX Hack for Change post

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#161]
Please give this a look and add comments or make suggestions.
https://docs.google.com/document/d/1HsmhD2-BzulE998aahxfXoUp1M1EU4BxEjibwuDVt8g/edit?usp=sharing

Should we create a Medium account to post there as well? cc/ @VictoriaODell

**Comment by VictoriaODell** [comment]
💯 
https://medium.com/@mateoclarke/think-government-is-broken-then-hack-your-city-f7f0a6c002c#.f58hdpiac
