### ISSUE TITLE
Get the CFAPI working again

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#162]
https://github.com/codeforamerica/cfapi
https://github.com/open-austin/Civic_Project

**Comment by mateoclarke** [comment]
We heard that CfA is dropping support of this bc they don't have any brigade engineers to maintain it. We might want to reopen this in the future, or create app or feed of our projects, be we should close this for now.

**Comment by luqmaan** [comment]
Looks like its still kind of supported: https://github.com/Code-for-Miami/code-for-miami.github.io/pull/19

https://codeforamerica-api.herokuapp.com/api/organizations/Open-Austin

@gusIreland Can you set this up?

**Comment by mateoclarke** [comment]
not very worried about support the CFAPI stuff right now. Seems like a very low priority for them and hopefully the brigades come up with a replacement
