### ISSUE TITLE
Research more about funding/ consulting 

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#167]
- What has worked for other brigades
- Where do we start
- What makes sense for us right now & in the future

**Comment by VictoriaODell** [comment]
This is awesome. But we're not ready. We can reopen this later. 
Maybe set a time in the future where we can really focus on this. It's a conversation we should start as a team.

**Comment by amaliebarras** [comment]
[My research / notes live here](https://docs.google.com/document/d/1835jKOd-DhZqeUaRX9_2HOMWmLWw3HU_80YiY3WW7_c/edit) for when we're ready to pick this back up
