### ISSUE TITLE
Hack For Change blog post

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#169]
1. What the event was
2. What the projects were
  - Description
  - Repo link
  - Photo

**Comment by mateoclarke** [comment]
https://opendata.bloomfire.com/posts/1176558-atx-hack-for-change-2016-recap

**Comment by mateoclarke** [comment]
http://www.open-austin.org/blog/2016/06/07/Recap-ATX-Hack-for-Change-2016
