### ISSUE TITLE
Schedule Hack Nights/Saturdays for second half of 2016

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#170]
We need to book locations for Civic Hack Nights/Saturdays starting in July going forward. Let's us this thread to coordinate who is reaching out to which potential sponsors.

The general pattern (with exceptions for holidays) is:
- Civic Hack Saturday on 1st Saturday
- Civic Hack Night on 2nd & 4th Tuesdays
- Civic Tech Meetup on 3rd Mondays

### June
- [x] Sat June 4 - Civic Hack Saturday / Hack for Change - **St. Edwards**
- [x] Tuesday June 7 - Civic Hack Night - **WeWork**
- [x] Monday June 20 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Saturday June 25 - Civic Hack Saturday - **Chicon Collective**
### July
- [x] Saturday July 2 - Civic Hack Saturday - **DevBootcamp (1705 Guadalupe St)**
- _4th of July Week_
- [x] Tuesday July 12 - Civic Hack Night  - **DevBootcamp**
- [x] Monday July 18 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Tuesday July 26 - Civic Hack Night  - **Cloudera (515 Congress, Suite 1212)**
### August
- [x] Saturday August 6 - Civic Hack Saturday - **DevBootcamp**
- [x] Monday August 15 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Tuesday August 23 - Civic Hack Night - **DevBootcamp**
- [x] Tuesday August 30 - Civic Hack Night - **Cloudera**
### September
- [x] Saturday September 3 - Civic Hack Saturday - **[The Comeback Space](http://www.thecomeback.space/) (902 E 5th St Suite 103)**
- [x] Tuesday September 13 - Civic Hack Night - **DevBootcamp**
- [x] Monday September 19 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Tuesday September 27 - Civic Hack Night - **DevBootcamp**

### October
- [x] Saturday October 1 - Civic Hack Saturday - _themed CHS [event with Women Who Code @ Dev Bootcamp](https://github.com/open-austin/iced-coffee/issues/174)_
- [x] Tuesday October 11 - Civic Hack Night - **data.world**
- [x] Monday October 17 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- Friday Oct 21 - Sunday Oct 23 - **2nd Annual ATX Diversity Hackathon**
- [x] Tuesday October 25 - Civic Hack Night - **DevBootcamp**

### November
- _November 1-3 - Code for America Summit in Oakland_
- [x] Saturday November 5 - Civic Hack Saturday - **Google Fiber Space**
- [x] Tuesday November 8 - Civic Hack Night -  **Galvanize**
- [x] Monday November 14 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- _Nov 21-25 - Thanksgiving Week_
- [x] Tuesday November 29 - Civic Hack Night - **DevBootcamp**

### December
- [x] Saturday Dec 3 - Civic Hack Saturday - **DevBootcamp**
- [x] Tuesday December 6 - Civic Hack Night - **DevBootcamp**
- [x] Monday December 12 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Sunday December 18 - Coreteam Leadership "Retreat" - _Google Fiber (N I35_
- [x] Tuesday December 20 - ATX Geo Bash 2016 - **Mister Tramps**

**Comment by mateoclarke** [comment]
_for posterity, this thread continues the work of #28_

**Comment by amaliebarras** [comment]
Can I reach out to Jessica from Cloudera first? Just because their location is closer to WeWork than DevBootcamp, and it'll be a smaller change for the people who work downtown and walk to CHN. 

If y'all agree I can email her this evening, and throw her dates for Jul, Aug, September.

**Comment by mateoclarke** [comment]
I’m down with Cloudera, esp for Tuesdays. I think we could get Dev Bootcamp for Saturdays.

A little worried that we would outgrow their space (in her email she said 35 ppl max with tables). But we can cross that bridge later.

@amaliebarras Will you get thoughts/confirmation from @luqmaan @gusIreland @mapineda before you email? Or we can just talk about it tonight.

**Comment by luqmaan** [comment]
All these dates look good to me. 👍 for emailing Cloudera/Dev Bootcamp first.

Should we try out one Saturday at Techranch? Or should we try to formalize things with Chicon Collective?

**Comment by mateoclarke** [comment]
From @mapineda talking, it sounded like Chicon is up in the air until they finalize their move. 

I'm thinking:
1: @amaliebarras checks Cloudera for Tuesdays in Jul, Aug, September
2: I check Dev Bootcamp for Saturdays Jul, Aug, September.

**Comment by amaliebarras** [comment]
works for me! Ill email this evening

**Comment by 100stacks** [comment]
Hey @mateoclarke @luqmaan @amaliebarras!  I don't know if ya'll are taking feedback from the community, I am with @luqmaan on a possible North Austin Saturdays/Tuesdays at Tech Ranch.  👍 

I think it's ok to have dual central and north meetups, since Austin traffic is such a 🐻  😫  🐲 !

**Comment by mateoclarke** [comment]
Ok, we have July confirmed! And we're just waiting to hear back from Cloudera for August CHNs. Let's see how these new venues work out but keep our ears to the ground for more options.

@100stacks, Tech Ranch is still a possibility. But for Tuesday nights, all of our core team works/lives in centrally so fighting traffic North would be harder for the organizers. There also isn't very good public transit options for folks that don't have cars to get there. The closet bus stop I saw is almost a mile away. When I asked Tech Ranch about Saturdays, they sounded lukewarm because they aren't normally open over the weekend. Overall, when we've had meetups North, like at Build-a-Sign, our turnout was smaller. But a big thanks for the feedback. We're definitely open to it always!

**Comment by 100stacks** [comment]
@mateoclarke, no worries thanks for considering.  Yeah I wish we had better multi modal public transportation options for getting around.  Happy 4th! 🎉

**Comment by mateoclarke** [comment]
Just added all these dates through the end of the year to the OA Google Calendar. Going to add it to our core team huddle to discuss whether we want to do events the week of Sept 5 and Oct 3.

**Comment by mapineda** [comment]
Book The Comeback Space for Saturday, Sept 3rd

**Comment by amaliebarras** [comment]
These are the details I have on August: 

"And let me check on the August dates with our new office manager, Marque, and will get back with you shortly.  I do know Aug 9th won’t work due to another meetup in the space but the other dates will probably work.  I’ll let you know shortly."

Cloudera is not being very responsive, at this point I think it would be easier to book DevBootcamp. It's just as convenient, free, and they are communicative and excited to have us.

**Comment by mateoclarke** [comment]
Dev Bootcamp confirmed for Aug 9. Going to ask them if we can do an ongoing deal.

**Comment by mateoclarke** [comment]
since we moved the Aug 9 CHN to Aug 23 to spread out the schedule better, I just emailed Dev Bootcamp to see if that Tuesday will be open or not.
