### ISSUE TITLE
Lightning Talks/June 20 Recap Blog Post

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#172]
Write up a blog post describing the talks and share links to the slides.

- Get slides
  - [x] Diego
  - [x] Paul
  - [x] Amalie
  - [x] Nik
  - [x] Victoria

**Comment by VictoriaODell** [comment]
Mine: https://docs.google.com/presentation/d/1F0jLB3vJsLLRAXzVwLVB0cr0PGwm_2h33GQquZHzkR0/edit?usp=sharing

**Comment by luqmaan** [comment]
Nik's: [commutely-austin-open.pdf](https://github.com/open-austin/iced-coffee/files/324749/commutely-austin-open.pdf)

**Comment by mateoclarke** [comment]
[PANDA Lightnin'.pdf](https://github.com/open-austin/iced-coffee/files/324766/PANDA.Lightnin.pdf)

**Comment by mateoclarke** [comment]
http://dhernandex.github.io/sass-color-functions/presentation/#/

**Comment by mateoclarke** [comment]
http://www.open-austin.org/blog/2016/06/23/lightning-talk-recap
