### ISSUE TITLE
Publicize Candidate Questionnaires

### ISSUE THREAD

**Issue by mscarey** [open-austin/iced-coffee#179]
Questionnaires for city council candidates about open data issues. The [form for last year](http://www.open-austin.org/candidate-questionnaires/documents/2014_OpenAustin_CandidateQuestionnaire.pdf) will need to be updated to remove requests for things the city is already providing, and add new policy priorities.

**Comment by mateoclarke** [comment]
https://docs.google.com/document/d/1_vRsdtyyb3d5gcHZn8OoS3b61OCbfGnpYJmY6Dl6V6s/edit

**Comment by mscarey** [comment]
I emailed out the survey forms.

**Comment by mscarey** [comment]
So far only Leslie Pool has responded (and only Zimmerman has declined).

**Comment by mscarey** [comment]
Here's the email contact list for all the candidates who haven't responded or declined. The austintexas.gov addresses aren't ideal to use because it might violate campaign rules to use them for campaigning. Let's not overwhelm them with emails, but we could send a reminder before the deadline. It might be better for the email to come from an open-austin email address.

district2@austintexas.gov
tx_boxer1@yahoo.com
wesley@austin4everyone.com
info@camachoassociates.com
andre@casarforcouncil.com
lchiii@stic.net
jimmy@jimmyflannigan.com
info@natalieforaustin.com
District10@austintexas.gov
info@alisonalter.com

**Comment by mscarey** [comment]
Mateo and Sean D created a page for the survey results on open-austin.org. https://www.open-austin.org/candidate-questionnaires/2016.html

We're going to present about the project at the 10-17 library meetup. About all that's left to do is to publicize the published results leading up to the election.
