### ISSUE TITLE
July 18th Meeting Blog post

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#180]
I took notes last night I just need to get them all tidied up.

Things I need 
- [x] Contact email for Mozilla
- [x] Link to budgeting game night event. 

I felt like the notes got kinda skimpy on Braden's part. 
Was there any call to action he had that I can make note of? 

@mateoclarke do you have any of the above?

**Comment by mateoclarke** [comment]
Contact for Mozilla: 
Robert Friedman
robert@mozillafoundation.org

Links to Budget Game Night:
https://www.eventbrite.com/e/budget-game-night-tickets-26423729085?aff=eac2
https://www.facebook.com/events/309340609405662/

Can't recall any specific call to action from Braden.

**Comment by VictoriaODell** [comment]
https://github.com/open-austin/open-austin.github.io/pull/112
