### ISSUE TITLE
Recognize our sponsors better

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#181]
- [ ] List sponsors on our website
- [x] List sponsors on Meetup.com

**Comment by luqmaan** [comment]
I started adding some sponsors to our Meetup page.

![image](https://cloud.githubusercontent.com/assets/1275831/16959186/6bdba94e-4da9-11e6-8fa1-67738170f1ab.png)

**Comment by mateoclarke** [comment]
i added Blue Treble

**Comment by werdnanoslen** [comment]
Added a link to this in our support page https://github.com/open-austin/open-austin.github.io/commit/3706383816a5b2c1b007be72ee3c828a9396d39a

Will add IBM and Galvanize to the sponsors list, too, since they have hosted us. That counts as sponsorship, right?

**Comment by werdnanoslen** [comment]
added ibm, conde nast, and galvanize to sponsors list
