### ISSUE TITLE
Write Hosting Instructions

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#182]
Write AWS usage Instructions and add them to open-austin/iced-coffee.

**Comment by luqmaan** [comment]
Started something here. https://github.com/open-austin/iced-coffee/compare/master...hosting-instructions?quick_pull=1

I think we can be less detailed about how to use AWS and also cover a few other alternatives.

**Comment by luqmaan** [comment]
This would be good to add https://github.com/open-austin/project-ideas/issues/73#issuecomment-233971154

**Comment by werdnanoslen** [comment]
updated [hosting.md](https://github.com/open-austin/iced-coffee/blob/master/hosting.md) and added to wiki
