### ISSUE TITLE
Setup HTTPS for open-austin.org

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#186]
Not having HTTPS setup for open-austin.org is harming us.

None of the webapps that live under the open-austin.org domain can display user locations.

For example, I get this error when visiting http://www.open-austin.org/austingreenmap/.

> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> 
> main.js:52811 Warning: Don't set .props.url of the React component. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props.

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by chip-rosenthal** [comment]
Any particular requirements or requests?

We can setup a https proxy on the Open Austin server that forwards to the Github site.

I'd also need to setup "Let's Encrypt" for the SSL cert. The previous StartSSL cert has probably expired, and I'm not using them anymore.

**Comment by gusIreland** [comment]
Hey Chip

Based on the projects we've seen, these are the requirements:

- Easy to setup/update. We have lots of projects now, with a few new ones start every every month.
- HTTPS
- Querystrings
- Subdomains
- Fast
  - CDN
  - Compression
  - Caching headers

I'm a little worried about losing query strings, as that would break several live projects.

It'd also be nice to manage subdomains without relying on you.

Based on these requirements, I think Cloudflare might be the better solution here.

**Comment by luqmaan** [comment]
I ran into another problem today with hack-the-budget and routing. Hosting hack-the-budget at `hack-the-budget.open-austin.org` instead of at `open-austin.org/hack-the-budget`, would solve the routing problem.

@chip-rosenthal Can you move the open-austin.org DNS to Cloudflare?

Our Cloudflare account credentials are in LastPass.

I've started the process of setting up Cloudflare already.

@chip-rosenthal Do these DNS records look correct to you?

![image](https://cloud.githubusercontent.com/assets/1275831/17593820/cd0cb9fa-5fac-11e6-8104-fdc7ac4f5ae2.png)

@chip-rosenthal Can you change the nameservers to:

```
alexis.ns.cloudflare.com
cloe.ns.cloudflare.com
```

![image](https://cloud.githubusercontent.com/assets/1275831/17593874/f754623a-5fac-11e6-81e7-fbff994403ca.png)

**Comment by chip-rosenthal** [comment]
* You'll need to update the nameservers in the domain registration to point to Cloudflare. Just let me know once you are done so I can decommission the current nameservers.

* Drop the mail.open-austin.org entry. That's a vestige of the mailserver migration some time back.

* You can drop the test.open-austin.org entry too.

* The MX entry is not correct if you want me to continue using the email forwarding on soaustin.net. The should point to mail.soaustin.net.

```
$ host -tmx open-austin.org.
open-austin.org mail is handled by 10 mail.soaustin.net.
```

* What do you want to do with the legacy openaustin.org and openaustin.com domains?

```
http://www.openaustin.org
http://www.openaustin.com
```

**Comment by luqmaan** [comment]
![image](https://cloud.githubusercontent.com/assets/1275831/17595665/8038e426-5fb3-11e6-83d2-af23e65c9ea3.png)

- [x] Updated the nameservers in Namecheap
- [x] Dropped mail.open-austin.org
- [x] Dropped test.open-austin.org
- [x] Updated mx to `10 mail.soaustin.net`

> What do you want to do with the legacy openaustin.org and openaustin.com domains?

Redirect them to open-austin.org. I'm not sure what the best way to do that is though. I don't see them listed in the Namecheap account.

**Comment by chip-rosenthal** [comment]
The open-austin.org MX record doesn't look right. It's not providing a response.

```
$ dig @CLOE.NS.CLOUDFLARE.COM open-austin.org. mx

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @CLOE.NS.CLOUDFLARE.COM open-austin.org. mx
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46312
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 5
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;open-austin.org.               IN      MX

;; AUTHORITY SECTION:
open-austin.org.        3600    IN      SOA     alexis.ns.cloudflare.com. dns.cloudflare.com. 2022259829 10000 2400 604800 3600

;; ADDITIONAL SECTION:
alexis.ns.cloudflare.com. 86400 IN      A       173.245.59.60
alexis.ns.cloudflare.com. 86400 IN      AAAA    2400:cb00:2049:1::adf5:3b3c
cloe.ns.cloudflare.com. 86400   IN      AAAA    2400:cb00:2049:1::adf5:3a56
cloe.ns.cloudflare.com. 86400   IN      A       173.245.58.86

;; Query time: 7 msec
;; SERVER: 173.245.58.86#53(173.245.58.86)
;; WHEN: Thu Aug 11 11:12:34 CDT 2016
;; MSG SIZE  rcvd: 201
```

The legacy domains (openaustin.org and openaustin.com) are owned by whurley, the original founder of Open Austin. In the past, he's wanted to maintain ownership, but he's been willing to point the nameservers to whatever we wanted. (The Midas Networks nameservers in this case.)

It might be hard to get them pointed elsewhere (he's hard to reach sometimes). My recommendation would be to keep the zones setup on server.open-austin.org, and them up to point to the HTTP redirector on server.open-austin.org, the way http://open-austin.org/ works right now.

**Comment by luqmaan** [comment]
Fixed it

![image](https://cloud.githubusercontent.com/assets/1275831/17596637/fc4589a8-5fb7-11e6-9678-5a80172503d6.png)

**Comment by chip-rosenthal** [comment]
Mail forwarding looks good.

At your convenience, could you setup an entry:

`redirector IN CNAME server
`

I'll use that to handle redirection from the legacy domains.

**Comment by chip-rosenthal** [comment]
Sorry, didn't mean to close :p

**Comment by luqmaan** [comment]
Sorry, I don't know what `redirector in CNAME server` means.

Do you want me to change this record:

![image](https://cloud.githubusercontent.com/assets/1275831/17606509/83df33e6-5fe5-11e6-98bb-235b34440518.png)

To this:

![image](https://cloud.githubusercontent.com/assets/1275831/17606529/94a46b88-5fe5-11e6-9fe8-819dcaa93b32.png)

**Comment by luqmaan** [comment]
I changed it to that:

![image](https://cloud.githubusercontent.com/assets/1275831/17606586/d8d7a018-5fe5-11e6-9c7c-de2ccba46bbf.png)

**Comment by luqmaan** [comment]
🎆  I set up a subdomain for https://github.com/open-austin/austingreenmap. 🎆 

http://greenmap.open-austin.org/

To do that:

- [x] Add CNAME file with `greenmap.open-austin.org` https://github.com/open-austin/austingreenmap/blob/gh-pages/CNAME
- [x] Add DNS record: `CNAME greenmap open-austin.github.io` ![image](https://cloud.githubusercontent.com/assets/1275831/17608958/01cedb8e-5ff6-11e6-995f-4aef771a5024.png)

**Comment by luqmaan** [comment]
@chip-rosenthal Email isn't working.

![image](https://cloud.githubusercontent.com/assets/1275831/17609273/efa0a11a-5ff8-11e6-9ae5-311e99143eb7.png)

**Comment by luqmaan** [comment]
HTTPS and user locations are working:

![image](https://cloud.githubusercontent.com/assets/1275831/17609362/f0b512d8-5ff9-11e6-9e12-40971c36c2b8.png)

Visiting `http://*open-austin.org/*` automatically redirects to `https://*open-austin.org/*`. https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-

![image](https://cloud.githubusercontent.com/assets/1275831/17609366/fb06e2fc-5ff9-11e6-895e-0ddc6e461f77.png)

**Comment by chip-rosenthal** [comment]
1. Are you still having email problems? I just sent a test message to tech@open-austin.org and it was delivered.

2. Regarding the DNS change for "redirector", I was asking that you setup an entry for "redirector.open-austin.org" that is a CNAME pointing to "server.open-austin.org".

3. I recommend NOT using a CNAME on server.open-austin.org, and instead use an A. The CNAME technically is not correct here ... the parent domain may have other content associated with it that does not go with the host.

**Comment by luqmaan** [comment]
Yes, I'm still having email problems. The emails are delivering. But I'm not actually getting them. I've tried these things out:

- My email to info@open-austin.org
- My work email to hack@open-austin.org
- @wilsaj email to hack@open-austin.org

Does this look correct to you?

- `CNAME redirector server.open-austin.org`
- `A server.open-austin.org 208.81.246.81`

![image](https://cloud.githubusercontent.com/assets/1275831/17630513/40796d7e-6085-11e6-9349-ccc3469f5c5f.png)

Thank you for helping me with this stuff.

**Comment by chip-rosenthal** [comment]
Oh, I see the problem!

The MX target for open-austin.org should be "mail.soaustin.net", not "soaustin.net".

The reason my test worked is that (duh!) the message went through the soaustin.net mail server without ever consulting DNS.

**Comment by luqmaan** [comment]
Awesome, email is working now.

Thank you!

![image](https://cloud.githubusercontent.com/assets/1275831/17631131/6bd07258-6088-11e6-8658-cd7a2acdd527.png)

**Comment by chip-rosenthal** [comment]
The following websites are running on server.open-austin.org but no longer configured in the DNS:

* austin-recycles.open-austin.org
* bike-buddy.open-austin.org
* tec-filer.open-austin.org
* old.open-austin.org
* test.open-austin.org

Unless you want any of those running, I'll take them down. (I won't be deleting any code or data, just removing them from HTTP.)

That will leave the following running on that host:

* 000-default (catchall that redirects anything it gets to www.open-austin.org)
* data.open-austin.org

**Comment by luqmaan** [comment]
I'm not opposed to taking them down. I'm not aware of anybody using or maintaining those services in the last year.

**Comment by mateoclarke** [comment]
@chip-rosenthal, In a previous comment, you mentioned that data.open-austin.org would remain running on the host. 

Is it still accessible? @amaliebarras was working on something and wanted to reference that subdomain.

Thanks!
Mateo

**Comment by chip-rosenthal** [comment]
Have @luqmaan to modify DNS to add a CNAME to point data.open-austin.org to server.open-austin.org.

**Comment by luqmaan** [comment]
Done, thank you.
