### ISSUE TITLE
Pet Alerts Domain

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#188]
> I wanted to get in touch to see if you wanted me to transfer the pet- alerts.com domain over to you or the organization - I'm moving off of my domain host soon, and I wasn't planning to renew it. The site looks like it is nearly a year out of date at this point 
> @tshelburne 
- [ ] Let the pet-alerts.com domain expire
- [ ] Setup pet-alerts.open-austin.org

**Comment by werdnanoslen** [comment]
Just wanna bump this to see if anyone else knows what we should do...

**Comment by tshelburne** [comment]
Can confirm that I no longer have this domain.

**Comment by werdnanoslen** [comment]
Yeah, whois shows it's owned by a French dude who runs a job talent site and owns a bunch of domains. Gonna call this closed
