### ISSUE TITLE
Facebook Strategy 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#190]
We need to work on being more engaged on Facebook 
Things we can do 
- [ ] Schedule regular meetings as events/ or maybe just larger events
- [ ] figure out a posting schedule
- [ ] Create a hashtag list

Jay is interested with is.

**Comment by werdnanoslen** [comment]
Are we using Facebook at all?

**Comment by VictoriaODell** [comment]
@werdnanoslen yes. Not as much as twitter though. Right now some of our buffer posts are set to post to twitter/facebook at the same time.

**Comment by VictoriaODell** [comment]
I'm closing this for now. Our current strategy is to post what is being posted on Twitter via buffer. If we identify needing a more thorough strategy we can reopen or make a new issue.
