### ISSUE TITLE
September Meetup Blog Post

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#191]
Started a draft. @amaliebarras and @mateoclarke ya'll have notes too right? 

https://docs.google.com/document/d/182kmNH4viBOO7lPM3zFqaM6jZ-FutSrOGO_w2p5PRI4/edit

**Comment by amaliebarras** [comment]
This looks good, my notes just go into more detail on the registry, which I don't really think is necessary

**Comment by mateoclarke** [comment]
just gibberish...

---

## Community Registry

Having voice heard
Task force on community engagement
Who are the leaders we need to talk to in an area. 
Well beyond its use
Cold fusion
Self service directory 
Orgs could use to connect to one anyone
Delveoplment notifiayions
Pull all the folks interested in water
Democratize access to notifications 
Email back and forth all the boundaries and Gis
It matches the map with the form data 
PDF of map

## data.world

- challenge everyone to upload a dataset
- public benefit corporation
- when you think about data analysis tools, they are are 1, first mile, 2, mile, 3rd mile of data work
    - 1. finding data, hosting data, preparing data for analysis, helping ppl find it
    - 2. analysis - R, Python
    - 3. visualization and presentation, Tableau, SAS
- collaboration and nto duplicate efforts
- Linked data
    - csv is tabular, translated into format of RDF
    - linked data is what enables joining data to things like the census and other data online
    - “Open data wants to be linked to data”
- There are more open data sets online than there were website available when Google was first founded
- Too much of data’s growth is happening in silos, no duh.
- hard to take the knowledge within a “labeled” box
- hard to decide if its something you want to use
- the benefit that can come from people using open data
- the benefit when data is machine readable and AI can use it, for good?
- what do you think about futurology
- Semantic web, Resource Description Framework, Linked Data
- applying the same architectureof the world wide web to basic research
- atomic fact
    - each data point becomes a triple (subject, predicate, object (Turkey, “is a”, Country,
    - “AAA” Principle
    - anyone can say anything about any topic
- hope to increase the value of data by linking it together in RDF linked paradise
- Linke
- data ferrett
- census

**Comment by VictoriaODell** [comment]
https://github.com/open-austin/open-austin.github.io/pull/116

Need to link some stuff. I think it's in a good spot for some eyes though 👓

**Comment by VictoriaODell** [comment]
I thought I published this but don't see it. 
If someone can see what I did wrong that would be great.
