### ISSUE TITLE
October Lightning Talks Meetup

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#192]
When: October 17th, 2016
What: We're hosting a lightning talk meetup with a focus on the elections/voting

Last time we had 5 presentations that lasted 10 minutes each and we had our announcements. 

Confirmed speakers:
- [x] City Council Candidate Surveys - Matt Carey & Mateo Clarke, Open Austin 
- [x] Voting Wait Times & Polling Locations - Tommy Miller, Travis County, GIS Coordinator 
- [x] "The Problem with Lazy, Apathetic Non-Voters" - Shellee O'Brien
- [x] Voting within Latino Communities - Ideation League
- [ ] Slot 5: TBD
- [ ] Extra Slot

Here are some possible people to invite to speak: 
- [x] Andrew Vickers/ VoteATX
- [x] Shellee OBrien/ Tx Turnout
- [ ] Audrey McGlinchy/ Austin Monitor & council races

Need more suggestions and to reach out to these people. :eyes:

**Comment by mateoclarke** [comment]
More ideas:

- [ ] Gretchen Nagy from Travis County to demo/publicize their [line length reporting system/map](http://kut.org/post/travis-countys-new-online-initiative-could-be-your-road-map-shorter-voting-lines)
- [ ] Someone from [TechVotes](http://austininno.streetwise.co/2016/09/21/techvotes-launches-to-increase-austin-tech-voter-participation/)
- [ ] Taylor Foody (or someone else) from Annette Strauss Institute to talk about the "Civic Life in the Cyber Age"
- [x] Matt Carey and/or me to talk about Candidate Survey responses

**Comment by mateoclarke** [comment]
I reached out to Andrew, Shellee, and Mrs. Nagy tonight. Taylor for ASI is next on my list.

@mscarey and I can share a slot to talk about candidate surveys.

We should shoot for 5-6 talks. Any other ideas on who to reach out to?

**Comment by mateoclarke** [comment]
Ideation League is a go.
Reached out to Nic Moe to see if he could talk or recommend someone else to talk about Prop 1/Mobility Bond.

**Comment by VictoriaODell** [comment]
I need to wrap this up with a blog post a la [June](https://www.open-austin.org/blog/2016/06/23/lightning-talk-recap): 


Here are our slides: 
https://docs.google.com/presentation/d/1BtsWRMQ5Pf6ZyIxM16ynrgxNHjAoPipS_gPp5D3Enj0/edit#slide=id.g105efe3300_0_41

Shelle's slides: 
https://docs.google.com/presentation/d/1bewoqrAtTIiToKOZlyGsjCSAc8pIGhM-hwVrsc4J-KE/edit#slide=id.p

Tommy had no slides but the map:
http://tcto.maps.arcgis.com/apps/Minimalist/index.html?appid=c181a61d343b4645aa7c1c3cd445aff6

Matt's slides
[city_council_2016_survey (1).pdf](https://github.com/open-austin/iced-coffee/files/540541/city_council_2016_survey.1.pdf)

Ideation league: 
http://www.slideshare.net/DarioFidanza/affecting-civic-space-with-ux-design

Fomo slides: tbd

**Comment by mateoclarke** [comment]
I went ahead and made the post:
https://www.open-austin.org/blog/2016/10/19/october-meetup-recap
