### ISSUE TITLE
Cute Pets Austin PR Push

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#195]
[Cute Pets Austin ](https://twitter.com/CutePetsAustin?lang=en)has been running for about a month now since being down for roughly 4 months. It would be great if we could promote it more. 

I plan on doing the following: 
- [ ] Creating a press release 
- [ ] Create list of news contacts to push the press release to 
- [ ]  Schedule tweets supporting the twitter bot
- [ ] I have another blog post in the works [that will feature the bot](https://github.com/open-austin/iced-coffee/issues/194)

@scascketta You got the app up and running again. Will you be at the upcoming hack night to talk more about the project?

**Comment by werdnanoslen** [comment]
@VictoriaODell  Is this done, or can it be moved to the Cute Pets Austin repo / project idea issue?

**Comment by VictoriaODell** [comment]
Closing here
