### ISSUE TITLE
Austin Design Week Workshop

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#197]
# [Event posting](http://designweekaustin.com/schedule/designing-for-civic-solutions)

Here is where I'm gathering/ organzing everything that needs to be done prior to the Austin Design Week Workshop. Feel free to contribute ideas, express concerns, and share. 
- [x] Join Call This friday or Next to learn more about event logistics
- [x] Post on Meetup [[link to meetup page](https://www.meetup.com/Open-Austin/events/234979901/)]
- [x] Submit supplies request by 10/31 
- [x] Tweets- A week and half prior promotion at the least from the Open Austin Twitter
- [x]  Workshop slides [[link to google slides-Work in Progress Slides](https://docs.google.com/presentation/d/1mZyNrdGNbW6mr3X_x9rlvBeVvUIKucYgg79w6Wl-MiU/edit?usp=drive_web)]
- [x] Write Agenda [ [Work in progress google drive file](https://docs.google.com/document/d/1ss6c-QwFzziVgWjLR5Ok2zI6p-msnb9Do2rY7bW3ddM/edit)] 
- [x] FB Post- personal
- [x] FB Post- Open Austin 
- [ ] Small printable agenda- 4 up. Design/ Review/  print

**Comment by VictoriaODell** [comment]
# Info from my phone call this past Monday: 
Phonecall Notes
Danielle- Austin Design Week 

Lunch time workshops are 1.5 hours(90 minutes) s but actual time for the workshop will be closer to 80 minutes after housekeeping.  

The goal is to provided people with great takeaways and allow them to get hands on with something. 

Best practices/ things to keep in mind

Clear takeaways
Clear Agenda
Mini Activities
Ice Breakers
Keep to the time
cap for workshop is at 30 people
best to have people work in small groups
Coordinate to the groups diversity
week before + week off there will be reminders
Have an example of what we are doing for the interactive part and walk through the process with the group
The space will have the following: 

Projector
whiteboard
whiteboard tables
Papers/pens
If we need more supplies then we should tell them no later than a week before. We should also try to arrive a half an hour early to setup and make sure that our equipment works.

**Comment by VictoriaODell** [comment]
@amaliebarras I have more info here. Is this something you think you could help facilitate or would like to help plan? I think you have some valuable insights and background when it comes to data~

**Comment by VictoriaODell** [comment]
Email update from the 21st

`Hello! 

We're so excited to have you leading a workshop for the inaugural Austin Design Week. Thank you to those of you who hopped on the phone with us this week and last to go over some details. 

We wanted to provide some resources as you dive into the planning of your workshop. If you’d like feedback on your workshop, please send any outlines, slides, materials, etc. to us by Monday, 10/31. You should also confirm any supply requests at this time, if you haven't already.

Below are some things to keep in mind as you put together your workshop. We know all of the workshops are very different formats, so not all of these tips will apply to everyone. Pick and choose to incorporate what is applicable to your specific event: 

Please plan to arrive at your workshop venue 30 minutes before your workshop begins. Mark your calendar now for the arrival time.
The workshop time is scheduled to be 1.5 hours long. We will allow a few minutes for everyone to check in, and then will have a 5 minute introduction to ADW. Please note you should be planning your workshop for an 80 minute time frame, which includes any time for Q&A. Please keep track of your time - it flies quickly! Plan to adjust as you go if you are behind on time, or moving along quickly
It’s great, even if you are doing a talk, to keep it interactive. It can feel hard to do this in a short class but there's easy ways to add this in - do a show of hands, or have students think of or write down the answer to a question. (For the workshops being hosted at General Assembly, the tables are whiteboard!)
Get to know your class before you start teaching - we always recommend trying to get a sense of who is there "how many of you work in x" "how many of you have done y before". It'll give you a better sense of your audience, as you won't have time for intros with everyone.
Tell them about yourself! What's your background, why is this important to you?
Include an agenda and learning objectives "By the end of this session, you'll be able to...". Revisit them throughout the class
Add in examples from your personal experience
Demos are welcome! Keep in mind, students won't have laptops so may not be able to do the example with you
Wrap up the session, revisiting what was covered

Please feel free to reach out during the planning process for any help, questions, feedback, etc. We'll be sending registration updates for your workshop and a volunteer confirmation the week before, and day of your event. 

And remember to help us spread the word about this inaugural Austin Design Week and your workshop! Tag @atxdesignweek on Twitter; @austindesignweek on facebook and instagram. #AustinDesignWeek16

Happy planning!
- the ADW organizing team`

**Comment by amaliebarras** [comment]
Hey! Totally, I would love to. Are you free Sunday to have a brainstorm / planning session for it?

**Comment by VictoriaODell** [comment]
Today @amaliebarras and @cthibaultatx caught up and updated the slides
https://docs.google.com/presentation/d/1mZyNrdGNbW6mr3X_x9rlvBeVvUIKucYgg79w6Wl-MiU/edit#slide=id.g1877427235_1_0

Still making some final tweaks on that and the Agenda
https://docs.google.com/document/d/1Pd3saQFKUCEpQAeo8uao05R7Q8535tHjaMPck3V7O9Q/edit#

We're having a final google hangout tomorrow at a tbd time and should be good to go..

**Comment by VictoriaODell** [comment]
We did it!

Have to do the following tonight: 
- [ ] clean up slides
- [ ] create survey
- [ ] Email follow-up with Danielle

**Comment by mateoclarke** [comment]
_closing this out_
