### ISSUE TITLE
Decide whether to join Electronic Frontier Alliance

### ISSUE THREAD

**Issue by mscarey** [open-austin/iced-coffee#199]
EFF reps contacted us about this affiliate program. We were the first Code for America brigade they've talked to about it. Here's the pitch from their email:

Would it be useful to:

*connect with other groups like yours in other cities?

*collaborate with other groups unlike yours that work in your area?

*have access to free documentary films that you could screen for
audiences to prompt discussion?

*receive policy guidance, campaign materials, and other information
resources?

*share your successes, lessons learned, and guidance with others to help
inform their work?

They require that members of the EFA espouse five principles (as explained on their site): expression, security, privacy, creativity, and access to knowledge.

https://www.eff.org/electronic-frontier-alliance

**Comment by mateoclarke** [comment]
What's the difference between EFF's Alliance program and a local EFF meetup group like EFF-Austin? http://effaustin.org/

**Comment by mscarey** [comment]
I think for a long time the EFF and EFF-Austin claimed to be unaffiliated. But now EFF-Austin is a part of the EFA (which means Austinites already have an EFA meetup they can go to if they want).

**Comment by mateoclarke** [comment]
Yeah, I've been wanting to do more things with the EFF-Austin crowd. I think we can reach out to them to do a special EFA style event. Closing to close this and with the answer of no, at least not right now.
