### ISSUE TITLE
11/13 Logo/Brand Redesign

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#2]
## Open Austin needs a new logo design/brand design ##

Our current logo is dated and needs a refresh! With increased awareness of Open Austin, established alignment with Code for America, and our website redesign, we felt it was great timing to work on our image. Open Austin will still keep doing the same work we have been doing and stay comitted to open-source, open data, and open government in Austin, Texas. 

### Our current logos and colors: ###
![copy-open_austin_banner_400x80](https://cloud.githubusercontent.com/assets/10767430/10779907/211ab974-7d05-11e5-9b54-5c4137a856bd.png)
There are no other brand documents that I am aware of. 

### Moving forward we need: ###
* a logo that is scalable and available for b&w printing(no grey or midtones and full color
* A new color palette for use on the web and in print
* new typography for use in marketing material for both print and web

We have a pinterest that is currently acting as a mood board for logo and design inspiration. View it [HERE](https://www.pinterest.com/amaliebarras/open-austin-site/). If you would like to be added please ping @amaliebarras or @Victoriaodell. 

Getting to a good where we fell we can go to production for shirts by **11/13** is desired but not a hard deadline. 

"For those interested in working on logo / tshirt:  https://style.codeforamerica.org/ We aren’t bound to any rules, but just some inspiration ~"

A great presentation on logo design http://www.crestwoodschools.org/userfiles/805/Logo-presentation-1.pdf

**Comment by VictoriaODell** [comment]
I updated the original comment and outlined what we will need in the case that anyone else will want to contribute or has ideas for this project.

**Comment by mateoclarke** [comment]
[Here is a repo](https://github.com/open-austin/open-austin-logo) with more versions of the existing logo.

**Comment by amaliebarras** [comment]
![](https://files.slack.com/files-pri/T036FLMDN-F0DHYH7NV/screen_shot_2015-10-30_at_7.02.02_pm.png)

![](https://files.slack.com/files-pri/T036FLMDN-F0DHYPSQZ/screen_shot_2015-10-30_at_7.07.35_pm.png)

**Comment by VictoriaODell** [comment]
![openaustin_logo_exploration_v1](https://cloud.githubusercontent.com/assets/10767430/10870837/b9ca51fa-809a-11e5-96bc-fe5bb9a6b81e.png)

This was one of my first thoughts.

**Comment by luqmaan** [comment]
Why a star?

**Comment by luqmaan** [comment]
Lets explore the pentagram theme a bit more. How is this? :trollface: 

![image](https://cloud.githubusercontent.com/assets/1275831/10870906/3bca20ac-809d-11e5-9381-6994cbe0f371.png)

**Comment by VictoriaODell** [comment]
You're such a troll. 
A star because Texas? Our capital has a woman at the top of it holding a star. It's an obvious symbol.  
:star: :star2: :hankey:

**Comment by VictoriaODell** [comment]
An interation of the previous image. Colors are changable of course~
![openaustin_logo_exploration_v2](https://cloud.githubusercontent.com/assets/10767430/10871021/531c694c-80a0-11e5-9be0-6e2af073af1d.png)

**Comment by luqmaan** [comment]
> A star because Texas?

:+1: Ah okay. Now I get it.

**Comment by VictoriaODell** [comment]
![openaustin_logo_exploration_v3](https://cloud.githubusercontent.com/assets/10767430/10871376/d31ebbfe-80aa-11e5-868c-dcb4f27b108b.png)

More Variations on the Star thing.

**Comment by VictoriaODell** [comment]
:thought_balloon:  :thought_balloon:  :thought_balloon:  Just thoughts. 

I like the idea of having a symbol that can scale. Right now we have a word mark type thing and it wouldn't work too well as a favicon or on small scale. Unless we do a shorthand type thing and make it "<OA/>" but then i think it loses it's meaning some. 

I thought a badge type logo would be cool but then scaling becomes an issue again.

**Comment by VictoriaODell** [comment]
Also best to find fonts for the logo with https://www.google.com/fonts
This we can ensure that the type we use is web safe. It's better to have the same or simliar type for the brand extensions that we use on the logo. 

I've been using Open Sans but I'm liking more geometric "O"s.

**Comment by VictoriaODell** [comment]
This is just a brain dump. 
![openaustin_logo_exploration_v4](https://cloud.githubusercontent.com/assets/10767430/10872513/1ce15ac6-80c9-11e5-9cea-5b82ec3483f7.png)

I want to do some more exploration this week. Also, I prefer "Open Austin" to "Open ATX" because I think having both can cause confusion.

**Comment by luqmaan** [comment]
:+1:

**Comment by mateoclarke** [comment]
The star reminds me of this redesign concept for the City of Austin flag: 
https://medium.com/@michaelkriegshauser/texans-love-their-flags-b5a2b1b9c524#.9dcef1a6y

<img width="232" alt="screen shot 2015-11-01 at 10 21 30 pm" src="https://cloud.githubusercontent.com/assets/5697474/10874265/107a56d4-80e7-11e5-94f1-11741adbb9ae.png">

**Comment by mateoclarke** [comment]
I like the Lamp of Knowledge as a symbol. May be too radical of a departure but it symbolizes the quest for wisdom. And (sun)light is a common symbol in transparency and open gov. Just a thought to play with.

<img width="119" alt="screen shot 2015-11-01 at 10 33 05 pm" src="https://cloud.githubusercontent.com/assets/5697474/10874389/10ee4a10-80e9-11e5-9e1f-3eaca14f3019.png">

**Comment by amaliebarras** [comment]
O hi thread

^ I like the sunlight direction a lot.

I actually kind of like the 8-bit typeface, it's playful but hard to read. I also *really* like the OA with no line in the A, it's modern but professional and recognizable... If I see "OA" I know what's goin on

![sideways idea]
(https://cdn3.iconfinder.com/data/icons/arrows/16/arrow__chevron-small-circle-4-01-512.png)

I'm not also crazy about the star though. one, because star reminds me more of Texas than Austin, and two, because it feels like it covers the "Austin" part but not the "Open" part. 

Maybe that's fine! What are we trying to say w/ the logo? 

One idea I had for the logo was to represent the policy / hack ecosystem as supporting and fueling each other. Like the icon for recycling has the arrows in a triangle? I tried sketching but it didn't work out, dunno if I have the chops.

**Comment by mateoclarke** [comment]
Yeah, thinking out loud... :speech_balloon: 

I think the star is a nice simple symbol. But it is pretty ubiquitous and as a stand alone symbol, I'm not the biggest fan. I like the spirit of splicing the inside angles to make it "open", but that does give the pentagram effect that Luq pointed out. So the question around the star, is how to make a very common symbol for all things Texas more specific to us. _I like bats more than stars as an Austin-y symbol_

I'm not a big fan of the 8-bit typeface as a main logo. I think it can be fun for one-off use (like for an event), but I'd get sick off looking at it all the time.

I like a lot of the stuff you (@victoriaodell) pinned. I especially can see an unique symbol for openness and connections coming from this droplet being morphed into an 'O'.

![](https://s-media-cache-ak0.pinimg.com/736x/4c/2f/ca/4c2fca70a6c3e8e82bc180ea6a92def1.jpg)

**Comment by mateoclarke** [comment]
If the droplet become an O in open. I can then see a bat becoming an A in Austin. Random thought...

**Comment by VictoriaODell** [comment]
I too like the bat~ Def want to experiment more. All this feedback is greatt. Keep it up~

**Comment by VictoriaODell** [comment]
Really quick mock of potential bat. Obs need to be refined 

![openaustin_logo_exploration_v5](https://cloud.githubusercontent.com/assets/10767430/10928186/f026aea6-826b-11e5-8206-2953b88bb6b3.png)

**Comment by VictoriaODell** [comment]
Bear with me on these quick iterations. I'm throwing stuff at a wall and seeing what will stick. 
![openaustin_logo_exploration_v6](https://cloud.githubusercontent.com/assets/10767430/10986778/9c87fa6a-83f2-11e5-803c-1edd02ececdd.png)

**Comment by mateoclarke** [comment]
I dig that! At first, I thought the brackets, curly braces, parens, etc was too much. But in this version, you can barely notice and it stand alone clearly as a bat. :+1:

**Comment by VictoriaODell** [comment]
Still brainstorming some more. I'd like to see if I can fit an "A" or "O" in there somewhere. I got distracted when I was working on the homepage cause this issue for branding is :fire: .

**Comment by amaliebarras** [comment]
Just messing around, appropriating vicky's curly braces idea with the comment about having the O and A! what about diz guy?

<img width="316" alt="screen shot 2015-11-06 at 9 50 08 am" src="https://cloud.githubusercontent.com/assets/11826646/11001256/f3f66010-846b-11e5-80ff-7d25f3e8ab15.png">

**Comment by amaliebarras** [comment]
<img width="490" alt="screen shot 2015-11-06 at 10 16 47 am" src="https://cloud.githubusercontent.com/assets/11826646/11001914/889571ea-846f-11e5-89bd-dfc8a2e53b30.png">

Round two with less awful colors

**Comment by mateoclarke** [comment]
![screen shot 2015-11-13 at 2 54 40 pm](https://cloud.githubusercontent.com/assets/5697474/11157356/88a8070e-8a16-11e5-8809-030f41f9ab0b.png)

An "open" O + Vickie's bat

**Comment by amaliebarras** [comment]
More iterations on this lil guy

<img width="507" alt="screen shot 2015-11-17 at 9 39 40 am" src="https://cloud.githubusercontent.com/assets/11826646/11216116/2b8781ca-8d0f-11e5-9401-99b9e1d25ecf.png">

**Comment by amaliebarras** [comment]
<img width="312" alt="screen shot 2015-11-18 at 6 45 29 pm" src="https://cloud.githubusercontent.com/assets/11826646/11259119/900c8512-8e24-11e5-9e4b-cfa64255d55c.png">

real bat wings instead of the curly braces?

**Comment by VictoriaODell** [comment]
AI PDF files of current exploration pages!

[open_Austin_logo_exploratoin_v5.pdf](https://github.com/open-austin/iced-coffee/files/40929/open_Austin_logo_exploratoin_v5.pdf)
[OpenAustin_logo_exploration_v4.pdf](https://github.com/open-austin/iced-coffee/files/40930/OpenAustin_logo_exploration_v4.pdf)

**Comment by benguhin** [comment]
Here's some variations on the bracketbat:

![open_austin_logo_exploration_v6-03](https://cloud.githubusercontent.com/assets/6953063/11320905/22743698-9078-11e5-9e43-470b06ef1f50.png)
![open_austin_logo_exploration_v6-04](https://cloud.githubusercontent.com/assets/6953063/11320906/27374576-9078-11e5-97b6-e2fe9ef519f7.png)

Ai PDF (creative cloud 2014): [open_Austin_logo_exploratoin_v6.pdf](https://github.com/open-austin/iced-coffee/files/40937/open_Austin_logo_exploratoin_v6.pdf)
EPS: https://drive.google.com/file/d/0B0AB0knkJkx0cFNDZHJNc1pkaHc/view?usp=sharing

**Comment by mateoclarke** [comment]
B!

**Comment by luqmaan** [comment]
B also.

We could use J when we're angry about something.

**Comment by VictoriaODell** [comment]
More contribution from attendee, Tarissa 
[bats.pdf](https://github.com/open-austin/iced-coffee/files/40951/bats.pdf)

**Comment by VictoriaODell** [comment]
<img width="667" alt="screen shot 2015-11-21 at 6 57 56 pm" src="https://cloud.githubusercontent.com/assets/10767430/11321361/ccfc752c-9081-11e5-819f-ed0859344b03.png">
This is a breakaway from bracket bat but thoughts? 
It's based on the "Open Source Initiative" logo. 
I was thinking keyhole or geometric shape of O and A stacked on each other. So like "Unlocking data/gov in ATX" or "unlocking the cities potential".

**Comment by VictoriaODell** [comment]
Moar bats <img width="705" alt="screen shot 2015-11-22 at 1 31 16 pm" src="https://cloud.githubusercontent.com/assets/10767430/11325812/56309b70-911d-11e5-93b5-8d9523f08458.png">

**Comment by VictoriaODell** [comment]
I like the scalabilitly of this one and I think it can be a badge also
<img width="366" alt="screen shot 2015-11-22 at 1 55 01 pm" src="https://cloud.githubusercontent.com/assets/10767430/11325931/b8c5076e-9120-11e5-96ef-1eda6b4f68a4.png">

**Comment by VictoriaODell** [comment]
Could keep exploring this route and try different bat shapes
<img width="663" alt="screen shot 2015-11-22 at 2 07 32 pm" src="https://cloud.githubusercontent.com/assets/10767430/11325994/6893384a-9122-11e5-8c22-341c86e070cf.png">

**Comment by VictoriaODell** [comment]
A quick simplification of an earlier iteration. 
line weight changes/edge clean up can happen after we agree on a concept. 
<img width="465" alt="screen shot 2015-11-22 at 2 16 40 pm" src="https://cloud.githubusercontent.com/assets/10767430/11326035/b23b35d2-9123-11e5-921a-5ca2d5ec62cc.png">

I keep thinking batman though

**Comment by VictoriaODell** [comment]
Iteration on Keyhole bat
<img width="568" alt="screen shot 2015-11-22 at 2 30 10 pm" src="https://cloud.githubusercontent.com/assets/10767430/11326089/919103a0-9125-11e5-8891-bd930e8909e0.png">

**Comment by VictoriaODell** [comment]
Didn't come to any solid resolution. Here is a dump of pieces and shapes I've been playing with. I can upload sketches later. 
[OpenAustin_logo_exploration_v7.pdf](https://github.com/open-austin/iced-coffee/files/41162/OpenAustin_logo_exploration_v7.pdf)

**Comment by mapineda** [comment]
Big fan of this one. I think its sleek. 
![screen shot 2015-11-23 at 2 17 41 pm](https://cloud.githubusercontent.com/assets/8691910/11348601/032cb1e0-91ed-11e5-9b4d-668b2fc2bbb0.png)

**Comment by VictoriaODell** [comment]
@mapineda I wanted the designer to push that one further and started messing with it myself some too. I like the shape but I don't think it loks a little dark.

**Comment by VictoriaODell** [comment]
<img width="153" alt="screen shot 2015-12-01 at 7 16 12 pm" src="https://cloud.githubusercontent.com/assets/10767430/11519464/03cd9136-9860-11e5-9967-8660bc87ae3c.png">

**Comment by VictoriaODell** [comment]
<img width="809" alt="screen shot 2015-12-01 at 9 04 08 pm" src="https://cloud.githubusercontent.com/assets/10767430/11521132/3092c8f8-986f-11e5-95de-c061f0672cce.png">

The line of thinking for the latest iteration. Trying to consolidate what the original logo had going.

**Comment by VictoriaODell** [comment]
<img width="177" alt="screen shot 2015-12-01 at 10 24 38 pm" src="https://cloud.githubusercontent.com/assets/10767430/11522193/581d9fb4-987a-11e5-8368-26d19ed4ceea.png">
<img width="165" alt="screen shot 2015-12-01 at 10 24 43 pm"src="https://cloud.githubusercontent.com/assets/10767430/11522194/581f54b2-987a-11e5-8ce1-b55891367cf1.png">

More iterations

**Comment by mateoclarke** [comment]
I really like the first one you posted with orange and grey.

<img width="133" alt="screen shot 2015-12-02 at 1 01 17 pm" src="https://cloud.githubusercontent.com/assets/5697474/11540906/f832bd84-98f4-11e5-84c5-b7c8838f73a1.png">

I also like the version with the circle and the negative space.

Better direction than the bat. Sorry bracket bat :cry:

**Comment by VictoriaODell** [comment]
:+1: 

I want to have a presentation on Monday about it. Thoughts? 
I'm meeting again with one of my design friends to get some feedback.

**Comment by mateoclarke** [comment]
Yeah, let's plan on that.

Another silly idea, thinking about http://www.responsivelogos.co.uk/:
What happens if you start with "OPEN :star:USTIN" where the logo replaces the "A".
Then you shrink a bit to the star above text, then you shrink to just the star.
_Maybe a dumb idea_

**Comment by VictoriaODell** [comment]
I could see that working better if the ">" was the top point of the star rather than the right point.

**Comment by VictoriaODell** [comment]
:wind_chime:

**Comment by VictoriaODell** [comment]
Presentation from tonight's Meetup:

[OpenAustin_logo_redesign_presentation.pdf](https://github.com/open-austin/iced-coffee/files/54919/OpenAustin_logo_redesign_presentation.pdf)

**Comment by mateoclarke** [comment]
That presentation is 💯! When do I get my tshirt?

**Comment by mateoclarke** [comment]
The last page of the [PDF](https://github.com/open-austin/iced-coffee/files/54919/OpenAustin_logo_redesign_presentation.pdf) made it click for me. Looks awesome!

<img width="1339" alt="screen shot 2015-12-08 at 10 36 53 am" src="https://cloud.githubusercontent.com/assets/5697474/11661475/b410ff06-9d97-11e5-953d-d6c4346c7d89.png">

**Comment by VictoriaODell** [comment]
I was going to do a shirt mockup too but :watch: 
:hushed:  Showing implementation of the design is part of selling it. Presentation is major because design is subjective and contextual ~

**Comment by VictoriaODell** [comment]
I'll be showing some color/weight options and we can finalize and order shirts!

**Comment by VictoriaODell** [comment]
Realistically, the 17/18th is when I can get everything nice and packaged. Tomorrow evening is my work holiday party~

**Comment by VictoriaODell** [comment]
<img width="321" alt="screen shot 2015-12-16 at 8 25 21 pm" src="https://cloud.githubusercontent.com/assets/10767430/11859700/348567fc-a433-11e5-8a5f-3416e7114f96.png">

Now to work on the type

**Comment by VictoriaODell** [comment]
Adjusted the color. I forgot to change it to the one we discussed in the meeting. I lightened it just a smidge more. 
<img width="528" alt="screen shot 2015-12-17 at 12 00 16 am" src="https://cloud.githubusercontent.com/assets/10767430/11862488/4d156060-a451-11e5-9e92-e15bd0b58338.png">

I packaged the images up as svg,pdf, ai, jpg, and png. Also included an all black version and a version with the grid for spacing in the back. 

I'll get that all uploaded tomorrow and work on the images to replace social media profiles, and shirt, button, sticker stuff.

**Comment by VictoriaODell** [comment]
Also, how it can appear on dark colored backgrounds. 
:cat2:

**Comment by VictoriaODell** [comment]
1 color orange preferred. If anyone has any thoughts on that let me know. I tried it with orange/white but didn't feel right. All white an option but not preferred unless an absolute. 
<img width="346" alt="screen shot 2015-12-17 at 12 09 33 am" src="https://cloud.githubusercontent.com/assets/10767430/11862595/802bab20-a452-11e5-967f-560476d3184b.png">
Whoops, little red mark is to be ignored. 

I need to extend the pallete out too.

**Comment by VictoriaODell** [comment]
Okay~ Made some final adjustments to they type and color. New logos are currently in the Google Drive for Open Austin but will be shared on GitHub. 

Currently working on extending the brand colors and making profile photos for social media. Also updating the logo presentation and including some quick brand tips/guidelines.

**Comment by mateoclarke** [comment]
Is there more work to do here @victoriaodell? I think we can close out this issue now that the new versions of the logo is uploaded to Google Drive. I'll go ahead and add them to the logo repo.

**Comment by VictoriaODell** [comment]
I'm currently working on extending the colors and doing some general guidelines stuff. I also want to make the logomark available by itself in the repo also.

**Comment by VictoriaODell** [comment]
I've updated the Google Drive to have files that are of the star symbol only. 
They can be found here: https://drive.google.com/open?id=0BwKb2oghmQldMkpRNmtiVXRzVTA

Available in black. white, and full color.
