### ISSUE TITLE
Schedule Events for 2017

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#200]
_this continues on the thread from #170_ 

Our existing general pattern (with exceptions for holidays) is:
- Civic Hack Saturday on 1st Saturday
- Civic Hack Night on 2nd Wednesday & 4th Tuesdays (subject to change)
- Civic Tech Meetup on 3rd Mondays

### January
- [x] Saturday January 7   - Civic Hack Saturday - **Dev Bootcamp**
- [x] Wednesday January 11  - Civic Hack Night -  **Dev Bootcamp**
- _Mon, January 16 - MLK Holiday_
- [x] Tuesday January 17  - Civic Hack Night - **[Industrious](http://www.industriousoffice.com/locations/austin)**
- [x] Monday January 23   - Open Gov & Civic Tech Meetup - **Terrazas Library**

### February 
- [x] Saturday February 4   - Civic Hack Saturday - **Chicon Collective**
- [x] Wednesday February 8    - Civic Hack Night -  **Chicon Collective**
- _Tues, Feb 14 - Valentine's Day_
- _Mon, Feb 20 - President's Day_
- [x] Tuesday February 21  - Civic Hack Night - **Galvanize**
- [x] Monday February 27   - Open Gov & Civic Tech Meetup - **Terrazas Library**

### March
- [x] Saturday March 4   - Civic Hack Saturday **Open Data Day** 
- [x] Wednesday March 15    - Civic Hack Night -  **DevBootcamp** 
- [x] Monday March 20   - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Tuesday March 28  - Civic Hack Night - **Galvanize**

### April
- [x] Saturday, April 1 - Civic Hack Saturday - **DevBootCamp**
- [x] Wednesday, April 5 - ATX Hack 4 Change Workshop - **Google Fiber**
- [x] Tuesday, April 11 - Civic Hack Night - **Galvanize**
- [x] Wednesday, April 12 - ATX Hack 4 Change Workshop - **Google Fiber**
- [x] Monday, April 17 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Wednesday, April 26 - Civic Hack Night - **DevBootCamp**

### May
- [x] Saturday, May 6 - Civic Hack Saturday - **Data.World**
- [x] Wednesday, May 10 - Civic Hack Night - **IBM Design Studio**
- [x] Monday, May 15 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Tuesday, May 23 - Civic Hack Night - **DevBootCamp**

### June
- [x] Friday, June 2-4 - ATXHacksForChange - **St Edwards**
- [x] Wednesday, June 7 - Civic Hack Night - **DevBootCamp**
- [x] Tuesday, June 13 - Civic Hack Night - **DevBootCamp**
- [x] Monday, June 19 - Open Gov & Civic Tech Meetup - **Terrazas Library**

### July
- [x] Saturday, July 1 - Civic Hack Saturday - **DevBootCamp**
- [x] Tuesday, July 12 - Civic Hack Night - **DevBootCamp**
- [x] Monday, June 17 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Wednesday, July 26 - Civic Hack Night - **DevBootCamp**

### August
- [x] Saturday, August 5th- Civic Hack Saturday - [**DevBootcamp** ](https://www.meetup.com/Open-Austin/events/233921980/)
- [x] Wednesday, August 9 - Civic Hack Night - **DevBootCamp**
- [x] Tuesday, August 15- Civic Hack Night - **Galvanize**
- [x] Monday, August 21 - Open Gov & Civic Tech Meetup - **Terrazas Library**

### September
- [x] Saturday, September 2 - Civic Hack Saturday - **Epoch Coffee** 
- [x] Wednesday, September 6 - Civic Hack Night - **Conde Naste**
- [x] Tuesday, September 12 - Civic Hack Night - **Galvanize**
- [x] Monday, September 18 - Open Gov & Civic Tech Meetup - **Terrazas Library**

### October
- [x] Saturday, October 7 - Civic Hack Saturday - **Capital Factory** 
- [x] Wednesday, October 11 - Civic Hack Night - **Conde Naste**
- [x] Monday, October 16 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- _Tuesday, October  24 - Cancelled_

### November
- [x] Saturday, November 4- Civic Hack Saturday - **Galvanize** 
- [x] Wednesday, November 8 - Civic Hack Night - **Conde Nast**
- [x] Tuesday, November 16 - Civic Hack Night - **Capital Factory**
- [x] Monday, November 20 - Open Gov & Civic Tech Meetup - **Terrazas Library**  - Thanksgiving Week

### December
- [x] Saturday, December 2 - Civic Hack Saturday - **TBD** 
- [x] Wednesday, December 6 - Civic Hack Night - **Conde Nast**
- [ ] Tuesday, December 12 - Civic Hack Night - **TBD**
- [x] Monday, December 18 - Open Gov & Civic Tech Meetup - **Terrazas Library**  

### Q3-Q4 Booked Dates
- [x] Monday, July 17 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Monday, August 21 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Monday, September 18 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Monday, October 16 - Open Gov & Civic Tech Meetup - **Terrazas Library**
- [x] Monday, November 20 - Open Gov & Civic Tech Meetup - **Terrazas Library**
  - worried about this being the week of 🦃 day
- [x] Monday, December 18 - Open Gov & Civic Tech Meetup - **Terrazas Library**

**Comment by mapineda** [comment]
Scheduled feb 21 and March 28 at galvanize

**Comment by mapineda** [comment]
I've reached out to Chicon to cancel the March 4th event and to see if they can accommodate us Feb 8th.

**Comment by mapineda** [comment]
CHN scheduled for Chicon for Wednesday Feb 8th

**Comment by mapineda** [comment]
I've proposed tentative dates for the coming months. Let me know what ya'll think. I'll reach out to Kelly at Dev Bootcamp for first priority dates and any that she can't fill, I'll begin reaching out to other spaces that worked well for us in the past. Namely, Galvanize and Chicon now that I know how to get in.

**Comment by amaliebarras** [comment]
Yo, I <3333 Chicon for Saturday hacks, but it was tough to do announcements and it was a tight squeeze for the last hack night. Galvanize and DevBootcamp are more hospitable, so if we can do one of those that's ideal

**Comment by VictoriaODell** [comment]
@mapineda are any of our August dates confirmed? I see them in Meetup but want to be sure before annoucing via newsletter. :)

**Comment by mapineda** [comment]
Hey! Will confirm today with Dev Bootcamp RE: august 5th. Working with Bazaar Voice to coordinate a Meetup there either for a CHN this month or a CHS in September

**Comment by VictoriaODell** [comment]
Hey, @mapineda 👋 Can you work to get us September-October and update Mateo's original issue with some dates? I know we are still working to get Bazaar voice finalized for this month too. 

I'll shoot an email over to my Conde Nast contact to see if there are any opportunities there.

**Comment by VictoriaODell** [comment]
@mapineda  Checked the Calendar and a little concerned about our next meetup. We haven't had a page published or a date/location put out. I'm sure some people would come out but we should get something up soon: https://www.meetup.com/Open-Austin/

**Comment by mapineda** [comment]
@VictoriaODell cool, I'll work out deets with your contact at Conde Nast. BV fell through but thankfully Galvanize stepped up for next week. I'll update the meetup page and work on Sept-Oct

**Comment by VictoriaODell** [comment]
@mapineda I'd be interested in seeing if Conde Nast and galvanize can take us through until the end of the year for hack nights while we plan on reaching out for more strategic partnerships the coming year. I think keeping a good relationship with Galvanize is especially important. 

Getting more into their programming and forming more intentional relations with students and teachers would be helpful.

**Comment by werdnanoslen** [comment]
They were very positive about that when we ran our last hack night there.

**Comment by VictoriaODell** [comment]
Yikes. Are we still unsure of where to host for our October 24th meeting?

**Comment by VictoriaODell** [comment]
I also pitched a 2018 partnership to Marcos. He is very open but just wants dates. Conde Nast has other meetups that are there on a reoccurring basis they just need a sponsor from within the company to keep the space in order. He is willing to do that. We just need to go back to him with a specific ask. Also, a continued partnership will likely mean no more pizza. We're the only meetup they have done that for 😄 . We can talk more about in issue #287. 

 He did ask if we had any November dates to fill. If we want to try to get one night from November and December on the calendar + the ask for next year I think now is the time. @mapineda 

I propose we do the open Wednesdays we have for November and December.

**Comment by VictoriaODell** [comment]
Hey @open-austin/leadership thoughts on canceling 3-4 events this coming November/December to make space for leadership time/training? 

I'm thinking the following: 
-  November 14th 
- December 2nd
- December 12th 

Maybe not just canceling but using them as leadership planning time on top of any outside retreat we can schedule. 

and using our November library meeting to plan/source community ideas for improvement and using December to do the same.

**Comment by mapineda** [comment]
Cool with me. Heads up. Will be out of town Nov 30-Dec 4. Also will be out of town the week of thanksgiving.

**Comment by VictoriaODell** [comment]
Okay @mapineda. Also @open-austin/leadership just a note. If you're out for our upcoming event times then be sure to note that here:  
https://docs.google.com/spreadsheets/d/1gllUNFMW73nLcl13vZLQtiLX9hpwIJMON0LY6Qjp1SQ/edit?usp=sharing

**Comment by VictoriaODell** [comment]
@mapineda Via slack re: conde Nast discussion above. "Awesome! Let's go ahead and do the Wednesday for Nov and Dec for this year"

**Comment by werdnanoslen** [comment]
I'm down. What's our attendance usually like during those times? Maybe we can just cancel them on meetup and arrange on iced-coffee when to meet? Or maybe we keep doing Hack Saturdays that month just so we have a regular presence on people's calendars?

**Comment by mapineda** [comment]
@VictoriaODell Capital Factory not available Nov 14th however they are free on that Thursday, Nov 16th. What do you think about moving CHN from Tuesday to Thursday? Also in the comment above you mentioned potentially canceling this night in favor of a leadership meeting?

**Comment by VictoriaODell** [comment]
Hey, @mapineda I think we're good here and can close out?
