### ISSUE TITLE
Idea: Create a List of beginner friendly projects and tutorials

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#202]
For example: 
[Update or audit US Census](https://github.com/open-austin/iced-coffee/issues/61)

other ideas:
- leaflet tutorial w/ open data
- socrata tutorial link
- other easy projects? do other brigades have resources for this?

**Comment by werdnanoslen** [comment]
Would be good to add this to the Civic Hacking 101, too

**Comment by werdnanoslen** [comment]
closing to combine with #178
