### ISSUE TITLE
Let Kelly (DBC) know who will be the point of contact for Saturday

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#204]
@amaliebarras @mapineda @mscarey, who is planning to be at Civic Hack Saturday?

Kelly is going to unlock the building around 8:45 am because she has another event to get to by 9:30. Can someone be there at that time?

**Comment by mapineda** [comment]
I hwill be there. 

Marco

**Comment by mapineda** [comment]
contact: 314-401-2324
