### ISSUE TITLE
Send out general core team application

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#205]
Luqmaan updated the typeform: https://openaustin.typeform.com/to/zyE0a4

Now we need to: 
- [x] confirm it asks the right things
- [x] create a [blog post](https://medium.com/code-for-atlanta/apply-for-code-for-atlanta-leadership-positions-in-2017-1c033ddf45f3#.p4s7qw96j)
- [x] add to newsletter
- [x] twitter

**Comment by amaliebarras** [comment]
I [drafted](https://github.com/open-austin/open-austin.github.io/blob/master/_drafts/our-new-leadership-approach.html) a blog post for this but I'm tracking out of issue [#218](https://github.com/open-austin/iced-coffee/issues/218). Going to close this issue.
