### ISSUE TITLE
Send Newsletter on Dec 6th

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#207]

**Comment by mapineda** [comment]
Working on this right meow 🐱  

Anyone have anything they want to include in announcements? Right now it is looking like a recap of the Texas Appleseed Award, event announcement, o'rielly code for america book bundle

**Comment by mateoclarke** [comment]
definitely make sure to include the 5 upcoming events we have on the calendar. (just added the Library meetup)
https://www.meetup.com/Open-Austin/events/

And maybe also a nod to the Coding4TX student hackahton this weekend:
https://open-austin.slack.com/archives/jobs/p1480521971000359
