### ISSUE TITLE
Send 2nd Dec Newsletter

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#209]
Not sure what date would be best for this. Ideally, this newsletter would be a year end recap and a little different format than the normal bi-weekly newsletter. Right?

Tuesday, Dec 20th could be one due date, or maybe something the 27th, after Christmas and before new year would be a good time to do a retrospective.

What to you think @VictoriaODell & @mapineda?

**Comment by mapineda** [comment]
Vote for the 27th. More timely than the 20th. We can add our list of accomplishments for 2016!

**Comment by VictoriaODell** [comment]
Sorry ya'll. Dropped the ball. EOY is super hectic for me RN and I was in Mexico the 27th, womps. 🙃 Not exactly finishing 2016 strong. 💪

**Comment by mateoclarke** [comment]
No worries. I still have work to do on the year end report. Let's push this back a week, maybe two.

**Comment by mateoclarke** [comment]
_let's try to get this back on track in Feb?_
