### ISSUE TITLE
Onboard Sean into Membership Team Lead

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#211]
# Onboarding a new Core Team member

- [x] set up with info@open-austin.org email
- [x] invite to private #coreteam channel
- [x] invite to #icedcoffee channel
- [x] add to @coreteam [slack user group](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group)
- [x] access to open austin google drive
- [x] link to [core team roles](https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit#heading=h.lfkg13polpyn)
- [x] access to lastpass
- [x] add to github org
- [x] access to google calendar

**Comment by seandellis** [comment]
Just started receiving info@open-austin.org emails. 👍
