### ISSUE TITLE
Values - Internal Project Planning

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#215]
This was one of three internal projects we brainstormed at the 18-Dec-16 Leadership Summit.

https://docs.google.com/document/d/19HncsnlAR5reLH0iul7oi-_tX7Cer-6Y0WCEZ_kkYTU/edit?usp=sharing

To-Do
- [x]  **Feb 14** | Audit what we have
- [x] **Feb 23** | Draft for values ready to share
- [x]  **March 9** | Ongoing edits/review and discussion. Should include the core-team and stakeholders in this phase to get the best feedback + Input
- [x] **March 13** | Comments closed and drafts are finalized and announced.

**Comment by mscarey** [comment]
Some notes from the values discussion: 

Ideas for points on the star (values):
open (government, source, technology)

participation

reproduceability: letting people reproduce the successes we've had

scalable

liberty and data for all


need an ethics guideline for disclosing personal information (protect the peeps)

policy positions organized around campaigns
	start with a slack poll in the policy channel?

common good
well-defined problems

One technology value

STAR method
Situation
Task
Action
Result

Purpose: 

make positive changes in community through civic tech
And the values help facilitate that

Big ideas that we have to narrow down by actually doing projects
Our values should relate to the types of projects we pick

Should we articulate what we should not do?

**Comment by VictoriaODell** [comment]
Here is stuff:
 https://docs.google.com/document/d/1OujyBccPpepUXSY5_nP3alzvd81WlCKSeSf_-sU5K-U/edit

**Comment by VictoriaODell** [comment]
Civic Tech Core Values: 
https://docs.google.com/spreadsheets/d/1rP0O-5MDMnYMMQfIwc-G67FsXdJTxV1wXIDgRRO5_ds/edit?usp=sharing

**Comment by VictoriaODell** [comment]
Can someone on @leadership help me get this on the site? I'm having trouble getting the site running on my computer to do updates myself. 

I get stuck at the chruby stuff.

**Comment by VictoriaODell** [comment]
Need help with this still. 🙃

**Comment by werdnanoslen** [comment]
@VictoriaODell where is the final content you'd like to add? I've never loaded the site locally; I've always just converted my stuff to markdown and then used a previewer to make sure it shows up right.

**Comment by werdnanoslen** [comment]
Let's put this on the website

**Comment by werdnanoslen** [comment]
From leadership huddle notes: @mapineda mentioned he might be able to help with this

**Comment by VictoriaODell** [comment]
![image](https://user-images.githubusercontent.com/10767430/31048300-fdea3546-a5df-11e7-905a-8b7ef6a57e2b.png)

And then in the matching section on the page we need this text: 

> The mission of Open Austin is to help communities and governments exchange ideas through the use of data, technology, and design. 
>
> We do this by hosting educational events and workshops, facilitating community workspaces, advocating for open data and government policy, and providing support and resources for projects and research.  
> We are here because we value: 
>
> **Open Community Spaces**
> Allowing citizens from all backgrounds and skill levels to get involved and engaged in the process of bettering their community through technology and design by providing space both in person or online.
> 
> 
> **Open Government**
> Supporting initiatives and policies to provide clearer paths for residents to engage with government. 
> 
> 
> **Open Data**
> Being stewards, evangelists, and a resource for learning about, finding, using, and freeing public data. 
> 
> 
> **Open Research**
> Supporting data management and publishing practices that help governments, journalists, scientists, and members of the community share their interpretations of open data, from raw datasets to published conclusions.
> 
> 
> **Open Source Technology**
> Creating and using free and open tools to expand public knowledge and civic engagement.

**Comment by VictoriaODell** [comment]
@mapineda ^^^ Let me know if you need any more guidance. :)

**Comment by VictoriaODell** [comment]
@mapineda ETA on when we can get this done? :)

**Comment by mapineda** [comment]
Yea haven't look at it. Prior to D4D hackathon my ruby environment was working great. During and after not so much, so I need to get that working before I can do this. I'll take a crack at it tonight and if not, I'll work on it on Saturday during the CHS.

**Comment by mapineda** [comment]
@VictoriaODell changes made, PR pending review. LMK what you think, if all good go ahead and merge.

**Comment by VictoriaODell** [comment]
This is live. Find for now!
