### ISSUE TITLE
Entity Formation

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#216]
Analyze pros/cons of different Entity Structures and their associated requirements.

- [x] Analyze Pro/Cons of different entities in TX (https://docs.google.com/document/d/1pSnTsi6J0n2M88IV-yjHEqkOlIhr_ndefhBsN2ajOu4/edit?usp=sharing)

- [x] Determine which entity structure best serves OA

- [x] Generate a draft of bylaws & certificate of formation 
(https://docs.google.com/document/d/1HwgQ9lDcJohBLZPyRVvMqvf282mGJOGM17KFNkvBmfA/edit?usp=sharing) 

- [x] Sign/Approve Bylaws as certificate of formation

- [x] Establish Officers

- [x] Research "Open Austin" name to ensure no naming conflicts with other entities (10/19)

- [x] Establish location for OA business address (Registered Agent) (10/19)

- [x] Submit Entity Registration to State (10/19)

- [x] Receive Certificate of Formation (https://drive.google.com/open?id=1W9dD0yPcjqrZsZd8EUoUCx7l0gT0HYEJ)

- [x] Apply for EIN, UPDATE Form SS4 Formation date (11/15 - Certificate of Formation required)

- [x] Receive EIN

- [x] Open up bank account
- [x] 1023-EZ Form, Tax exempt Status for organization

- [x] Receive Federal Tax exemption

- [x] Submit Federal Tax Exemption Certificate to TX for State Tax Exemption
- [x] Receive TX State Tax Exemption notice
- [x] Hold first meeting as an Entity, determine President, VP, Treasurer, and Secretary

**Comment by jonplaca** [comment]
NOTE: I will migrate the final version to the Open Austin Drive. Currently WIP

**Comment by jonplaca** [comment]
Moved file to Open Austin: https://drive.google.com/drive/folders/0B1cMlEZm_nJ0ZV9LdmdVeGN3TXc

@mateoclarke,
Please look over when you have the chance.
Ultimately, I think it would be best if we form our own non-profit. The traditional non-profit gives us more flexibility and enables us to manage our own entity. I am hesitant to find a Fiscal Sponsor (despite NumFocus.org) - ironically there seems to be more risk by relying on a third-party entity.

We can discuss more in this week's ice-coffee meeting.

**Comment by jonplaca** [comment]
@mateoclarke - As you know, I reached out to CFA to determine our relationship with them concerning entity formations. I am primarily interested in to see whether or not funds are consolidated across CFA and then distributed, or whether each brigade only receives only its funds. The reason for my question is to determine whether or not there are any specific benefits to staying with CFA.

Additionally, I would like to see if the State has any restrictions on working with Non-profits vs. a Subsidiary of a Non-profit. *Do you know of State Employee that would have more information on this? I've looked around online to no avail.*

Assuming the CFA *doesn't* distribute funds and the state *only* works with registered non-profit corporations (and not unincorporated non-profits), I think there is a strong argument to convert entities - else, it might be best staying with CFA.

**Comment by mateoclarke** [comment]
Hey @jonplaca, My guess is that funds are consolidated and then distributed. But I think its great to get clarity and definitely a good idea to make sure pursuing formal status and leaving CfA's financial infrastructure has clear benefits.

When you say State, would City be sufficient? I have a contact at the City with a background in legal that might be able to help us.

**Comment by jonplaca** [comment]
@mateoclarke 

Whitaker actually just confirmed that the funds are *not* pooled across the nation and distributed evenly, rather they each brigade is only entitled to their own donations/funds. 
Despite this, there still might be a benefit to staying with CFA since they would handle any tax-compliance issues.

Next step would be to understand whether or not the City would interact with an unincorporated non-profit vs. an incorporated non-profit. 

@mateoclarke *can you provide your contact at the city so I can follow-up for more information?*

**Comment by jonplaca** [comment]
Sent a message to Dawn (Philly) to get her opinions on becoming a non-proft and the pros/cons she's seen. I will share her response when received.

**Comment by jonplaca** [comment]
@mateoclarke following up per our conversation at tonight's meetup: If possible, please deliver information on corporate companies and whether or not they'd be more/less willing to donate to nonprofits vs. volunteer organizations.

If your time is limited, I can handle the conversations with corporate partners if you're willing to facilitate an introduction

**Comment by jonplaca** [comment]
@mateoclarke Updated. We should discuss in more detail.

https://docs.google.com/document/d/1pSnTsi6J0n2M88IV-yjHEqkOlIhr_ndefhBsN2ajOu4/edit#

**Comment by jonplaca** [comment]
Takeaways: 
Co-ops require huge administrative burdens with minimal benefit. Additionally, the idea of voting rights could quickly become cumbersome. Furthermore, the payouts of a co-op can become quite complicated (see: Section 251.302 http://www.statutes.legis.state.tx.us/Docs/BO/htm/BO.251.htm).

I would suggest a non-profit - it's a cleaner process with less administrative burden. Furthermore, distributions can be dealt out (http://www.statutes.legis.state.tx.us/Docs/BO/htm/BO.22.htm#22.054)

**Comment by jonplaca** [comment]
10:59]  
If you like the "voting rights" associated with co-ops, we can form a non-profit and establish voting clauses in the Bylaws that mimic a cooperative-esque voting system

[11:01]  
Also, seems like co-ops have dividend-like payouts, meaning that all members get a fair share of the profit (regardless of whether they attributed to a project or not)

**Comment by jonplaca** [comment]
I will be working on this during the weekend - I am looking to update the bylaw template we received @ last meeting. I will keep everyone posted CC: @mateoclarke @werdnanoslen 

http://www.communitydesign.org/Resources/Documents/BYLAWS14.pdf

**Comment by jonplaca** [comment]
Current Bylaws:
https://docs.google.com/document/d/1D6mhqrxokBCXG8g9I5XXKtBvUyjUCJS4_njqc1N9DVs/edit?usp=sharing

Note, I haven't read through these in their entirety - just copied/pasted (from link in previous comment) and updated spelling errors, state names, entity names, etc to fit Open Austin. 

Please review and comment on any specific areas that you think need changing. I will do the same later today

CC: @mateoclarke @werdnanoslen @patrickm02L

**Comment by werdnanoslen** [comment]
Whoo finally got back around to this. I've added some comments and suggestions, will continue to do so over this weekend

**Comment by werdnanoslen** [comment]
Almost there! If we all approve it at the leadership huddle, is there anything else we all need to do to submit it, or is that something you can do @jonplaca ?

**Comment by werdnanoslen** [comment]
Updates from Sep 8 bylaw review: https://docs.google.com/document/d/10lhAPUEEUitIgafKttUONFGKM80snBlCG1loMBHoxC8/edit#

**Comment by mscarey** [comment]
I made more changes to the bylaws. I think if the changes are accepted, it looks ready to file. https://docs.google.com/document/d/1HwgQ9lDcJohBLZPyRVvMqvf282mGJOGM17KFNkvBmfA/edit?usp=sharing 
Also, I partially filled out the Certificate of Formation form and put it in that same folder (bylaws & non-profit planning). The file is called 202_boc.pdf. We'll need to fill in the information of the people in the different roles. The form has only three spaces for directors, but we can add more after the nonprofit is formed.

**Comment by werdnanoslen** [comment]
I approve these bylaws. Everyone else please take a look at Matt's changes and react by emoji to his message if you accept before the huddle. Then at the huddle we can take care of submission questions or any signatures that may be involved.

**Comment by mateoclarke** [comment]
Looks good to me! This is really exciting!

**Comment by jonplaca** [comment]
@werdnanoslen @mscarey @VictoriaODell 

I reviewed the Bylaws and everything looks good. The only language that I did not accept dealt with changing "Articles of Incorporation" to "Certificate of Formation" as Articles of Formation  are Open Austin's proposed documents to becoming a non-profit - the Certificate Formation is essentially a receipt from the government, recognizing and authorizing our status. Therefore, any language related to amendments should be for "Articles of Incorporation" vs. "Certficiate of Formation"

**Comment by jonplaca** [comment]
@werdnanoslen @mscarey @VictoriaODell - Also, updated original ticket Description for near-term objectives.

Regarding the next Deliverable (establishing Officers) - who would you like to have on the board (minimum 3 individuals).

**Comment by VictoriaODell** [comment]
@jonplaca and I are set to meet with Sarah Goldgar this coming Thursday morning. She practiced non-profit law and is currently a developer. I met her at ACT-W Conference this past year. 


As far as the board q goes, I need some better help understanding the boards relation to officers/leadership. A diagram or something would help me. :)

**Comment by werdnanoslen** [comment]
Commented on Vickie's comment on the doc. https://docs.google.com/document/d/1HwgQ9lDcJohBLZPyRVvMqvf282mGJOGM17KFNkvBmfA/edit#

Also, I think we roughly mapped out the board a couple months ago. It was something like
- President = Captain
- Vice-President = Co-captain
- Treasurer = Finance lead
- Secretary = Comms lead

These are just suggestions, as they're just what currently maps between our snowflake and the board. For example, Vickie, you couldn't be both Secretary and President because we separated those board positions in §5.01

Btw I nominate Vickie as prez

**Comment by mscarey** [comment]
This is from the [Secretary of State's FAQ](https://www.sos.state.tx.us/corp/bocfaqs.shtml) about the meaning of "certificate of formation" in Texas.

> My entity’s governing documents still use terms like “articles of incorporation,” “regulations,” and other vocabulary of prior law. Does this mean that my entity’s governing documents do not comply with the BOC?
> 
> No. The BOC includes a list of synonymous terms so that a reference in your entity’s governing documents to “articles of incorporation” is legally synonymous to a “certificate of formation,” and a reference to “regulations” is synonymous to a “company agreement.” For a complete list of synonymous terms, see section 1.006 of the BOC.

If we submit the generic PDF form from the state, it's titled "certificate of formation" rather than "articles of incorporation." And I don't think "articles of formation" has a specific [definition in Texas law](http://www.statutes.legis.state.tx.us/Docs/BO/htm/BO.1.htm#1.006).

Speaking of the board's relation to leadership, there's also the role of executive director, who is the person who "has day-to-day responsibility for the affairs of the corporation." That role can be held by any of the other board officers or a separate person. If no executive director is appointed, then the president acts as executive director. If we want to be able to name both co-captains as co-executive directors, we might need to mention that in the bylaws. We don't need to assign a person to that role before we file though.

**Comment by werdnanoslen** [comment]
From @VictoriaODell's meeting with Sarah Goldgar this morning:
*   [Sample IRS Application for 501(c)(3)](https://www.bolderadvocacy.org/wp-content/uploads/2012/05/Sample_1023_Form.pdf)  
*   [Texas Nonprofit App Form](http://www.sos.state.tx.us/corp/forms/202_boc.pdf)  
*   [IRS Publication on Tax-Exemption](https://www.irs.gov/pub/irs-pdf/p557.pdf)
*   [IRS Application Process Interactive Questionnaire](https://www.irs.gov/charities-non-profits/application-process)
*   [IRS Guide on 501(c)(3)](https://www.irs.gov/pub/irs-pdf/p4220.pdf)
*   [Before Applying for Tax-Exempt Status ](https://www.irs.gov/charities-non-profits/before-applying-for-tax-exempt-status)

**Comment by jonplaca** [comment]
Officers established:
Matt
Sean
Jon
Vickie
Andy
Marco

**Comment by werdnanoslen** [comment]
Just dropping a reminder here from the leadership huddle for @jonplaca to find a registered agent service/company, and report back with options (including prices)

**Comment by ErieMeyer** [comment]
Hi all! Jumping in to follow along -- thanks for sharing this link with me. I have follow-up questions about items mentioned here but don't want to derail (unless it's helpful to have them all in the same place -- let me know!).

**Comment by werdnanoslen** [comment]
Go for it, we chat here and on Slack mostly. Better to keep stuff in one of the two so others can follow along :)

**Comment by VictoriaODell** [comment]
Hey @ErieMeyer Feel free to comment!

**Comment by VictoriaODell** [comment]
@jonplaca can we get some tentative dates added to this?

**Comment by jonplaca** [comment]
@VictoriaODell ETA to submit application this Thursday 10/19.
Dates added above

**Comment by mscarey** [comment]
I just did an entity name on the [Secretary of State's website](https://direct.sos.state.tx.us/corp_inquiry/corp_inquiry-find.asp), and I don't see any issues. The search for "Open Austin" returned 568 results but these were the only remotely close ones:

 	800346868 	The Open Door Ministry of Austin 	Domestic Nonprofit Corporation 	In existence 	Legal 	In use 
 	802009766 	Open Six East Austin Hotel LLC 	Domestic Limited Liability Company (LLC) 	In existence 	Legal 	In use 
 	111939601 	OPEN DOOR CHURCH OF GOD IN CHRIST, INC. OF AUSTIN Domestic Nonprofit Corporation 	In existence 	Legal 	In use 
 	800195651 	AUSTIN OPEN MRI, LP. 	Domestic Limited Partnership (LP) 	In existence 	Legal 	In use 
 	800668249 	Open A Management, LLC 	Domestic Limited Liability Company (LLC) 	In existence 	Legal 	In use 
 	800743286 	OPEN A INVESTMENTS, LTD. 	Domestic Limited Partnership (LP) 	In existence 	Legal 	In use 
 	801723491 	Open A Ranch, LLC 	Domestic Limited Liability Company (LLC) 	In existence 	Legal 	In use 
 	802041469 	OPEN A ARENA, LLC 	Domestic Limited Liability Company (LLC) 	In existence 	Legal 	In use 

A US PTO trademark search returned only one result: the defunct trademark for ["BILL AUSTIN'S OPEN PIT BAR-B-Q CHICKEN-BEEF & RIBS"](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:g043dh.2.1)

**Comment by jonplaca** [comment]
Certificate of Formation to be submitted tomorrow. Board will include members previously mentioned.

I'll keep the group posted on when we receive our Certificate of Formation.

**Comment by VictoriaODell** [comment]
Was on an email with a few others that are going the non-profit route and I liked this from Code for Charolette: 

> Charlotte is moving forward with the 501c3. We just finished seating our board of 9 people with an advisory board of 12. And the lawyer has the paperwork to review and submit. I expect that it will be submitted in the next couple of weeks. Our nonprofit is named Open Charlotte and Code for Charlotte will be a program of the nonprofit. We’re doing it that way to draw a clear line between paid and volunteer work.

**Comment by VictoriaODell** [comment]
@jonplaca do we have any ETA on when we will receive the certificate?

**Comment by jonplaca** [comment]
@VictoriaODell ~2 weeks; I've followed up with the State and they've confirmed that if in two weeks we do not receive a notification to follow up.

**Comment by VictoriaODell** [comment]
Hey @jonplaca any news here?

**Comment by VictoriaODell** [comment]
Also, what do we do since we lost two officers that we had earlier identified? Sean and Andy.

**Comment by VictoriaODell** [comment]
@jonplaca I checked that we got our certificate. Now we need to apply for our EIN?

**Comment by jonplaca** [comment]
@VictoriaODell Yes, we need to apply for the EIN. I already have the signed documents and will be submitting this week.

See the original issue description for the location of the newly updated Certificate of Formation (https://drive.google.com/open?id=1W9dD0yPcjqrZsZd8EUoUCx7l0gT0HYEJ)

**Comment by VictoriaODell** [comment]
@jonplaca informed me that we have received our EIN number. Should be meeting with him soon to go over any next steps.

**Comment by VictoriaODell** [comment]
Met with @jonplaca Jon Today. 

It takes about 6 months to get recognization at the federal level as a non-profit. Jon is submitting the forms for 559 this weekend. There are a couple other to-do's @jonplaca will update us on. One of them being us going out to make a bank account.

**Comment by jonplaca** [comment]
As @VictoriaODell mentioned, we received the EIN number - currently investigating relevant banks that favor non-profits. 

Simultaneously applying for federal tax exemption - will keep you updated

**Comment by jonplaca** [comment]
@VictoriaODell Reached out to a number of banks thus far, Wells Fargo seems like a valid candidate. I will keep reaching out to major institutions.

@VictoriaODell - last week you mentioned a local bank - can you reiterate their contact information and I'll try reaching out to them?

**Comment by mateoclarke** [comment]
I'm biased towards credit unions. I've heard Velocity CU is good for non-profit banking.

**Comment by jonplaca** [comment]
CC @sortizsh

**Comment by jonplaca** [comment]
Bank account opened at UFCU.
Financial Information shared with @VictoriaODell. 
Need to add @sortizsh to Bank Account (to obtain debit card). 

@VictoriaODell to follow-up with CFA to understand offboarding process (I can assist if needed).

**Comment by jonplaca** [comment]
@VictoriaODell @sortizsh Form 1023-EZ (application for Tax-Exempt Status) for Federal Government has been paid for and submitted. Now we wait for the Fed's approval, so that we can then gain TX's approval as a tax-exempt entity.

**Comment by jonplaca** [comment]
Spoke with IRS today to follow-up on on 501c3 status. Status was approved 2 weeks ago and, per the commentary of the individual, the notice should arrive within the next 1-2 days via mail.


CC: @VictoriaODell @sortizsh

**Comment by jonplaca** [comment]
Received Federal Exemption
[Uploading 2018 05 - Open Austin - 501c3 Confirmation.jpg...]

**Comment by jonplaca** [comment]
@VictoriaODell What address do you want the new entity to be located at?

**Comment by jonplaca** [comment]
@VictoriaODell @sortizsh - Sent TX Comptroller a notice of our Federal Exemption status. Filled out for AP204 to receive similar recognition in TX (CC'd you both on email to Comptroller).

I will keep you posted on a response.

**Comment by jonplaca** [comment]
@VictoriaODell 

Do you have an address that you'd like me to update for TX and the Fed regarding Open Austin? I'll update all this information once I wrap up the Tax exempt status confirmation with TX Comptroller

**Comment by jonplaca** [comment]
@VictoriaODell @sortizsh 

It's official! 
Open Austin is officially a 501c3, recognized by State and Federal Government.

For Texas, we just received verification that they've accepted our status.
Our Tax ID: 32065445929
Please use this Tax ID for sponsors that want to confirm Open Austin as a 501c3.

I will update the Drive to include materials which will highlight our status so that, when fundraising, you can attach this information for the sponsor

**Comment by jonplaca** [comment]
FYI I've updated Open Austin's Google Drive > Legal folder to include all State and Federal Documents

I've also attached the main, important files here
[2017-12_Texas_Certificate of Formation.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a3dd89aebfc7200014a91a/125516c66e82c728ace21e0d46bac4cb74cfd2fbb0ddba5ba54ecfb72c54337a2f0da02a6480a327b9025d0e1d021fe818070156e0ebc969f9ec6923ce4e01ffd46b5c26933f18afee8a4cbc03e8718c4f85e3e8834dc7ea2f39f5c9de116a415841c3aa1f27aa8b4ac152f74ee24b52a2173165e3773e7f55d9.pdf)
[2018-01_Federal_EIN.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a3dd89aebfc7200014a91a/125516c66e82c728ace21e0d46bac4cb7bcfd3f8b0cfba47a14ff19816630e5d6b48e13b628ae92dbc56395b4d5a48af130d5d4dffaf8178a5b46e218d5c0bb885645e73c42f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e48d88493a19031f8efe5827ed.pdf)
![2018 05 - Open Austin - 501c3 Confirmation.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a3dd89aebfc7200014a91a/125516c66e82c728ace21e0d46bac4cb7bc2d3fccfa4ff6cb458fed408533467200ae36630d0b379bc113b22000118f503050e00a5a6d739baa47c32d5065ebe957f5566c33b12feed8016bc57b273884dd7e7bb8a4c95bc3424e0899d532c5c5446dda0006ceacc09da52e44ae64754a1103064e072317a4e931c763e26.jpg)

**Comment by jonplaca** [comment]
![2018 05 - Open Austin - 501c3 Confirmation.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a3dd89aebfc7200014a91a/125516c66e82c728ace21e0d46bac4cb7bc2d3fccfa4ff6cb458fed408533467200ae36630d0b379bc113b22000118f503050e00a5a6d739baa47c32d5065ebe957f5566c33b12feed8016bc57b273884dd7e7bb8a4c95bc3424e0899d532c5c5446dda0006ceacc09da52e44ae64754a1103064e07231744f901f7c3e26.jpg)

**Comment by jonplaca** [comment]
[2018 09 - Texas - Open Austin, Exemption Letter (1).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a3dd89aebfc7200014a91a/125516c66e82c728ace21e0d46bac4cb7bc2d3f0cfa4ff77a145f187690b675c3901ad6b5190f03cb64c37412a171bf1011c061ba2e9f57ee2f269329a440af4c3714d3484624bf9ebc60db513bf26881dd0b4b5891ac8bb3e27b5da884f3e4b511188f85f27bc8b099906a214bc141ff1512469f477317646911d732b6d632eabfbdd5281972d.pdf)
