### ISSUE TITLE
Feb 16 Leadership Meeting Agenda

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#217]
Starting an agenda here for structure. We can totally deviate if necessary.
### Agenda

- The month ahead...
- revisit the [snowflake](https://www.open-austin.org/assets/snowflake_model_2017.png)
- [political actions](https://github.com/open-austin/brigadesandpoliticalaction) 
- Review Internal Projects
  - Open Austin Labs #210 
  - Entity Formation review #216
  - Values #215 
  - Roles & Leadership Development #218 
  - Membership UX #221 
- Dive into projects in smaller teams
- Bike rack (other ideas we need to get back to):
  - t-shirt inventory, new shirts? new attendance record? [membership](https://drive.google.com/accounts?continueUrl=https://docs.google.com/document/u/1/d/1GQbmlomA9p3VI6RSOl0atnoSTQNtDa2O3dG6O-SVmgI/edit?usp%3Ddrive_web&ddrp=1#)
  - clean up iced-coffee issues
  
## Action Items 

- [x] Sean - Update Snowflake
**Jon | Finance** Change resource lead name
**Andy | Private Org Liason** Academic Research, Project Management / Development, Connect w/ Business
**Hannah | Project Team Lead** Clear the path, pick 2-3 projects that we can own, write a few tutorials for new peeps
**David | Volunteer Placement** 
- [ ] Mateo - onboard our new leadership team members [open-austin.org email, add to coreteam slack, etc.]
- [x] Mateo - set up 1:1 or 1:2 meetings w/ everybody to figure out how to help
- [x] Jon - create doodle poll for meeting before SXSW w/ entity formation, featured projects to prototype process
- [x] Amalie - connect Sean w/ Kaitlin who wants to work on onboarding

**Comment by jonplaca** [comment]
Sent out Doodle poll.
See: https://waffle.io/open-austin/iced-coffee/cards/58aa7328996c0a7300722421 for more details

**Comment by seandellis** [comment]
Here's a copy of the updated team snowflake along with one for a project team. Let me know if there's anything else you'd like to include.

![diagram-open austin-team structure-20170221](https://cloud.githubusercontent.com/assets/1584916/23186063/51a2bd40-f84b-11e6-8f61-a8c7b1a9e4e4.png)

![diagram-open austin-project structure](https://cloud.githubusercontent.com/assets/1584916/23186064/51b6ca42-f84b-11e6-9af8-7f2802e04f02.png)

**Comment by amaliebarras** [comment]
looks gr8 to me @seandellis

**Comment by amaliebarras** [comment]
@seandellis I referenced this in a blog post draft just now. Also this would be amazing wiki content! Have you thought about adding it to our [about page](https://github.com/open-austin/open-austin.github.io/blob/master/about/index.md) too?
