### ISSUE TITLE
Roles and Leadership Development

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#218]
#### 1. Sharing out where we are so that we can co-create the model
- [x] Share opportunities w/ community 
![screen shot 2017-02-15 at 8 45 02 pm](https://cloud.githubusercontent.com/assets/11826646/23005048/a84fc434-f3bf-11e6-90e5-21d75b35fa3c.png)

#### 2. Prioritize critical roles & fill them 

- [x] Filled critical roles
- [ ] @seandellis to update snowflake

#### 3. Team leads requirements for all teams

- [x] Amalie Consolidated & Drafted [New Roles Document](https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit#heading=h.luseebsphfta)
- [ ] @VictoriaODell  review comms roles
- [ ] @seandellis  review memberhip roles 
- [x] @mapineda  review events roles
- [x] @mscarey  review policy roles
- [x] @jonplaca  draft resource roles
- [x] @mateoclarke review non-branch roles 

###### Draft

* Apply using [typeform](https://openaustin.typeform.com/to/zyE0a4)
* Wait for one of us to respond or [ping us](info@open-austin.org)
* Chat with one of us and get plugged into core team meetings
* Start showing up
* Find your place on our leadership [snowflake](https://drive.google.com/drive/u/0/search?q=.ai)
* Create your own [onboarding card](https://github.com/open-austin/iced-coffee/issues/211) and assign to @mateoclarke 

#### 5. Announce new leads, invite people to onboard by MAR 29

**Comment by amaliebarras** [comment]
assigning to sean so he can share updated snowflake!

**Comment by jonplaca** [comment]
joining this card so I remind myself to complete part of this task

**Comment by jonplaca** [comment]
Left commentary on "New Roles Document" - please feel free to review accordingly.

**Comment by amaliebarras** [comment]
assigning coreteam to review their team roles ... plz unassign yourself and check box when you're done!

**Comment by mscarey** [comment]
I put a "Policy Champion" role in the policy team, similar to a project champion, but for people who introduce a policy initiative that doesn't really involve a technical dimension or any product management. Open to discussion whether that should fall under "policy" or "projects." But now that I've described the advocacy process in the doc, it makes me think we should have an easier way to highlight policy initiatives on the website.

**Comment by amaliebarras** [comment]
@mscarey Nice! I'm thinking about #234 as a potential Policy Champion / Project team collab :)

**Comment by amaliebarras** [comment]
@mateoclarke does that roles process under #4 look right to you? would you add anything? I think patrick mcdonnel is interested and he could help us prototype this!

**Comment by mateoclarke** [comment]
@amaliebarras: 4 under next steps? Yeah that seems right. Start showing up seems like a pre-req instead of in the middle of the list.

Here's how I would outline it if it were sequential:
1. Start showing up
2. Apply using typeform
3. Ping us at let us know you filled out the application
4. Chat with one of us ask when the next leadership team meeting is scheduled.
5. Look at our leadership "snowflake" model and decide where you would like to contribute.
6. Create your own onboarding card(issue) and assign to @mateoclarke

**Comment by amaliebarras** [comment]
Are you thinking of "start showing up" as coming to general meetings, or coming up to our leadership meetings? I was thinking the ladder, but maybe both should be in the process @mateoclarke

**Comment by mateoclarke** [comment]
hack nights or general meetings is what I meant. But now I understand what you meant by including it later in the process.

**Comment by amaliebarras** [comment]
started writing about this [here](https://github.com/open-austin/open-austin.github.io/tree/master/_drafts)

**Comment by werdnanoslen** [comment]
I think this can be closed, considering the other open issues linked here? 

I'll message @amaliebarras about that draft she was working on

**Comment by seandellis** [comment]
@werdnanoslen yeah, this can be closed.
