### ISSUE TITLE
Photo Folder

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#22]
Create a photo folder of past open Austin Events to pull imagery from for future marketing and outreach efforts. Label by event title and date and place in the Open Austin Google Drive.

**Comment by mateoclarke** [comment]
yeah, we should do this!

Got a bunch of photos saved here. Would be better if there were in a Google Drive or something better: https://photos.google.com/album/AF1QipPAHYtvYE6rGTer_bQkt16LH0ynKCYDHzCUMkVh

**Comment by mateoclarke** [comment]
done! :snowflake: :coffee:
