### ISSUE TITLE
Setup Next Snowflake meeting

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#222]
@channel Based on the Doodle Poll results, the majority of individuals can meet on Tuedays. February 28th @ 7:00pm or March 7th @ 7:00pm. However, two of the three (@marco  , @sya, @amaliebarras) may be unable to make it.

@marco, @sya, and @amaliebarras  - is there any flexibility in your schedules that *might*  open up your availability on either Tuesday?

See attached PDF to review everyones' responses.

**Comment by jonplaca** [comment]
see: http://doodle.com/poll/ndtduwta432362fz for responses

**Comment by jonplaca** [comment]
Marco has confirmed that he can make it on 2/7 @ 7pm - making it the best date for the majority of individuals.

@mateoclarke can you send out a calendar invite to the team. 
Else, can someone point me to a directory where there is a list of Core Team member email addresses?

**Comment by mateoclarke** [comment]
sent!

**Comment by jonplaca** [comment]
Marked as complete
