### ISSUE TITLE
Status Check / Clean Up Open Austin Repos

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#223]

**Comment by mateoclarke** [comment]
this is done (for now), no?

**Comment by amaliebarras** [comment]
Nope. Only the project idea repos have been done. This is probably backlogged until we land on a project process / criteria

**Comment by mateoclarke** [comment]
ah, could you make a checklist in the first comment of what needs to be done and what has been done?

**Comment by amaliebarras** [comment]
assigning to Hanna to document this as part of project dropoff research per our conversation 3/22

**Comment by werdnanoslen** [comment]
Like a project idea, repos should be left alone until someone stumbles upon it and decides to continue working on it. What would "clean up" mean though?
