### ISSUE TITLE
New Project Step-By-Step

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#224]
### Intake:
* Create a project-idea issue, link repo in readme
* Create a repo and add tags for
** Stack
** Status
** Needs

### Evaluation: 
* Someone will evaluate to make sure you’re not doing anything sketchy
* They may point you to another similar project in OA to join
* They may suggest an existing project in the CFA network

### Production: 
* Leave a comment every time you work on it at an event
* @amaliebarras if you have specific needs

### Marketing: 
* When your app is ready to use, let the comms team know and they’ll walk you through
** Documenting 
*** Github README
*** Open-Austin.org
** Blogging
** Sharing on social media
** Engaging Open Source community

## Figure out where to publish this, new project champ UX.

**Comment by amaliebarras** [comment]
reference @VictoriaODell 's [6 steps to successful project](https://docs.google.com/document/d/1QvssEVp0K51qePEDouD2USfnXmmysiSWT6B0aGrH-Yk/edit)

reference [civic hacking roadmap](https://github.com/open-austin/iced-coffee/issues/69)

**Comment by amaliebarras** [comment]
Drafting out what this might look like 

<img width="668" alt="screen shot 2017-02-25 at 12 54 31 pm" src="https://cloud.githubusercontent.com/assets/11826646/23333890/afdd14b2-fb59-11e6-861f-87f4fac82186.png">

Feedback needed and appreciated!

**Comment by amaliebarras** [comment]
assigning this to you @hlupico but I'll myself on to lurk / assist you as called upon

**Comment by amaliebarras** [comment]
## From 3/22

[notes](https://docs.google.com/document/d/14tT9UhlWOO95R_2dboFYR1eauxYt_Dp8Avt0lri9sfA/edit) from our team conversation 

Relevant action items

- [ ] Research project drop off, create google doc with status of current repos
- [ ] Ideate of names of project phases
- [ ] Make edits to our ideas template based on CfD's

**Comment by werdnanoslen** [comment]
The problem and project definition bits from Mozilla's open leadership training is pretty useful for part 1: https://docs.google.com/presentation/d/1bCOAoLrNtRVuTt0dtOwsnzbclbGTvWUkcdzk-o8iJeM/.

For example, here's the project vision step that is between figuring out what i'm doing and filling out a canvas:

> Brainstorm answers to these questions:
> 
> - 1. Who you’re working with, or hope to work with
> - 2. What you’re doing
> - 3. Who you’re doing it for, your audience (may be same as b)
> - 4. Why you’re 
> 
> doing this, the impact or change you hope to make
> 
> Put your answers together in a short statement:
> I’m working with [community, allies, contributors] to [make, build, teach, or do something] so that [audience, end users, consumers, community members] can [do something different, achieve a goal]
>

**Comment by werdnanoslen** [comment]
When creating new issues, I suggest we immediately add a "Help Wanted" tag so it can show up here: http://civicissues.codeforamerica.org/geeks/civicissues

And our projects with an Open Austin repo should [soon](https://github.com/codeforamerica/brigade-information/pull/35/commits/c3dac487717b758be4ea854ecff4c15f76f89025) show up here: http://brigade.codeforamerica.org/brigade/projects

With that as a policy, we can immediately direct people to check these two sites as well as our repos specifically for finding similar efforts. Unfortunately, the issues one is [not searchable](https://github.com/codeforamerica/civic-issue-finder/issues/30), and I don't have the dev environment ready to make that change right now. In the meantime, we can fork it to embed on our site, along with an embedded project finder. That would probably be a weekend hack day's worth of work, but it'd translate to more cross-brigade or at least cross-project exploration and (hopefully) collaboration. By the way, this is one practical example of "knowledge matching" I was talking about @amaliebarras

**Comment by hlupico** [comment]
Thanks Andy - this is awesome!

**Comment by werdnanoslen** [comment]
just to document here what we discussed yesterday:

scratch the help wanted tag, that project is abandoned by CfA and we can make our own fork for the website. We can choose the labels

**Comment by mapineda** [comment]
@werdnanoslen there was a need expressed at the previous CHS about projects being tagged with their "tech stack" ie: reactjs, angularjs, angular2, php, mongodb, sql, c#, python etc

**Comment by werdnanoslen** [comment]
Re:@vickie I should make this into a blog post, and maybe a lightning talk

----
Andrew Nelson
andyhub.com
832-677-7180
(sent from mobile)

**Comment by werdnanoslen** [comment]
I'm just going to make this the canonical issue for this work and close the others. Here's some related issues:

#237
#235
#233
#224
#218
#215
#69

**Comment by werdnanoslen** [comment]
I think this has been captured in the new project idea template. We can make new issues targeting more specific outcomes we want, but I think the original intent of this issue has been completed.
