### ISSUE TITLE
March 7 Leadership Meeting Agenda

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#227]
**Time**: 7-9pm
**Location**: 2900 Manor Rd

**Agenda**: 
- 7pm: Breakouts
  - Projects
  - OA Labs/Entity Formation
  - Values
  - other?
- 8pm: Share backs
- 8:30pm: General announcements
  - #rosebudthorn

**Comment by mateoclarke** [comment]
## Project Team Lead Roles

Amalie -
Likes:
Communicating with the city to fulfill needs
Helping volunteers find forking opportunities
Civic Hacking 101, sometimes

Needs Help With:
Civic Hacking 101
Knowledge of existing projects in repo
BASED Board and Blogging

Wants to:
Create a system for leadership to connect volunteers to existing projects that fit their skill set and interests


Hanna -
Wants to:
Help with Civic Hacking 101
Project process for projects at all project tiers
Manager developer resources
Help Product Managers define their requirements and refine their value prop


Need To Do (Actionable Items):
Update the Open Austin Role Description with what the two Project Co-Leads are responsible for
Better Define Product manager/Project Champion roles for Portfolio Projects
Define what the project tracks are (Portfolio Projects/Unofficial Projects)

**Comment by mateoclarke** [comment]
## Values

https://github.com/open-austin/iced-coffee/issues/215#issuecomment-284922906

**Comment by mateoclarke** [comment]
## Entity Formation

Delay non-profit until the following:
- [ ] Reach out to local companies and understand how companies donate to non-profits vs volunteer organizations
    - IBM
    - Data.world
    - Capital Factory
    - Foundational gives
    - etc.
- [ ] Alternative: Co-op
Research req.
https://www.sba.gov/starting-business/choose-your-business-structure/cooperative
  - [ ] Research Yellow Bike Project

- [ ] Mateo to handoff finances to Jon

**Comment by danielryne** [comment]
# **Membership Discussion Notes:** 

**1. Tracking attendance**
Last Monday used membership link to track headcount at events, as well as follow up with meetup attendees afterwards. 

**2. Member communication outside of Slack**
Creating email groups or improving regular newsletters?
Develop standard messages for different clients: 
- Welcome (with basic info) for new members 
- Newsletters 

**3. Website updating**
Redoing website or elements of website to be more user friendly for non developers
No intro to organization and how to interact 
Projects are oldest to newest 
Project intake process 
Email box

**Some Next Steps:**
Test new member email to list in March, using mailchimp? (Sean)
Working on user interviews to get feedback on website (Sean)
Sean to work with Vicki on planning website updates 
Standardizing Meetup event templates and other resources? (Daniel)

Questions: 
Do we currently use an email client? - Yes, MailChimp for newsletters
Where can some of these communication tools and processes live? GitHub wiki? (ie. meet up event language)
What is our goal for attendance tracking? Why is that number important?
