### ISSUE TITLE
Create welcome email and page for new attendees

### ISSUE THREAD

**Issue by seandellis** [open-austin/iced-coffee#228]
@amaliebarras @VictoriaODell @mateoclarke @mapineda @hlupico I'm throwing you all in here to get your advice.

I've looked into the Zapier integration with MailChimp and it's pretty simple. A nice feature is that I can have MailChimp send an email to attendees that sign in to our welcome form.

To make it easier to maintain and reusable on our site, I'd like to make a welcome page for new attendees on the site.

Is there a list of things that new attendees would be interested in and need to know?

---

Here's my first take on what the email and welcome page might contain.

---

### Sample Welcome Email

---

# Welcome to Open Austin

Thanks for signing in to our event. We're glad to see you here!

**Want to help on a project?** 

Browse our list of [projects](https://github.com/open-austin/project-ideas/issues).

**Is this your first event?**

_Visit our site to see how to get access to Slack and XYZ_ (need to figure out what this is)

http://open-austin.org/newattendees

**For regular attendees**

Welcome back! Attending and signing in to five events will get you one of our awesome Open Austin t-shirts.

Regards,

Sean Dellis
Membership Lead @ Open Austin

---

### Sample Welcome Page

This page would contain details about the group and how they can contribute.

---

We're glad you're here. 

Here's a rundown of how we do things.

[Needs Content]

* You can request a Slack invite...

**Want to help on a project?** 

Browse our list of [projects](https://github.com/open-austin/project-ideas/issues).

---

**Comment by VictoriaODell** [comment]
This is looking good, Sean. 

I would say the following are things that people are who are new may be interested in. You hit on a lot of it with your draft: 
- How to get involved now: slack, link to projects, rsvp
- When the next meeting is and what to expect
- Where we are on social media
- Open Austin origin/overview of civic hacking?
- How to contact someone to ask a question

**Comment by hlupico** [comment]
I like the idea of having a welcome email and an email for returning volunteers. In the welcome email for new volunteers I think it would be helpful to reiterate the mission of Open Austin in context.

Maybe something like: "Thanks for signing in to our event. We're glad to see you here! You can help advocate for open government and contribute to open application development by jumping into help with an existing project (link to browse projects) or you can introduce us to your own project idea (link process for project development).

**Comment by seandellis** [comment]
Adding this for reference: https://github.com/Data4Democracy/read-this-first

**Comment by VictoriaODell** [comment]
Hey @seandellis. We should connect on this. I think we can simplify our welcome email process by just using Mailchimp Automation. I mentioned this at a hack night. Do you have 30 minutes or so to connect sometime in the next week or so? We can do a video chat.

**Comment by seandellis** [comment]
@VictoriaODell Sure. Just sent you an email.

**Comment by VictoriaODell** [comment]
@seandellis this is essentially done, right? I know we talked about ways to potentially improve but maybe we can close this issue for now?

**Comment by seandellis** [comment]
Still working on it. I need to update the welcome messages across all of our accounts.

**Comment by werdnanoslen** [comment]
@seandellis want any help on this?

**Comment by seandellis** [comment]
@werdnanoslen That would be great! 

Could you update the [Mailchimp Welcome email](https://us13.admin.mailchimp.com/campaigns/wizard/autocampaigns?id=913621) whenever someone signs up for our newsletter?

Once that's done you can close this issue.

----

You can tailor it based on this message:

Welcome to Open Austin
Thanks for filling out our membership form. We're glad you're here!

[Learn more](http://open-austin.org/welcome) about Open Austin and how you can get involved.

*For regular attendees*

Welcome back!

Signing in at five events will get you one of our awesome Open Austin t-shirts. Was this your fifth event? Contact @seand on [Slack](https://open-austin.slack.com/messages/) with your shirt size.

Regards,

Sean Dellis
Membership Lead @ Open Austin

**Comment by werdnanoslen** [comment]
There doesn't seem to be a welcome email, but I'll set it up

**Comment by werdnanoslen** [comment]
Oh! Nevermind, there are two accounts on LastPass, using the new one now.

**Comment by werdnanoslen** [comment]
Ok, turns out there's a built-in way of doing this as a "Final Welcome Email" after the confirmation email. So I put this content there:

![image](https://user-images.githubusercontent.com/764090/30236493-f8932294-94df-11e7-96d8-08ce3afb1236.png)
