### ISSUE TITLE
Develop Financial Model & KPIs

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#229]
Develop a sustainable Financial model based on historical spend and donation. Work to forecast future cashflows

**Comment by werdnanoslen** [comment]
@jonplaca this doesn't have to happen before we submit for incorporation does it?

**Comment by werdnanoslen** [comment]
Need to incorporate, then get a bank account, then we can get back to this

**Comment by jonplaca** [comment]
See issue #286. Closing this card as duplicate
