### ISSUE TITLE
Implement Financial Operations

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#230]
Review historical expenses and begin proper accounting. Take note of all Balance Sheet items that may be available (e.g prepaid expenses such as annual software subscriptions)

- [x] Tie Accounting System to Bank Account

- [ ] Review and categorize historic financials

- [ ] Establish financial forecast model

- [ ] Tie-in OpenCollective.com for income stream and reimbursement activity

**Comment by jonplaca** [comment]
Currently researching free accounting software:

- https://www.waveapps.com/pricing/

- https://zipbooks.com/

I have some experience with wave, but mostly used Quickbooks. Considering most of our accounting will just be for expenses, I think QB might be overkill at this point. Plus, any accounting system should have modularity involved. I will see what flexibility wave and zipbooks offer

cc: @mateoclarke

**Comment by jonplaca** [comment]
@mateoclarke After researching wave vs. zipbooks, I would recommend zipbooks for the following reasons:

- Stronger Financial Reporting
- Professional Invoices (including Recurring Invoices)
- Team Collaboration
- Company Documents (e.g historical tax payments, company formation docs, etc.)

I will say that wave is stronger on tracking receipts and bulk uploading a chart of accounts - but these are both minor and can be dealt with in Zipbooks.

Of course, this would require that we connect our current bank account; something that is sensitive and should be handled by you ( @mateoclarke ), solely. 


If you'd like to proceed down this path, once you connect the bank account, I can start categorizing and standardizing most of our financial statements. In the future, this will allow us to get a better handle on how/where we spend money and forecast our financials (which may help with fundraising initiatives - if we choose to do so).

**Comment by jonplaca** [comment]
Moved to backlog - dependent on https://waffle.io/open-austin/iced-coffee/cards/58a3ddf28ee241730040e8ff

**Comment by jonplaca** [comment]
Adding https://opencollective.com/codeformiami for #fundraising capabilities.

Idea is to drawdown CFA account and simultanously fundraise through OpenCollective (Entity formation is required beforehand so that we can accept donations into a specific bank account) 

CC @mateoclarke

**Comment by werdnanoslen** [comment]
Need to incorporate, then get a bank account, then we can get back to this

**Comment by jonplaca** [comment]
Incorporation completed.
Blocked as no funds have been transferred to UFCU (#236)

**Comment by mateoclarke** [comment]
We should be unblocked once CfA issues OA funds in the for of a grant which Vickie mentioned two leadership syncs ago. Going to reopen...

**Comment by mateoclarke** [comment]
@JMensch & I decided to close out this issue in our 501c3 working group mtg [on 3-26-19](https://docs.google.com/document/d/1rhit58w16fn7TJGtTyc54qt-9AVEkyRLBMdrWNgNlbo/edit) 

It seems like a financial model and categorizing past expenses is unnecessary at this point. We just need to decide on how to track expenses for basic accounting and we have #340 open for that.
