### ISSUE TITLE
Create wiki that documents our process and tools

### ISSUE THREAD

**Issue by seandellis** [open-austin/iced-coffee#231]
These are some general ideas that our Wiki could contain.

## Toolset

* Wiki - GitHub?
* Communication - Slack
* Blog - Jekyll, Medium
* Storage - Google Drive
* Issue Tracking - GitHub

## Best Practices for Github wiki

[Netflix/Hystrix Wiki](https://github.com/Netflix/Hystrix/wiki)

**Comment by hlupico** [comment]
A folder for high level org information would be great in addition to a folder for each of the 'snowflake' branches (Members, Projects, Finance, etc).

**Comment by amaliebarras** [comment]
Definitely! I could see our projects best practices living here, BASEDEF, and documented workflow stuff (like @hlupico 's idea of creating a guide for writing to request public information)

**Comment by amaliebarras** [comment]
oh and maybe our new [civic hacking 101](https://drive.google.com/file/d/1xsz6XziJsywxkC7cbIHmLU4kxJRjasjTGQ/view?usp=sharing) video!

**Comment by VictoriaODell** [comment]
@seandellis and I discussed this today! We're going to start working to create docs using the Iced-Coffee Wiki. We'll need to work on prioritizing docs. 

I think a good start would be moving what @amaliebarras has collected here in issue #218  and put it in the wiki.

**Comment by werdnanoslen** [comment]
we should also document what our own and members' most common suggestions are for I/PaaS:
- AWS for computing power
- Heroku for app hosting
- Google for web service APIs (e.g. Maps/Places)

**Comment by werdnanoslen** [comment]
The [iced-coffee wiki](https://github.com/open-austin/iced-coffee/wiki) is up and occasionally updated, but we could probably do a better job of doing so more often. We can make new issues for specific updates we want to make, but I'll close this one since all the content posted here has been added.
