### ISSUE TITLE
Email follow up SXSW Create & First March Newsletter

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#232]
I want to make the SXSW Create email a little more personal to follow up with everyone that stopped by. We have a good sized list. I can do the data entry for the names in a google sheet. 

Both the regular newsletter and the Create one should drop on Tuesday. I'll draft on Monday, 

@mapineda let me know how you think that sounds.

**Comment by VictoriaODell** [comment]
Regular campaign scheduled for tomorrow to go out at 12 pm. 

[If you have anything to add ping me and write it here on the google doc.](https://docs.google.com/document/d/1E1QGjLEWObfBsTN6IXt1eNu6Dggmm_4W6emLbhllAFQ/edit)

**Comment by VictoriaODell** [comment]
SXSW Create Attendee email list wip. Should only be viewable by core team members: 
https://drive.google.com/drive/folders/0BxCjCqEUIrLFMVBRR19lN0luRG8?usp=sharing

**Comment by mateoclarke** [comment]
This is done, no?
