### ISSUE TITLE
Document Process for Requesting Data from City

### ISSUE THREAD

**Issue by hlupico** [open-austin/iced-coffee#234]
Documentation for the process of requesting data be published from the city/state may help volunteers in their project development process.

**Comment by amaliebarras** [comment]
Nice! Would you be down to open this up to the community? I think this deserves a project idea issue in itself, I feel like we've had data liberation stories in the community that members might want to help document.

**Comment by werdnanoslen** [comment]
@mateoclarke where can we find more info on this?

**Comment by VictoriaODell** [comment]
Discussed at our meeting with CTM. Still need a couple of answers. I made a comment in the doc linked below. 

> **Requesting data from the city**
> In their current sprint putting together a form to direct people to a seamless doc. 
> 
> - October 11th there should be updates
> - When there is a prototype it will be posted on bloomfire
> 
> 
> Current ways to request data 
> 
> - Email address 
> - Socrata portal 
> - Through the site/ help desk
> 



Notes here: 
https://docs.google.com/document/d/1TJbV7RNl940j5tZ-59146VEmzdvUVjyAckmRVB50WB4/edit?usp=sharing

**Comment by werdnanoslen** [comment]
Perfect, sounds like we can make something for our members this month

**Comment by VictoriaODell** [comment]
@sortizsh we need to follow up on this at the next CTM+ATA+OA meeting. They said it was in a sprint and there we some chatter at the Open Data meetup but idk where they are on this.

**Comment by VictoriaODell** [comment]
Followed up at the CTM+ATA+OA meeting this morning: 
https://cityofaustin.seamlessdocs.com/f/atxopendatarocks

Open Data. rocks getting updated by end of April before Socrata Connect event. This will house information for folks who are interested in using the Data Portal. 

CTM will Submit a talk to our library meetup once the portal support is ready.

**Comment by VictoriaODell** [comment]
https://cityofaustin.github.io/atxopendata.rocks/ is live and updated by @happinessk ! 

There is a button that says "suggest a dataset". I should add this to our 101.
