### ISSUE TITLE
Create Project Process Waffle

### ISSUE THREAD

**Issue by hlupico** [open-austin/iced-coffee#235]
Code for Denver has a really cool step during project creation where a waffle board for the project is pre-populated with project checkpoints for the volunteers to work towards and tasks to complete.

**Comment by amaliebarras** [comment]
Assigning myself to this one too so I can see what happens.

**Comment by hlupico** [comment]
I created a simple Google Map with location markers for the legal practices that offer help for 'Families and Kids' in Travis County. I will be sharing this with some of their employees. The thought behind creating this rough prototype is to keep the conversation rolling with State bar of Texas with respects to publishing data. 

https://drive.google.com/open?id=13HJbeq7AdPDg4xhvKkngqCWkv_k&usp=sharing

**Comment by VictoriaODell** [comment]
Is this still active? @amaliebarras maybe there is some help you can do with us remotely since you're in the area? 👀

**Comment by amaliebarras** [comment]
Yeah, once a CFD project reaches "official" status, they have a process for creating a waffle board for it. Does @werdnanoslen still want to do this?

**Comment by VictoriaODell** [comment]
I'm connecting with @werdnanoslen today. We can go through and look at some of the project to-dos. Def want to leverage any knowledge you have about what's working in Colorado though. :)

**Comment by werdnanoslen** [comment]
Not sure if Waffle is still the most important thing (hard enough to get people to use Github in the first place), but I did update the project idea issue template back in May https://github.com/open-austin/project-ideas/blob/master/ISSUE_TEMPLATE.md

That has steps for active and featured projects, too.
