### ISSUE TITLE
Document project management work

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#237]
I think our work on targeting project/process management is something worth documenting itself. I'm going to keep track of our Github artifacts in that vein through this issue. Other documentation will go on my Drive folder: https://drive.google.com/drive/folders/0B4TqIjcFtb4bZENhRl9VR0ZfQUk

**Comment by werdnanoslen** [comment]
### Related issues
#235 
#233 
#224 
#218 
#215 
#69

**Comment by werdnanoslen** [comment]
## The problem
Let's start by clearly defining the problem we have with managing projects, what are the fundamental challenges as well as more specific/circumstantial ones? Reply here or add to my [Google doc](https://docs.google.com/document/d/1mRtOigXNKyclprR0IJg6QL4z-vLRAB-ipSrNKUTi6Rk/edit#).

**Comment by amaliebarras** [comment]
I chatted about this with Hanna tonight, she should be touching base soon
about how to collaborate with ya on the PM process project
