### ISSUE TITLE
google calendar for delivery lead

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#239]
I'm going to attempt to do this for delivery lead tasks for the sale of tracking time

**Comment by hlupico** [comment]
@werdnanoslen @amaliebarras - I made a google spreadsheet to map out who can lead the Civic Hacking 101 at the Civic Hack Nights over the next two months. Maybe we could do this exercise every 2 months as projecting weeknight schedules out further than that can be tough.

Can you place your names next to the Hack Nights that you definitely CAN and CANNOT attend? Then we can discuss together who can take on any nights left over.
ttps://docs.google.com/spreadsheets/d/1vCI_uTPV5QlSIn7PTIG80KkwMD1zU52kmpXgQsmkFPI/edit#gid=0

**Comment by amaliebarras** [comment]
Finally added my info here
