### ISSUE TITLE
Let CfA know what projects are using AWS

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#240]
_From an email_
> Hi everyone, 
>
> If you’re getting this email it means that your Brigade is currently using Code for America’s AWS credits. I’d like to introduce you to John O’Duinn who is our new technology infrastructure manager at Code for America. We’re trying to get a sense of who is using our AWS billing and what for. Can you fill this out me what projects are using our AWS and who the point of contact for those projects are? 
> 
> Thanks so much, 
> Christopher Whitaker

https://docs.google.com/spreadsheets/d/1rvUf6coNlasBwYfyl7hQCMRVm2R-NGtkr1iej3DCmP8/edit#gid=0

**Comment by werdnanoslen** [comment]
related, I will check to see if IBM could provide bluemix credits as well

**Comment by werdnanoslen** [comment]
Are we using _their_ AWS or our own?

**Comment by luqmaan** [comment]
Open Austin has its own AWS account. But the billing is paid for by Code for America. You should be able to see this by logging into AWS and looking at the billing settings.

**Comment by werdnanoslen** [comment]
Are they still looking for this info, or are we square with them for now? I saw @mateoclarke  called them, but we're not on this spreadsheet (no idea if they're actually looking at the sheet anymore anyway)

**Comment by mateoclarke** [comment]
I just forwarded you an old email chain. I shut down some zombie instances on AWS and had a call with John O'Duinn to walk through things. After I did some proactive cleanup, he seemed happy with our monthly billing levels.

@werdnanoslen, I think it would be a good idea for you to reach out to him and let him know your managing our resources and refer some of your questions around usage to him. Let me know if you need me to make any intro.
joduinn@codeforamerica.org

**Comment by mateoclarke** [comment]
And I would suspect that the Google Doc is no longer up to date or actively being used.

**Comment by werdnanoslen** [comment]
will do, closing this now... thanks for the info!
