### ISSUE TITLE
project resource survey

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#241]
I'd like to get a survey of what resources project teams have considered important, including those they were lacking or missing. This'll give me a better idea of what exactly to look out for when connecting them with particular resources:  https://goo.gl/forms/0PGtzsfUWvW2IQRO2

**Comment by werdnanoslen** [comment]
Could y'all first look it over and let me know if it's balanced on comprehensiveness and length? If so, fill this out for any project teams at OA you've been a part of, and pass it along (or treat it as a structured interview guide) to other project leads?

**Comment by hlupico** [comment]
@andy - Looks great! I have two comments with regards to the resources form:

   1. Can you add examples of what types of resources you want more
   information about within each of the Knowledge, Skill, Tools and Techniques
   sections? I can see there being resources that could fall into more than
   one of these categories.
   2. Under Other Resources - What other resources have your team lacked
   that would be important? A time field appears as the form of input but I
   think the intention was for that to be an editable text field.

**Comment by werdnanoslen** [comment]
Ha thanks for catching the time field, dunno how that happened. And for #1,
I think that's ok since people may interpret the categories differently,
and I don't want to skew opinion with examples. If they can't think of
anything, I'll follow up with examples, though.

----
Andrew Nelson
andyhub.com
832-677-7180
(sent from mobile)

**Comment by amaliebarras** [comment]
Hey, I just filled this out. In my experience it was hard to answer "what would have helped" because oftem times you don't know what you don't know. I think this could be shorter and more anecdotal. 

i.e. 

**"To what do you attribute to your success?"** (skills, tools, techniques, etc.) 

**"What could have made you more successful"** (skills, tools, techniques, etc.)

**Comment by werdnanoslen** [comment]
cool, thanks. I'm mostly using this survey to inform a way to build future research artifacts like coding qualitative data and enumerating multiple choice questions.

**Comment by werdnanoslen** [comment]
Here's the results so far: https://docs.google.com/forms/d/1K0OyI75Edxzt5jYb-A2pq7P2QswySElHOvIcNrtQ1BE/edit?usp=sharing

**Comment by werdnanoslen** [comment]
So I analyzed resources in terms of knowledge, skills, tools, and techniques. Here's the results from the survey a while back:

### Knowledge
A wide variety of knowledge has been important to teams, from specific domain expertise to general project management skills. It seems it would be helpful to many if we made easily available some high-level knowledge about processes, whether that's about a project at OA or work at the city or how to set up a tech stack.

### Skills
The most commonly important skills are in programming, data analysis and cleaning, and UX design. These are very tech-centered, so it would be beneficial for us to continue allying with other technical organizations to share skills.

### Tools
Data storage and visualization tools are the most important, so it might be nice to host and record a night where we cover things like Socrata, CartoDB, ArcGIS, and others. Github is of course important, as we base many things on it (including this content). Finally, technical frameworks like Angular and Firebase are also quite common.

### Techniques
Data-related techniques are the most important, although project management and testing skills were also reported as techniques. As part of the skill sharing, we might run meetup crossovers where we ask folks to start by sharing some useful techniques in these areas and then try to foster longer-term relationships that ensure these gurus are accessible.
