### ISSUE TITLE
Create visual indicator for project cards

### ISSUE THREAD

**Issue by hlupico** [open-austin/iced-coffee#242]
If ideas in the project repo was marked with the visual indicator reflecting it's 'freshness' then we would have a quick reference to projects that have not been touched in a while without having to dive into the comments.

**Comment by hlupico** [comment]
assigning to @werdnanoslen as discussed on (3/28)

**Comment by werdnanoslen** [comment]
Ideas from slack convos, a few Github comments like https://github.com/open-austin/iced-coffee/issues/247#issuecomment-294170457, and chatting in person with @amaliebarras @hlupico @mateoclarke :

The `Abandoned and needs love` label should be removed and, for each issue it was applied to, replaced with at least one of the following:

- **Inactive**: Has no lead and no recent update
- **Backlog**: Has a lead or interested contributors but no recent update
- **External**: Has a lead and work is being done elsewhere

And in terms of freshness, new issues will get the `New idea` label for its first couple of weeks, `Active` labelled issues are kind of subjectively applied, and here are a few others than might help:
- **Prototyped**: Project has reached some form of "completeness" but there is likely more work to be done that may or may not ever happen.
- **Launched**: Project has a public presence.
- All other issues (probably >50%) won't have any freshness label

**Comment by werdnanoslen** [comment]
As documented in the [idea issue template](https://github.com/open-austin/project-ideas/blob/master/ISSUE_TEMPLATE.md), there are new, active, and featured projects. I think **External** isn't necessary, but having a sort of freshness label like **Inactive** and/or **Backlog** are important to indicate whether previous project members are active without the obligatory "hey is this project still happening?" post and likely non-response.

So, to simplify the previous post, here's the only change I'd make on this topic. For each idea that has an `abandoned and needs love` or `needs leadership` label or hasn't been updated in a long time (let's say 3 months):
- Label as `backlog` if it has advocates or a known OP/lead
- Label as `abandoned and needs love` if not, i.e. it's truly been abandoned

**Comment by werdnanoslen** [comment]
@VictoriaODell aligned on this, so now there are five labels in the ideas repo:

status: abandoned and needs love
status: backlog
status: new
status: active
status: featured
