### ISSUE TITLE
Lightning Talks for April 17

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#244]
⚡️⚡️⚡️⚡️⚡️⚡️ 
- [x] Sabine Romero- Open Government Partnership Update
- [x] Patrick McDonnell - Tactical Urbanism vs Open Source
- [x] Andy Nelson- Open Leadership
- [x] David Edmonson  - Austin Technology Alliance
- [x] Sarah Morris - Fake News, Web Literacy & Internet Health
- [ ] One more slot

**Comment by VictoriaODell** [comment]
done
