### ISSUE TITLE
Recent/Active Project Links for OA Welcome Page

### ISSUE THREAD

**Issue by hlupico** [open-austin/iced-coffee#246]
The Membership team has requested that we provide links to quick filter the Active/Recent projects for the OA Welcome Page (https://www.open-austin.org/welcome/)

**Comment by hlupico** [comment]
Active Projects Url - 
https://github.com/open-austin/project-ideas/issues?q=is%3Aissue+is%3Aopen+project+label%3A%22Active+Project%22

Beginner Friendly Url - 
https://github.com/open-austin/project-ideas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Beginner+friendly%22

New Ideas Url - 
https://github.com/open-austin/project-ideas/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3A%22New%20Idea%22%20

**Comment by seandellis** [comment]
@seandellis Need to add new links to Welcome page.
