### ISSUE TITLE
ATX Hack for Change To-Dos

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#248]
We're partnered with St. Eds and the city for this year's [ATX Hack for Change](http://atxhackforchange.org/) on June 2-4. 

Goals this year are to get 50 projects and 500 attendees. There is also a focus on keeping the work going through sister events. 

**We completed 2 workshops with them:** 
- [Hackathon 101 ](https://drive.google.com/open?id=1IPjXLLF0NoKQXIW5CluF2ujgKbttBzEKAEGSHov6rDI)
- [Hackathon Tech & Tools](https://docs.google.com/presentation/d/1BnYvgP3wUgfvk2bT7Ci8fby7OXfGU2n-EEJYe9oR-zo/edit?usp=sharing)
- I have some edits I want to make to the slides to make them more comprehensive for next year's presentation. 

**Other partner workshops**

- **April 19**
Topic: Coding 101  
Location: Devboot camp 
Trainer: Devboot camp

- **May 4**
Topic: Team Dynamics  
Location: WeWork  
Trainer: General Assembly + City of Austin

**Quick links**

- [Volunteer](http://atxhackforchange.us8.list-manage2.com/subscribe?u=f46435d8281132f2b2b4d0817&id=87df2e11f3)
- [Submit a project](http://atxhackforchange.org/projects)
- [Register](https://www.eventbrite.com/e/atx-hack-for-change-2017-tickets-32500276201)
- [social media calendar-UPDATED](https://docs.google.com/document/d/1Zh667EzmdnRV4UmO4SGo83hfiCi58TQWnkw4QCG4HNA/edit?usp=sharing)
- [Twitter](https://twitter.com/ATXhack4change)
- [March 31st Partner Meeting](https://docs.google.com/presentation/d/1-OWm2XmP5W5TneYIbnIzmsjYpH1QqolVDePVX5xfXy4/edit?usp=sharing)
- [Open Austin Hack 4 Change Google Drive ](https://drive.google.com/open?id=0BwKb2oghmQldYWtLWWhuNEIzaHM)

**Comment by VictoriaODell** [comment]
@hlupico "Could you give us a run down of what activities/announcements/visibility OA will have during the St Eds Hack for Change?"

So we had 2 activities. Aside from that, we're supposed to be listed as a partner on the site but it appears those changes aren't live yet. We are still talking mostly about promotional to-dos right now as we prep people with the workshops and get people to submit projects. 

During the actual event we should have the opportunity to plug OA like we did last year. Though we currently haven't gone over day of logistics. Our next meeting is going to be the 24th though and I can get more questions answered and suggestions made.

**Comment by VictoriaODell** [comment]
Meeting with the ATX Hack4Change crew in a few. I'll paste updates here.

**Comment by werdnanoslen** [comment]
H4C Last-minute planning for next civic tech night @ library

### Outcomes:
1. Existing project teams make a value proposal and potentially reframe 👇 
1. Others discover & frame problems via hack/open canvas

This is a note to self for now, I'll keep updating after I go through airport security

**Comment by VictoriaODell** [comment]
Confirmed Ashley will be joining us from the ATX Hack for Change team. 

@werdnanoslen the above looks good to me! lmk if you need help or want to do a working session to talk through what you're planning. I have some availbitly this Friday and on the weekend.

**Comment by VictoriaODell** [comment]
Meeting this Thursday with the H4Change team. We'll be posting flyers around town if anyone from @leadership is free sometime around 1-5pm to help out. :)

**Comment by werdnanoslen** [comment]
Main deck for tonight is here https://docs.google.com/presentation/d/1Q-IC3qSGMibqj2n3OMETKXnFOE34fKw_pTGNMpHyQd0/edit#slide=id.p
There are other decks, too, but they are from my studio and I can't share the files. I can't stop you from taking photos tho! ;)

**Comment by VictoriaODell** [comment]
Woo. Things are moving along .We'll have time to pitch Open Austin on Sunday. Here is the run of show. 

Sunday, June 4 
(this has changed slightly from information in packets) 
5:15 PM - Project Reports End
5:15 PM - Judges exit with Sarah Sharif to deliberate 
5:15 PM - Sister Events/Partners Pitch managed by Ashley DiStefano

(Each of you have 3 mins to pitch to the room about your idea/fund/initiative) 

Order: 
Open Austin 
Google Fiber 
CoA
Mozilla Foundation
U.S. Ignite
ATX Hack the Traffic 
Smart City Hack 

5:35 PM - Judges Award 
5:50 PM - Closing remarks from Ashley 
6:00 PM - Event Close 

I need to submit a slide by Tuesday for when we do an announcement. Would be best to talk to Core team about what we should specifically say during the pitch at our next leadership meeting.

**Comment by VictoriaODell** [comment]
Copy of event logistics
[Event Logistics- Partner Print out .docx](https://github.com/open-austin/iced-coffee/files/1046197/Event.Logistics-.Partner.Print.out.docx)

**Comment by mateoclarke** [comment]
🎉
