### ISSUE TITLE
Civic Hacker Summit interview

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#249]
We got contacted to do be a part of the Civic Hacker Summit. 
<img width="791" alt="screen shot 2017-04-14 at 1 19 04 pm" src="https://cloud.githubusercontent.com/assets/10767430/25051968/010b6c72-2115-11e7-8483-e7de350bd655.png">

### Here is the first message 

> Hello,
>
>I’m reaching out because I would love to feature a short video interview with a representative of your group in an online event I'm producing called the Civic Hacker Summit. It's a free virtual summit primarily focused on stories and strategies tied to using data and analytics for civic impact. Here’s a link to the event’s one-pager: https://drive.google.com/file/d/0B3G_C7hVyxOVNDNXRjgyV3RwYjA/view?usp=sharing
>
>Your participation would just involve pre-recording an interview with me any time before April 22nd. The interview will be pre-recorded at your convenience using Zoom, so we can include any slides or other visual aids you would like to present. Think of it as StoryCorps for civic hacking groups. =)
>
>Interested? The commitment is low - no travel! The experience is similar to being on a podcast, >but ultimately with greater exposure. 
>Please let me know if you are interested in speaking and I will follow up with further details. I look forward to your reply and will follow up with you soon.
>
>Regards,
>Lori McNeill
>https://www.linkedin.com/in/lmcneill/

### Here is the second
>Thank you for your interest in participating in the Civic Hacker Summit. The goal of hearing from you about Open Austin is to teach and inspire by example. I want to show off your success, share your strategies for gaining government and other partnerships, and help others overcome challenges you've already faced. Ideally your group will gain some new members and additional support in return for being so generous with your time!
>
>Please see below for some of the questions I'm thinking would be of most interest to this audience.
>
>If you'd like to proceed, the important next steps are:
>1. Please book a recording time that works for you here: https://calendly.com/lorimcneill/video-with-lori-60-min
>
>2. At your earliest convenience, please authorize usage of our recorded discussion and related content by completing the form here: https://civichackersummit.com/speaker-consent/
>
>3. To send me the head shot and biographical information you'd like to be published, please use this online form: https://civichackersummit.com/speaker-information-sheet/       
>
>We're going to aim for a 20-30 minute conversation. I want to make sure that we highlight any important points you wish to include, so please feel free to let me know if there's a topic you would like me to prioritize. Also, at the end of the interview, I will ask you if there are any upcoming projects or events you'd like to promote so that you have an opening to plug whatever you'd like. 
>
>Please let me know if you have any questions. Looking forward to talking with you soon!
>
>Thank you,
Lori McNeill
(408)781-6045
https://www.linkedin.com/in/lmcneill/
>
>**********************  SAMPLE QUESTIONS *********************
>
>1. How was your group formed, and how long ago?
>2. What are the different skills among your membership? What skills are people learning?
>3. What are the areas of greatest need right now for the group in terms of resources, volunteers, >or partners?
>4. How do you work with any government agencies, NGOs, private companies, etc.?
>5. What have been the biggest challenges in obtaining and/or working with open data?
>6. Walk me through one of the projects you have going on right now.
>7. Which of your projects would you say has had the most impact so far, or has the most >potential to have impact?
>8. How does your group decide what projects or issues to tackle?
>9.  What are some lessons learned or strategies you can offer to other civic tech groups looking >to form partnerships that further their work?
>10. What are some of your group's favorite "go-to" resources?

This seems like a cool opportunity to get some exposure. I'm intersted in checking the event out too. We can plug ATX hack for change and the upcoming Texas Data Demo Day. 

I can work to prepare slides, answer the sample questions, and schedule the interview for Friday, April 21st. 

@mateoclarke any thoughts?

**Comment by mateoclarke** [comment]
I think it could potentially be cool. I can't personally help with this right now though. Too much going on this month and I'll be out of town on 4/21.

**Comment by VictoriaODell** [comment]
Set up a time for Thursday at 10pm

**Comment by VictoriaODell** [comment]
I set up a time for today at 10pm. 

Link to the thing: 
https://civichackersummit.com/

I'll post some slides I make here in a few

**Comment by VictoriaODell** [comment]
The thing is live. 👀  @leadership maybe can dig out some cool stuff from some of the talks? I believe my account will still have access after the time limit is up so we can reference things in here at a later time too. 

https://civichackersummit.com/

**Comment by mateoclarke** [comment]
Seems like there is nothing left to do here. Going to close...
