### ISSUE TITLE
11/20 Presentation to CoA Data Liaisons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#25]
**Meeting Details: 12-2pm on Friday, Nov 20th at City Hall**

This will be an important presentation where we have a chance to help define what the deliverables are for the City's next  90-day-sprint. CIO Stephen Elkins and City Manager Marc Ott might both be in attendance

We've been asked to bring 3-4 Open Austin members that could take part in break out sessions with data liaisons during the second half of this presentation/workshop. 

- [ ] Make Slides for presentation @mateoclarke
- [ ] Find 3-4 volunteers to represent OA.

**Comment by mateoclarke** [comment]
@luqmaan, do you think you can attend?

**Comment by mateoclarke** [comment]
Some talking points for the presentation:
- Who is Open Austin. What do we do? What is our history?
- Code for America partnership
- Events overview
- Projects overview
- Past, present & future policy initiatives
- Type of relationship Open Austin wants with the City
- Things we'd like to see next:
    - List of newly liberated data
    - Open data inventory & directory of liaisons
    - Vision of an dedicated Public (not necessarily open) Data Team with a Chief Data Officer, unifyed with Business Intelligence Group
    - Tying department success and performance metrics to open data

**Comment by luqmaan** [comment]
Yes I'll be attending. Do you want to work on the presentation together?

**Comment by mateoclarke** [comment]
Yeah, let's take this to Slack to discuss if we should get together one night next week and/or collaborate on some slide over Google Docs.

**Comment by mateoclarke** [comment]
https://docs.google.com/presentation/d/1Kx3HFwkA2evt74OP1dCaGnF5BxhKcMQRiyzjRidB3Ik/edit?usp=sharing
