### ISSUE TITLE
Leadership Huddle - May 30

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#252]
_Thursday, May 30th, 7pm_
previous meeting #245 
### Agenda
- Reflection on first part of the year. 🌹 🌱 🗡 
- Discussion/preparation for ATX Hack for Change 
  - logistics, who is participating as hacker/project champion? what help is need?
  - how do we harness the momentum with new folks after the event?
- Finalize [Entity Formation doc](https://docs.google.com/document/d/1D6mhqrxokBCXG8g9I5XXKtBvUyjUCJS4_njqc1N9DVs/edit)
  - Mission
  - Values
  - [Organizational Objective](https://docs.google.com/document/d/1OujyBccPpepUXSY5_nP3alzvd81WlCKSeSf_-sU5K-U/edit#)
  - Membership status
- 🍻 Farewell drinks w/ Amalie after

Bike Rack:
- Austin Design Week
- WOW + National Day of Civic Hacking

**Comment by VictoriaODell** [comment]
Notes from the meeting: https://docs.google.com/document/d/15MpXUPennDrEvDgdlbbPSo_PengexjjxIKfZ9kd66ZI/edit
