### ISSUE TITLE
Automation integrations with Slack? 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#253]
There are a couple task that could be automated. Anymore? I know there are different ways to do these things so maybe we can post some different methods here? Talked to @seandellis about it today. 

- [x] Automate event volunteer message. Asking #iced-Coffee and people in #general if they are available and can help with any upcoming event. 
- [x] Automate Welcome message for anyone new to the slack.

**Comment by werdnanoslen** [comment]
Just set up automatic calendar updates a day before they occur to post on the announcements channel.

**Comment by werdnanoslen** [comment]
@seandellis set up the event volunteering message on the iced-coffee channel https://open-austin.slack.com/archives/C0GKYM1PG/p1504537209000248

**Comment by werdnanoslen** [comment]
Added Welcome message using Aloha
