### ISSUE TITLE
Leadership Huddle - July 6th

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#254]
_Thursday, July 6th, 7pm_
previous meeting #252 

### Agenda
- Update on Entity Formation from Finances Team
- Transitioning Leadership, updating the [snowflake](https://www.open-austin.org/assets/snowflake_model_2017.png)
- [Our Account w/ CfA](https://docs.google.com/spreadsheets/d/1ORwvp9rPOidH-bhTAfzSmUGWpi7AHOKyhrgCKZmkGKQ/edit#gid=0) & Fundraising:
    - Current Balance: $4,042.24
    - Income in 2017: $2,300 (Mozilla grant)
    - Expenses in 2017: $2,71.94
    - What would a fundraising campaign look like? When would it happen? 
- ATX Hack for Change
- Upcoming Events
   - 7/12 CHN
   - 7/17 OGCT Meetup
   - 7/26 CHN
   - 8/5 CHS
   - ...
- Open Government Partnership
- `codeforaustin.org`
- Budget Party Party
- [2017 Advocacy Agenda](https://docs.google.com/document/d/1ll7mp8XrJ5744WS2GUiBblh6mGQOnFN25n3Tkcxk4jY/edit)
- [Values](https://docs.google.com/document/d/1OujyBccPpepUXSY5_nP3alzvd81WlCKSeSf_-sU5K-U/edit#heading=h.cim3xllpxlwp), are these ready to add to the website?
- The other [internal projects](https://github.com/open-austin/iced-coffee/issues/213)
- Austin City Up

**Comment by mateoclarke** [comment]
https://docs.google.com/document/d/1Td9soDd6jFjBV-ovMt44WnUR4UVOBFkLkzX30sNqw0k/edit#

**Comment by mapineda** [comment]
Bylaws:
https://docs.google.com/document/d/1D6mhqrxokBCXG8g9I5XXKtBvUyjUCJS4_njqc1N9DVs/edit#
