### ISSUE TITLE
Write offboarding admin member documentation 

### ISSUE THREAD

**Issue by seandellis** [open-austin/iced-coffee#256]
What's needed to offboard admin members?

- Github
	- Remove Admin members

- Slack
	- Remove people from Slack groups and @ mentions

- Meetup
	- Remove admin members

**Comment by werdnanoslen** [comment]
Do you think this'd be a good entry to the wiki? https://github.com/open-austin/iced-coffee/wiki/Team-Roles-&-Responsibilities

**Comment by werdnanoslen** [comment]
Should also pair it with this https://github.com/open-austin/iced-coffee/issues/211

**Comment by seandellis** [comment]
Added to wiki: https://github.com/open-austin/iced-coffee/wiki/Onboarding---Offboarding-members-to-the-Leadership-team
