### ISSUE TITLE
Create form for members

### ISSUE THREAD

**Issue by seandellis** [open-austin/iced-coffee#257]
- link to form
	- benefits
	- google doc for page content
	- design
	- collaborate on Google Doc

**Comment by werdnanoslen** [comment]
@seandellis @VictoriaODell how's this going? Can I help?

**Comment by seandellis** [comment]
@werdnanoslen I'd love your help on this. 😃

Could you do the following:

1. Duplicate our existing [welcome form](https://docs.google.com/forms/d/e/1FAIpQLSd799C8EF7cCXmuSM9jfYPFSlPGPReFOao_GTaI58QD_w5FPg/viewform)
2. Use the relevant questions that are currently disabled.
3. Be sure that it puts the answers into either a new sheet in our existing [OA Membership form](https://docs.google.com/spreadsheets/d/1dghpcswCfUOsEnSKM6m-SM5-HHHaISDRFiAYU7RO2Kk/edit#gid=1952773302) or a new Google Sheet altogether.

I believe we settled on the term Active Member for members that would have voting rights. Somewhere in the messaging it would mention "Become an active member of Open Austin."

**Comment by werdnanoslen** [comment]
@seandellis it looks like that form is on your personal drive, not in the shared folder

**Comment by werdnanoslen** [comment]
got access, thanks @seandellis

**Comment by werdnanoslen** [comment]
@seandellis Let me know how this is:

Form: https://docs.google.com/forms/d/e/1FAIpQLScKIIY8uUmLaeK0SQb_qiNolfADyOx2r8v7D1pEWHKD4ekc6w/viewform

Responses: https://docs.google.com/spreadsheets/d/1dghpcswCfUOsEnSKM6m-SM5-HHHaISDRFiAYU7RO2Kk/edit#gid=694576777

**Comment by seandellis** [comment]
@werdnanoslen  This works great. Thanks!
