### ISSUE TITLE
Membership -> Bylaws

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#258]
@seandellis and I talked about this today! 
Review our agenda and notes here: 
https://docs.google.com/document/d/1P8wbVHkb8Df1LKXiiJjD1nwg1axKNqvhJ9noxe4_4OA/edit?usp=sharing

Bylaws here: 
https://docs.google.com/document/d/1D6mhqrxokBCXG8g9I5XXKtBvUyjUCJS4_njqc1N9DVs/edit?usp=sharing

Vickies notes here: 
https://docs.google.com/document/d/1P8wbVHkb8Df1LKXiiJjD1nwg1axKNqvhJ9noxe4_4OA/edit?usp=sharing

To-Do

- [x] Determine necessary information to be an affiliate member #257 // @seandellis + Me to create google doc
- [x]  Translate Vickie's Doc to bylaws and have it reviewed by Jon + Leadership at next monthly meeting // Me
- [x] Create affiliate form #257 // @seandellis 
- [ ]  Determine best/easiest way to create and update a "profile". Thinking Slack // Me

**Comment by VictoriaODell** [comment]
Issue #257 is for the affiliate form 📝

**Comment by werdnanoslen** [comment]
Membership no longer part of bylaws.
