### ISSUE TITLE
New Food at Hack Night? 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#260]
Hey, ya'll. We got a $100 donation from Expedition hack for this coming hack night on Wednesday. We usually get Chipotle for hack night and it's around $250 dollars. 

Chipotle cost about $230 for 10 chips & Guac and 72 tacos (Veggie, beef, sofritas, chicken) which is 2 tacos for 36 people or 3 tacos for 24 people plus the chips. The cost per taco is $2.16 which isn't bad.

+Add the cost of drinks and were at that $250 mark. 

Any ideas on how we might bring the cost down and introduce new food into hack nights? I think tacos are working for people for the most part. What makes them nice is the veggie and gluten free options too. Open to suggestions though. We discussed trying to order from local businesses too so any leads on that would be superb.

**Comment by werdnanoslen** [comment]
Tacodeli supports some local nonprofits http://www.tacodeli.com/commitment-to-quality-local-ingredients/community/

**Comment by VictoriaODell** [comment]
That looks super great but the cost per taco with their catering options ends up being $3.60 a taco and then we would get additional fees since we need them after they close. :/

**Comment by werdnanoslen** [comment]
Right, I meant this would be an option once we have an EIN. I'm also a huge
Pueblo Viejo fan, so I'm waiting on them to respond to my message with a
quote.

**Comment by VictoriaODell** [comment]
I see. Like as part of their donation thing and not actually ordering their catering? Def worth looking into once we have that. 

Same with Pueblo Viejo! I've been going there for years. Let me know when you get a response. though they seemed on the higher end too when I was perusing the web. Chipotle is chipotcheap.

**Comment by VictoriaODell** [comment]
I'm closing this out or now. Chipotle is working good and seems to be the cheapest + easiest for us right now.
