### ISSUE TITLE
August Open gov Meetup Speakers

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#262]
Hey, everyone, I believe we discussed having lightning talks this round. We should work to fill some spots

**When:** Monday, August 21st
**What:** We're hosting a lightning talk meetup. Should we have a theme? Does anyone have any thoughts on what we should cover? Might be interesting to have someone talk budget to us since we have Budget Party + it's Budget season. Or maybe someone from the innovation office to talk more about the OGP work they are doing. 

Each presentation should last 10 minutes + 5 minutes for questions each and we have our own announcements. 

Confirmed speakers:
- [x] Slot 1: COA- 2016 Mobility Bond Data & Resources | Aly Van Dyke, City Communications and Marketing Consultant & Zachary Ashburn, Data and Design Lead for the Corridor Program Office
- [x] Slot 2: Austin Montor- Ashley Fisher | Austin City Budget 101
- [x] Slot 3: Chris McConnell 
- [ ] Slot 4: TBD
- [ ] Slot 5: TBD

Here are some possible people to invite to speak: 
- [x] Ashley Fisher- Austin Monitor - City Budgeting 101 
- [x] Chris McConnell - GeoRodeo Presentation **Reached out to need to confirm** 
- [x] OGP partner from the City. Brion, Kerry, etc. 
- [x] Influence Texas team  **Reached out to need to confirm** 
- [x] COA Mobility Bond data sites  **Reached out to need to confirm** 

No's: 
- [x] Matt Carey - Policy Agenda with ATA. **Not this time around**

Need suggestions! Please comment below. :eyes:

https://www.meetup.com/Open-Austin/events/236698311/

**Comment by mateoclarke** [comment]
Ashley Fisher from Austin Monitor said she could do a quick hit on the Budget. Would be a run through of some charts and graphs on the City Budget. Let me know if you'd like me to confirm

**Comment by VictoriaODell** [comment]
@mateoclarke That would be great!

**Comment by VictoriaODell** [comment]
Someone from the COA will come to speak about 2016 Mobility Bond Data and resource. :)

**Comment by VictoriaODell** [comment]
@mateoclarke any word from Ashley? Also, thought it would be cool to get some OGP Updates too. I can bring this up in the meeting tomorrow. :)

**Comment by mateoclarke** [comment]
I'll confirm with Ashley. 

I'm pretty sure the OGP meeting for this month got cancelled. But you can come hang out in the Innovation Office anyways if ya want 😉

**Comment by VictoriaODell** [comment]
Hey thanks for confirming with Ashley @mateoclarke 

I had 2 thoughts for the last spot. We can do an OGP update or maybe invite the folks you worked with at Galvanize to get the twitter water quality bot thing running. lol I need to sync with you on that but since you kinda have a hand in both, any thoughts?

**Comment by mateoclarke** [comment]
yeah water quality would be cool and they already did a short presentation for their graduation. I can ask Jeff if he'd be interested.

After you left @VictoriaODell, I grabbed Daniel Honker and he was willing and ready to claim a 10 min spot. Some combination of us OGP folks in the City (Daniel, Sara Smith, me, Ginger or Brion in Equity Office) could report out on some of the specific projects. Might also be a good thing to invite Raymond, our IRM to.

Your call.

**Comment by VictoriaODell** [comment]
Hmm, OGP seems really relevant right now and if the team is willing I think it would be great to have them! 1. I can shoot an email and start to do some coordination or 2. You can coordinate and get some people in office to shoot me over what they're thinking for their spot and who will present. Would be good to know end of week.

I still would like to see more about the water quality bot though! Maybe we can Engage Jeff and team to write out a blog post or something?
