### ISSUE TITLE
Civic Hack Night Ideas

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#263]
Hey, ya'll. Here are a couple thoughts I've had about CHN Since visiting Code for D.C. Also, want to start the conversations so we can document our hack nights so they can become replicable. 

## Intros
Saw intros at Code for D.C. They do announcements and the leads give an intro on who they are but since they have over 20 people they skip roundtable type intros and replace that with name tags. Since about half the people there were with a project they already knew each other and jumped into working on projects. All new people went to a separate room where longer introductions happened.

I purpose that we try out the same or similar. This would mean having name tags at each meetup and we skip longer intros for larger crowds. If we have a smaller crowd then we can go for the roundtable like we've been doing. The main purpose of this would be to save some time on getting started and spend more time with the newbies. Newbies would still get Civic Hacking 101 like usual but also the longer intros and time for more discussion with each other. 

## Donation Jar
We tried this out at this past hack night and I think it worked okay. We got $6 dollars lol. But if we could start averaging like $10 every hack night that would be cool since it would cover drinks.

## Report Out
At the end of Hack Night Code for D.C. does a report out. Projects that are still working would take a moment to stand up in front of everyone and give an update on what they did. I think this would be helpful in catching up with what progress was made and if any help is needed moving forward. 

## Discussion/ Free work Group
Code for D.C. Had a group that was just for people that were working independently. They made sure people who didn't have a project sat together. This made for good discussion. We should consider formally having this. 

**Current Agenda**
6:30 - Grab food & chat with a neighbor
6:45 - Announcements 
6:55 - Project Role Call
7:00 - Intros
7:20 - Break out into smaller groups 

**New Agenda**
6:30 - Grab food & chat with a neighbor
6:50 - Announcements & Project Roll Call
7:05- Start Hacking // Civic Hacking 101
8:50 - Report Out 
9:00 Close up

**Comment by VictoriaODell** [comment]
The donation jar is working! Today we collected $10 and last time we collected $6. Not a whole lot but it counts.

**Comment by werdnanoslen** [comment]
Let's try the new agenda next hack night!

**Comment by werdnanoslen** [comment]
I'm trying the new agenda tonight

**Comment by werdnanoslen** [comment]
It seemed to work fine? There were about a dozen people there by 7:15, and only a couple were new so we just chatted one on one. I think it worked really well in this case since everyone seemed eager to get to work on their projects. Only thing we didn't do was report out, so next time we'll try that out. I'll go ahead and close this since they were great ideas that worked well in our own way.
