### ISSUE TITLE
2-3 Most successful projects to date

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#264]
We received this message on Meetup. It might be nice for us to define these and have some numbers or a quick blurb on projects that have been particularly successful. The [projects page](https://www.open-austin.org/projects/) is a start but I'd like to narrow in on a couple and really define a good story for them that is easy to tell. 

So open thread/discussion on this.
```
Hi,

I’m Tom Bayer, a volunteer with Code for Denver(CfD). We are doing an informal survey of Code for America(CfA) brigades in an effort to generate project ideas for CfD and share the survey results with the CfA network.

We would like to compile what individual brigades feel are their two or three most successful projects to date.

As a starter, among CfD’s most successful projects to date have been:

•    Fresh Food Connect(FFC)

Webpage: http://www.freshfoodconnect.org/
Github: Project taken private, only outdated versions available

With FFC, if you have extra produce, you can schedule pickups via the FFC web-app. The FFC team will pick up the produce on bicycles and then distribute it in local neighborhoods facing food insecurity.

•    Cute Pets Denver

Twitter: @CutePetsDenver
Github: https://github.com/codeforamerica/CutePetsDenver

A twitter bot that posts a random adoptable pet from Denver’s animal shelter.

•    Owlet

Webpage: http://owlet.codefordenver.org
Github: https://github.com/codefordenver/owlet-ui

A curriculum website that guides middle school students through a diverse array of creative technology skills and houses a growing library of resources.

If you would like to share a bit about your brigade’s most successful projects, that would be fantastic and greatly appreciated! You can simply respond to this message.

Thank you.

Tom Bayer
Code for Denver Volunteer
```

@wilsaj mentioned our more recent projects AppleSeed and Budget Party.

**Comment by VictoriaODell** [comment]
@mateoclarke mentioned the Park Equity map and Texas appleseed today in conversation too.

**Comment by werdnanoslen** [comment]
Is this the same as https://github.com/open-austin/iced-coffee/issues/194?

**Comment by VictoriaODell** [comment]
Relevant! I think we can update the list with more recent projects though. I followed up the CfD to see if they still had a need.  

Closing #194 and we can continue the convo here and 


https://docs.google.com/document/d/1lMzjlCpNQs9N6v0VT7iLk_0tSGDZ0Cj86bmMHXAyFjc/edit?usp=sharing

**Comment by werdnanoslen** [comment]
How about we just replace Instabus with Budget Party?

**Comment by werdnanoslen** [comment]
The CfD thing passed, but I've replaced Instabus with Budget Party here: https://docs.google.com/document/d/1lMzjlCpNQs9N6v0VT7iLk_0tSGDZ0Cj86bmMHXAyFjc/edit?usp=sharing

The doc is in our Drive, so it's there when we need it. Is there anything to do with this for now, though, or can we close this issue?
