### ISSUE TITLE
Slack channel names

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#265]
I recently worked to archive inactive channels from the Open Austin slack. I did this so new and existing slack members could easily find channels that are of interested to them. 

I think another step we can take to better organize the Slack is by starting to have some indicator of what is a project channel versus a general topic channel. This can help people see what channel might be more relevant to them when browsing. Another option is to keep a published list of what each slack channel is. I'm sure there are other solutions but I think we should pick one and implement before the next hack night which should be next Tue/Wed

@werdnanoslen Can you pick or come up with something that you think would be effective and easy to implement? If we don't want to disturb any current channel names then making the list might be easiest.

**Comment by werdnanoslen** [comment]
[Posted to Slack](https://open-austin.slack.com/archives/C036FLME2/p1502662067240696)

**Comment by werdnanoslen** [comment]
9 :+1: and 1 :-1:, so I'll go ahead and change these all with another `#general` announcement

**Comment by werdnanoslen** [comment]
Oh apparently I'm not a Team Admin. @VictoriaODell can you help me out?
