### ISSUE TITLE
Stream/record CTNs

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#266]
I have received requests from people about recordings of our civic tech nights as well as streaming. I've streamed a library CTN before for one person via Hangouts, but it would be nice to stream it regularly so that folks in other cities or are otherwise unable to attend still be able to learn about what Austinites are doing in civic tech.

Another opportunity is in documentary shorts of what civic tech means to people and how they do it. I think the easiest way to get started would be to record CTNs or use Hangouts to easily both stream and record to Youtube. Another possibility is for @mateoclarke to find a way to find a way to record for play on local public access channels.

**Comment by VictoriaODell** [comment]
closing until we have a comms or events lead. We should work to create descriptions of what is needed to run.
