### ISSUE TITLE
Final Bylaws Review 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#270]
This came out of our August leadership Huddle #261. [Based on our survey](https://docs.google.com/spreadsheets/d/18UcIvYIA7-if9vrcqQA-xrvZXidvnPqi4P9UEE7fzy4/edit?usp=sharing) a majority of leadership believes we should continue with incorporation.
<img width="500" alt="screen shot 2017-09-01 at 9 38 24 pm" src="https://user-images.githubusercontent.com/10767430/29992297-08382992-8f5e-11e7-9464-4d70989442c3.png">

There are[ quite a few comments to close out for the bylaws](https://docs.google.com/document/d/1pnBIesByEAe0tUU4OhjVR7UisLKRtCpTiYmQ0IK0JLU/edit#). Let's dedicate a 1.5 hour time slot to reach consensus and get comments resolved so we can move forward. Let's coordinate, @jonplaca, @mscarey, & @werdnanoslen. @danielryne and @seandellis since ya'll marked either unsure/no then I think it's important that ya'll consider coming or letting us know any additional concerns. 

By the end of this session, we should have closed out the comments and have a completed doc. 

**Doodle Poll here:** [https://doodle.com/poll/4fp52cps27vs4gx6](https://doodle.com/poll/4fp52cps27vs4gx6
) 
**Doodle Poll Dates:** 
- Sept 
- Tue 5
- Thu 7
- Fri 8 
- Mon 11
- Wed 13
- Thu14

**Note:** I didn't include weekends in the Doodle poll for the 9th/10th. If no other time works but folks have some flexibility there then we can try to schedule then. But I'd prefer we make a week day work. :)

**Comment by VictoriaODell** [comment]
We chose this coming Friday, September 8th at 6-7:30pm but need a location. 

<img width="286" alt="screen shot 2017-09-04 at 11 10 24 am" src="https://user-images.githubusercontent.com/10767430/30033592-b12ececa-9161-11e7-94ba-7ac1e904a220.png">

**Comment by werdnanoslen** [comment]
My place is open as usual. We can meet out by my grill/pool and I can cook
for us. This many people a cafe probably wouldn't work well, but maybe a
dinner type place or brewpub would work if y'all wanna go out.

**Comment by werdnanoslen** [comment]
Issues we might be able to update if not close:

- [ ] https://github.com/open-austin/iced-coffee/issues/215
- [ ] https://github.com/open-austin/iced-coffee/issues/210
- [ ] https://github.com/open-austin/iced-coffee/issues/258
- [ ] https://github.com/open-austin/iced-coffee/issues/257
- [ ] https://github.com/open-austin/iced-coffee/issues/229
- [ ] https://github.com/open-austin/iced-coffee/issues/230
- [ ] https://github.com/open-austin/iced-coffee/issues/216

**Comment by werdnanoslen** [comment]
Finished reviewing bylaws, next steps are covered in #216 to incorporate
