### ISSUE TITLE
Leadership Huddle - September

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#273]
**Location:** Andy's place (301 Brazos)

**Time:** 6-8pm

**Date:** Sep 28// [Doodle Poll CLOSED](https://doodle.com/poll/rufx3xki6ma2shkx)

[Agenda// WIP// Add to it as needed 
](https://docs.google.com/document/d/13O4dd_mzJrCUTFEOcRrDZkyN3kgLV_eI7xZRhKz5d7c/edit?usp=sharing)

**Comment by VictoriaODell** [comment]
@leadership, let's pick a time for our huddle for the last week of this month: 
https://doodle.com/poll/rufx3xki6ma2shkx

**Comment by werdnanoslen** [comment]
Everyone responded yay! Let's meet at my place Sept 29 from 6-8pm. As usual, let me know if you want one of my two parking passes. Or if you wanna meet somewhere else, please respond. Also don't forget to add agenda items!

**Comment by VictoriaODell** [comment]
I messed up and Javier's show is September 29th. Any way we can pick another date? 😅

**Comment by VictoriaODell** [comment]
@jonplaca do you have any flexibility for the 28th or the 25th?

**Comment by werdnanoslen** [comment]
I've actually already committed to something Monday (25) and Tuesday (26)...

**Comment by VictoriaODell** [comment]
Ok. Well looks like this one will have to go on without me. I'll be sure to put my notes and updates in prior to the meeting.

**Comment by werdnanoslen** [comment]
Unless @jonplaca can do 28th?

**Comment by jonplaca** [comment]
This works for me

**Comment by werdnanoslen** [comment]
Let's pull out action items from the agenda and make issues now. Add them as next month milestone

**Comment by werdnanoslen** [comment]
Made/commented on issues with action items from the huddle. Closing...
