### ISSUE TITLE
Core team wiki docs

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#274]
Hey, Everyone. We mentioned starting to do this at our last leadership meeting and @werdnanoslen  got us started and created a [projects wiki page](https://github.com/open-austin/iced-coffee/wiki/Projects). Let's use this as a template and commit to getting our daily, weekly, and monthly task filled out. Getting a couple of bullets under each section is all that we need to get started. What you write is unique to what you do in relation to your [role](https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit?usp=sharing). 

- [ ] Policy @mscarey 
- [ ] Event @mapineda 
- [x] Marketing me
- [ ] Finances @jonplaca 
- [ ] Membership @seandellis 
- [ ] Captain me/ @werdnanoslen 

You can also add links to docs you use or reference frequently to do your role. The [events page](https://github.com/open-austin/iced-coffee/wiki/Events) has some stuff filled out for reference. 

Ask questions and get help by reaching out to @werdnanoslen or me here or on slack. It would be great to have an update at our [September leadership meeting](https://github.com/open-austin/iced-coffee/issues/273).

**Comment by werdnanoslen** [comment]
From our [leadership huddle](https://docs.google.com/document/d/13O4dd_mzJrCUTFEOcRrDZkyN3kgLV_eI7xZRhKz5d7c/edit#heading=h.ffax9i2or415): Others have also expressed interest in joining leadership but haven’t yet really followed through on contributing. Let’s keep them engaged and try to find ways of onboarding them to some tasks, like documenting what we do so we can easily delegate a task or two to folks interested in helping out.

**Comment by VictoriaODell** [comment]
I'm going to work on getting basic docs made this Friday/weekend.

**Comment by JMensch** [comment]
@open-austin/leadership IMO reviving this makes sense if we don't have up to date roles and responsibilities docs (based on the roles we _need_, not what we want). Thoughts?

**Comment by VictoriaODell** [comment]
@JMensch Maybe we can just take the info off wiki docs and put it in a google doc folks can add to and edit? That's something I can help with.

**Comment by mateoclarke** [comment]
Seems like there is still a need for this especially given what we've discussed in our recent leadership syncs about having better clear expectations for contributing.

**Comment by JMensch** [comment]
Closing in favor of https://github.com/open-austin/iced-coffee/issues/367
