### ISSUE TITLE
Source potential event partners

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#275]
As we start planning for future events, we should consider who we can work with more closely to create stronger programming with pooled resources. I started to document local organizations in the below google doc. Please add notes + entries as needed. This will help us with 2018 planning and calendaring out our year. 

https://docs.google.com/document/d/1uOyYMt2nzSWH_tXpAK_EZNUJ4SirnPpmTa_v37g2pqw/edit?usp=sharing

@werdnanoslen this is from our discussion today. Let me know if this works or if another format may be better.

**Comment by werdnanoslen** [comment]
I added this to the [events wiki](https://github.com/open-austin/iced-coffee/wiki/Events). Is there anything we need to update for this? Or can we close this and make it maybe a monthly task to update the list with any new leads and remove cancelled partnerships?

**Comment by VictoriaODell** [comment]
@werdnanoslen monthly task sounds good! 

@mapineda thoughts?

**Comment by mapineda** [comment]
@VictoriaODell @werdnanoslen  I'm good with monthly task.

**Comment by werdnanoslen** [comment]
Cool I'll just crossref this with the wiki issue #274 and close
