### ISSUE TITLE
notify slack about emails to OA addresses?

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#276]
To promote visibility and timely discussion around emails to us, should we post the content or subject of emails to our [team]@open-austin.org addresses to a Slack channel like #iced-coffee or #coreteam?

**Comment by VictoriaODell** [comment]
I would say let's test it out in #iced-coffee. If it's too much then we can put it in another channel.

Also, #coreteam isn't used very often, we should consider its purpose. There isn't a lot of chatter in there and some of it could have been in #iced-coffee.

**Comment by werdnanoslen** [comment]
How about on the comms channel?

**Comment by werdnanoslen** [comment]
done, routed to #coreteam
