### ISSUE TITLE
Location + partners for 2018 

### ISSUE THREAD

**Issue by mapineda** [open-austin/iced-coffee#277]
Discussion about securing long term location partnership agreements with certain organizations. 

Ex:

- Galvanize
- St. Ed's 

Questions to spur discussion:
* What value do we offer the potential partner?
* What does the partner gain? ( concrete numbers )

Potentially expand upon sponsorship prospectus from Code Across 2016 
https://goo.gl/CtC3XZ

**Comment by VictoriaODell** [comment]
Here is a doc that I started too : https://docs.google.com/document/d/1uOyYMt2nzSWH_tXpAK_EZNUJ4SirnPpmTa_v37g2pqw/edit?usp=sharing

**Comment by werdnanoslen** [comment]
Dropping a reminder here for @mapineda from the leadership huddle to to try to get with the booking person at the new library by their grand opening on Oct 28th 1-6pm. We should also confirm whether they're going to charge for that kind of thing, but maybe they'd reconsider for a nonprofit?

**Comment by werdnanoslen** [comment]
Could we keep this all in one issue like #287 ?

**Comment by VictoriaODell** [comment]
Closing this since we seem to be doing fine chatting on this in slack and & our event issue thread
