### ISSUE TITLE
Gigabit Funding for Open Austin 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#279]
I met with Charles Purma from CTM last week and heard we got some allocated funding to support gigabyte activites. [View my notes from the meeting](https://docs.google.com/document/d/1c020XQinMJAekKPkPXhY8wRPzP6PiY0hdBn3WFmprlk/edit?usp=sharing). 

> Hi Vickie and Andy -- It was great chatting with you this morning! As I mentioned, we have set aside $200 of our US Ignite funding per quarter to support Open Austin Meet-ups, hackathons, and other events/efforts that will promote the smart city gigabit ecosystems and encourage collaboration with our application/solution development teams and the civic tech and non-profit community over the next two years. In fact, we have $400 that we have not spent since it’s taken a little bit longer than planned to get ramped up.
>  
> Quarter 1 Year 1 (Apr -Jun 17): $200
> Quarter 2 Year 1 (Jul-Sep 17): $200
> Quarter 3 Year 1 (Oct-Dec 17): $200
> Quarter 4 Year 1 (Jan-Mar 18): $200
> Quarter 1 Year 2 (Apr-Jun 18): $200
> Quarter 2 Year 2 (Jul-Aug 18): $200
>  
> Please let me know when you’d like to talk more about how best to leverage this money.
> 
> 

Would love feedback and ideas from leadership on how to spend this funding. This might be something good to inform the community of for feedback also. 

A few things to note: 

- This money can't be spent on food
- We need to respond in a timely manner/ before October at least to talk about use of funds.

**Comment by werdnanoslen** [comment]
From Slack, Marco and I are interested in using this to secure venues when necessary, such as if a venue backed out last minute and we need to pay for a room somewhere like Capitol Factory or General Assembly.

As far as projects go, perhaps we could use it to book a class or tech guru for a select team as a reward.

Or perhaps it could go toward buying books to really jump-start Chris' book club by giving folks the books to read.

**Comment by VictoriaODell** [comment]
Slack thread on spending also in #iced-coffee: https://open-austin.slack.com/archives/C0GKYM1PG/p1505881945000044

**Comment by werdnanoslen** [comment]
Vickie's going to check our finances to figure out what we need and what the exact rules are for what we can use Ignite money for.

**Comment by VictoriaODell** [comment]
Notes from the meeting with CTM 

> **Gigabyte funding**
> 
> - Don’t have to spend money in a set amount of time
> - The city likes things broken down in milestones and deliverables
> - We don’t have to spend the money in a specific quarter. 
> - CTM wants to make sure we do spend that money and start spreading it around to people
> - Get approval for purchase/ invoice then send to TARA. CC/ CTM. 
> - Tara handling contracts/ paying people and reporting
> - Happiness and Charles handling project management. 
> 
> Process for spending
> - We can talk about the spending at the kick-off meeting. 
> - Logistical stuff
> - spending/contracts/ reporting - point of contact 
> 

**Link to notes:** 
https://docs.google.com/document/d/1TJbV7RNl940j5tZ-59146VEmzdvUVjyAckmRVB50WB4/edit?usp=sharing

The meeting they mentioned where we would get more info is this Tuesday at the  City of Austin and US Ignite Community Kickoff Meeting
<img width="450" alt="screen shot 2017-10-05 at 4 24 41 pm" src="https://user-images.githubusercontent.com/10767430/31253270-cd50b8f2-a9e9-11e7-92d0-7e3d2d7a9f0a.png">

**Comment by werdnanoslen** [comment]
@VictoriaODell if you want us to join that meeting too, could you please add it to the Open Austin calendar?

**Comment by werdnanoslen** [comment]
From Charles on Oct 16:

> **$1,200: Open Austin Meet-ups and Hackathons** – We will partner with Open Austin (Austin’s Code for America Brigade) to support meet-up and hackathon events to promote the smart city gigabit ecosystems and encouraging collaboration with the civic tech and non-profit community on the projects over next two years. The funds will cover promotion and materials used during the events such as paper products, pens, and other utilities with an expected distribution as follows:
> Quarter 1 Year 1 (Apr -Jun 17): $200
> Quarter 2 Year 1 (Jul-Sep 17): $200
> Quarter 3 Year 1 (Oct-Dec 17): $200
> Quarter 4 Year 1 (Jan-Mar 18): $200
> Quarter 1 Year 2 (Apr-Jun 18): $200
> Quarter 2 Year 2 (Jul-Aug 18): $200
>  

We should let him know when we have ideas on how to best leverage this funding and we’ll coordinate from there.

**Comment by VictoriaODell** [comment]
@werdnanoslen I don't know when it's appropriate to share events with individual people versus the organization. The organization calendar goes out to everyone that subscribes to our calendar.

**Comment by werdnanoslen** [comment]
True, it'd be better to just have the open-austin@gmail.com account to join these calendar invites so that everyone in leadership can sync just that calendar
