### ISSUE TITLE
Schedule 2016 Hack Nights

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#28]
- [x] WeWork Tuesday
- [x] Saturday
- [ ] Test run for somewhere in central/north austin

**Comment by luqmaan** [comment]
Saturdays:

**Comment by luqmaan** [comment]
Thoughts on something like this?

```
- Mon Jan 11 - Library
- Wed Jan 13 - WeWork
- Sat Jan 30 - Urban Co-Lab
- Tue Feb  2 - WeWork
- Sat Feb 13 - Urban Co-Lab
- Mon Feb 22 - Library
- Tue Mar  1 - WeWork
- Sat Mar 12 - Urban Co-Lab
- Mon Mar 21 - Library
```
For January we'd have our first meetup on Jan 11 and first hack night on Jan 13. I think we should do this because:

- First week of January will be too quiet
- Third week of January will be too late for our first hack night

**Comment by amaliebarras** [comment]
Two in one week is a lot but as long as it's just to kick off the year I think people will understand.

**Comment by mateoclarke** [comment]
Thanks for starting this @luqmaan. I don't think the starting on Tuesday the 5th at WeWork would be a bad idea. If it were the first Monday back after a holiday it might be harder. Two events in one week would definitely steal attendance from each other. I think the best January schedule would look something like

```
JAN
- Tue Jan 5 - WeWork
- Mon Jan 11 - Library
- Sat Jan 23 - Urban Co Lab
```

February looks good. But two things to be aware of in March. CfA's Code Across is March 5th. I'd like to plan to do our event that Saturday too. Also SXSW Interactive is March 11-16. It might be cool to host a hack night or social during that time but also it'd be fine to bunker down and avoid it.

```
MARCH
- Tue Mar  1 - WeWork
- Sat Mar 5 - Code Across
- SXSW March 11-20
- Sat Mar 12 - Urban Co-Lab
- Mon Mar 21 - Library
```

Also open to trying out IBM or something else up north on a Thursday night.

**Comment by luqmaan** [comment]
Good points. Let's just go with jan 5.

**Comment by luqmaan** [comment]
We've booked the WeWork hack nights for Jan, Feb and March in the new boardroom.

Tuesday January 5
Tuesday February 2
Tuesday March 1

**Comment by luqmaan** [comment]
Scheduled the WeWork hack nights on Meetup.com and the Open Austin Google calendar.

**Comment by mateoclarke** [comment]
Closing this out and starting a new thread
