### ISSUE TITLE
Ask CfA about any issues with becoming a nonprofit

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#280]
Follow up with CfA about what happens (1) when we are recognized by Texas as an unincorporated nonprofit and then (2) when we are recognized by the federal government as tax exempt and then (3) when Texas recognizes we are a 501c3 tax exempt nonprofit corporation.

**Comment by werdnanoslen** [comment]
Started a convo with Chris Whitaker on the CfA Slack #brigade-501c3s channel: https://cfa.slack.com/archives/C2N48MEHL/p1506953510000228

**Comment by ErieMeyer** [comment]
Hallo! Subscribing myself for this conversation. For context, are you already committed to becoming a full 501c3 or you're considering it?

**Comment by werdnanoslen** [comment]
👋 Welcome! We're quite committed https://github.com/open-austin/iced-coffee/issues/216

**Comment by ErieMeyer** [comment]
Gotcha! I'm checking that out now, too. Thank you!

**Comment by werdnanoslen** [comment]
Re: #3 that's basically the end of our legal relationship to CfA, we're then our own thing and only affiliated with them. All financial ties are cut other than what would be normal business between other 501c3 orgs. Vickie and I learned more at the Brigade Congress, but I think this is enough info to close this issue...
