### ISSUE TITLE
set goals to accomplish advocacy agenda items

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#282]
set specific actionable goals and events to accomplish policy items set in our [Advocacy agenda](https://docs.google.com/document/d/13O4dd_mzJrCUTFEOcRrDZkyN3kgLV_eI7xZRhKz5d7c/edit#)

**Comment by VictoriaODell** [comment]
Today Jeff Senk suggested a separate repo to house advocacy items  and ideas. I think I talked with @mscarey about this before.

**Comment by VictoriaODell** [comment]
P sure this was for old agenda items. We haven't had a policy lead and not much is happening to push our agenda forward right now. @mscarey has done occasional updates via post and presentation which I think is fine for now. Coming up with what/ if we have advocacy agenda items for 2019, is another item.
