### ISSUE TITLE
Leadership Huddle - October/ November

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#284]
[DOODLE!](https://doodle.com/poll/9mteiesyuc7i32dy)

**Location:** TBD

**Time:** TBD

**Date:** TBD

[Agenda// WIP// Add to it as needed 
](https://docs.google.com/document/d/1XWEMZL8mXxiaBKhRh8O-fUR6lIbthQDxnhPOT61D1Ng/edit)

**Comment by VictoriaODell** [comment]
Hey, @werdnanoslen can you make and post a doodle? Worried we're cutting it close.

**Comment by werdnanoslen** [comment]
Oh snap yeah, forgot to come back to this one. Here's the Doodle: https://doodle.com/poll/9mteiesyuc7i32dy

**Comment by werdnanoslen** [comment]
Ok, we don't have a good time that brings more than four of us together. I also apparently can't edit the poll :(

So let's try this, edit this post with your name next to these other evenings you're available:
- Nov 1
- Nov 2
- Nov 3
- Nov 4
- Nov 5

**Comment by VictoriaODell** [comment]
@mapineda made a doodle poll for us and we chose Saturday, November 11th from 2-4:00pm 
https://doodle.com/poll/sp6inzw3dgfstaeq

**Comment by VictoriaODell** [comment]
We had our huddle at the new library! 

Meeting notes: 
https://docs.google.com/document/d/1XWEMZL8mXxiaBKhRh8O-fUR6lIbthQDxnhPOT61D1Ng/edit?usp=sharing

New issues were made from the action items.
