### ISSUE TITLE
Financial Planning/ Model

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#286]
I created this very crude sheet that has our current spending and how much we have left in the bank with Code for America. It def needs some love. 

Here is the breakdown of the sheets 
- 2017 Expenses. Has all of our expenses thus far. 
- By the numbers. Has our spending broken down monthly 
- Spending. Estimated expenses for the year, upcoming expenses, and some nice to haves for the org that would require spending $$.

https://docs.google.com/spreadsheets/d/13yTcEDH-_XsO1erytDJiFceCLrbXtfF8RQxHN6meiUM/edit?usp=sharing

**Comment by jonplaca** [comment]
@VictoriaODell What other SaaS Services do we use (or would like to use):

Google
Buffer
Meetup.com
_______ Other

**Comment by jonplaca** [comment]
WIP: 

https://docs.google.com/spreadsheets/d/1f4F_MhBe-xa0O50oxKQqBDY28iTjfoKZDlvJLR0p6uU/edit?usp=sharing

@victoriaodell - I filled in some basic information regarding our SaaS Costs (speculative), Meal Cost (based on historical expense), and then some buffer-room ($150 additional expense/month). 

NOTE: I've also included our current financing ~$3k to account for our current Cash. 
For practicality, I assumed this budget will take effect in 2018. However, in the real world - this budget would be occurring ASAP. 

We'll need to sit down together to determine which SaaS services we'd like to have and what other events we can expect by the end-of-the-year. This will help formulate a stronger budget moving forward.

**Comment by VictoriaODell** [comment]
This spreadsheet looks fancy @jonplaca. 

This would be related to #230, correct? Should we close this issue and continue over there?

**Comment by VictoriaODell** [comment]
Also, have some of those expenses you mentioned documented on this sheet: https://docs.google.com/spreadsheets/d/13yTcEDH-_XsO1erytDJiFceCLrbXtfF8RQxHN6meiUM/edit?usp=sharing

I probably need better sheet practices 🙃

**Comment by jonplaca** [comment]
@VictoriaODell Thanks for the added info.
Regarding our expenses, let's sit down next meeting and discuss in more detail. We should discuss upcoming major events. 

Similarly, we can budget in "nice-to-have" expenses so that we can understand our maximum expense availability

**Comment by VictoriaODell** [comment]
Sounds good. Do you have time this Friday? Maybe in the am? Lmk if that works. Also ccing @werdnanoslen

**Comment by jonplaca** [comment]
I am available at 9:30am - 10:30am this Friday, 10/20.
Happy to meet at a location of your convenience

**Comment by jonplaca** [comment]
To streamline our meeting, I would suggest coming up with a few ideas/events that you'd like to have in Q4 2017 and 2018. From here, I'll pull these into the Financial Model which should dictate our fundraising goals. 

@VictoriaODell @werdnanoslen

**Comment by VictoriaODell** [comment]
Sent a calendar invite for this friday 9:30am-10:30am at Cenote

Also as far as events, we currently have the same schedule as this past year, though our event model might change.  @mapineda is starting to place calendar dates for events here: https://github.com/open-austin/iced-coffee/issues/287

I'll try to calendar out some additional partner events that might come up before Friday.

**Comment by werdnanoslen** [comment]
We have secured funding from the city for certain items:

> $1,200: Open Austin Meet-ups and Hackathons – We will partner with Open Austin (Austin’s Code for America Brigade) to support meet-up and hackathon events to promote the smart city gigabit ecosystems and encouraging collaboration with the civic tech and non-profit community on the projects over next two years. The funds will cover promotion and materials used during the events such as paper products, pens, and other utilities with an expected distribution as follows:
> Quarter 1 Year 1 (Apr -Jun 17): $200
> Quarter 2 Year 1 (Jul-Sep 17): $200
> Quarter 3 Year 1 (Oct-Dec 17): $200
> Quarter 4 Year 1 (Jan-Mar 18): $200
> Quarter 1 Year 2 (Apr-Jun 18): $200
> Quarter 2 Year 2 (Jul-Aug 18): $200

We should let him know when we have ideas on how to best leverage this funding and we’ll coordinate from there. See https://github.com/open-austin/iced-coffee/issues/279 for more info

**Comment by werdnanoslen** [comment]
@VictoriaODell what's left on this to-do? Or is there another issue that covers the next financial planning steps?

**Comment by jonplaca** [comment]
@werdnanoslen - @VictoriaODell and I met up yesterday and got a rough outline of all the services we would like/currently use. As a result, we were able to determine a rough budget and fundraising target for 2018.

I still have to research and add one-time expenses (e.g special events we throw/attend), but this will require more discussion.

If you have a list of 2018 events you'd like to attend, please msg me

**Comment by jonplaca** [comment]
Closed

**Comment by jonplaca** [comment]
Merged with #230
