### ISSUE TITLE
Create community events calendar

### ISSUE THREAD

**Issue by mapineda** [open-austin/iced-coffee#288]
**Goal: Increase community outreach**

Idea: Catch all community events calendar to show events around town that coincide with our mission, vision etc. 

Examples: Upcoming hackathons, civic tech events, talks, smart city, happy hours, kids + coding education, latinitas, etc

**Comment by werdnanoslen** [comment]
How about we add them all to our OA Google calendar? That way they're automatically announced (and reminded 24 hours before) on the #announcements channel, and then it's easier to take a snapshot of that one source when building meetup agendas.

**Comment by werdnanoslen** [comment]
There's probably a good way to automate this, but we should curate the calendar and not make it entirely publicly editable. For now, I've added it to the events team wiki as a weekly task and I'll add the things we have in our newsletter to the calendar.
