### ISSUE TITLE
austin design week

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#289]
Austin Design Week is an annual celebration of design through a week of workshops, talks, studio tours and events. We are partnering with Austin Spark League to run a week long design-a-thon. Their leader Nick Hahn has started a proposal here: https://docs.google.com/document/d/1mKZqkPtqToTnelCmgprc2H8oFQuiQzu_hswBJkBs_4w/edit

**Comment by VictoriaODell** [comment]
@werdnanoslen what is going on with this? I saw them mention stuff on their site but it doesn't appear we are involved. 

 https://austindesignweek.org/design-a-thon

**Comment by werdnanoslen** [comment]
yeah actually i hadnt heard anything except from Nick that we should chat soon but I hadn't heard anything from them. Until today, when they posted this internally: https://www.eventbrite.com/e/austin-design-week-2017-presents-design-placemaking-for-local-civic-engagement-registration-38220248793

Looks like the organizers changed to some other folks I know that aren't involved in anything civic as far as I know. So I think they're just going in an entirely different direction. Looks like they don't want us involved, unless we ask to be? What do you think?

**Comment by werdnanoslen** [comment]
See the email thread with info@open-austin.org for more info. TLDR, they're going in a direction that doesn't really align with our community, so we won't partner with them but would share their events among our other community events. Still want to keep discussing it though, so Vickie and I might chat with them this week.

**Comment by VictoriaODell** [comment]
Spoke with them today. @seandellis was on the call too. I think it went well.

Here is an involvement doc I drafted up base don our conversation : 
https://docs.google.com/document/d/1KPqFqOxGhHhq2OatQmaHSiQ8kyeTzStXktibWeyM8-o/edit?usp=sharing

Here is the agenda + notes: 
https://docs.google.com/document/d/1DOsxJzTU4vNk8ylLkPb9CbDAFo82cqN231OGI6UtE5w/edit?usp=sharing

**Comment by VictoriaODell** [comment]
We did it! 

The design a thon went well. There were 6 teams and 2 projects were from the Open Austin/ ATX Hack for Change project repo. These were the projects OA brought: 

> Civic Tech/Service projects
>  ATX Votes
> How might we help interested voters get credible, accurate information about how, where and when to vote
> https://github.com/open-austin/project-ideas/issues/53
> 
> 
> Austin Green Map
> An app with all the parks in Austin. Offline, mobile-friendly, and easy to search for features and amenities
> https://github.com/open-austin/project-ideas/issues/1
>  
> CodeForAustin.org
> https://github.com/open-austin/project-ideas/issues/102
> 
> 
> Request Yo Racks 
> https://github.com/open-austin/project-ideas/issues/117
>  
> Welcome Basket 
> https://github.com/atxhack4change/2016-project-proposals/issues/20
> 


This was the civic hacking 101 deck used: 
https://docs.google.com/presentation/d/174K-6DU4eNqT1FYkQeQYA6RI8r-fPbukmgwOD5n1zMA/edit?usp=sharing


The winners of the design-a-thon were a group of UT students that picked up the project, Request Yo Racks. They got 6 SXSW tickets and we'll work to keep their project going. There is the project lead and the transportation department involved at this point :) 

More info on the event: 
https://austindesignweek.org/design-a-thon


A retrospective is being held sometime next week.
