### ISSUE TITLE
Which of our featured projects are still working/up?

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#290]
### Down (edited by Matt):

- [x] https://www.open-austin.org/projects/cycle-nearby.html (emailed owner)
DNS error at http://cycle-nearby.open-austin.org/index.html
repo at https://github.com/AustinBlues/Good-Sect--Bad-Sect

- [x] https://www.open-austin.org/projects/vote-atx.html (https://github.com/open-austin/voteatx-app/issues/28)
"Not in operation" message at voteatx.us, because data isn't current

- [x] https://www.open-austin.org/projects/lives.html (https://github.com/chip-rosenthal/atx-lives-feed/issues/1)
The code to generate a new .zip of LIVES data still works, but it's no longer running nightly, so the data at data.open-austin.org/LIVES/ hasn't been updated since 2017-01-11. The [mirror on data.world](https://data.world/openaustin/lives-restaurant-inspection) says it was last updated in 2016.

- [x] https://www.open-austin.org/projects/austin-restaurant-scores.html (https://github.com/open-austin/iced-coffee/issues/290#issuecomment-338511614)
Now [visible online](https://www.open-austin.org/atx-restaurant-scores/), but the [dataset search function isn't working](https://github.com/open-austin/atx-restaurant-scores/issues/10), and that's really the site's only feature.

- [x] https://www.open-austin.org/projects/bike-buddy.html (https://github.com/open-austin/iced-coffee/issues/290#issuecomment-338511614)
DNS error at http://bike-buddy.open-austin.org/,
repo at https://github.com/chip-rosenthal/bike-buddy

- [x] https://www.open-austin.org/projects/austin-recycles.html (https://github.com/open-austin/iced-coffee/issues/290#issuecomment-338511614)
DNS error at http://austin-recycles.open-austin.org/
repo at https://github.com/open-austin/austin-recycles

- [x] [Recycle Please](https://www.open-austin.org/projects/recycle.html) The site is supposed to crowdsource reports about what buildings don't recycle, but it can't accept reports and I don't think it can show a map. Its database has been taken offline. The [front end is up](https://www.open-austin.org/recycling-atx/).

- [x] [Pet Finder](https://github.com/open-austin/pet-finder) Our projects page says this project's URL is [pet-alerts.com](http://www.pet-alerts.com/), which now redirects to https://www.petalert.us/, a site not controlled by us.

- [x] [Open Gov Datasets by Department/Category](https://www.open-austin.org/projects/datasets-by-dept.html)
The page loads [without any data](https://data.open-austin.org/data-catalogs/views/by-department.html). It's probably because the nightly update isn't working.

**Comment by mateoclarke** [comment]
Hey @werdnanoslen. Can I help with this? Could this align at all with Grackl?
https://github.com/cityofaustin/grackl

Could I use OA projects as seed data, and in the process, update the data on project status for OA?

**Comment by werdnanoslen** [comment]
Oh ya that'd be neat! Would you just use the public read-only API to fetch info? I think that might related to #264 too. This issue is more about me going through all our prjoects and just turning them back on

**Comment by werdnanoslen** [comment]
@chip-rosenthal On the [ATX Scores settings page](https://github.com/open-austin/atx-restaurant-scores/settings), there's an error saying the "Domain's DNS record could not be retrieved." I checked the [dns settings file](https://github.com/open-austin/server-configs/blob/master/dns/db.open-austin.org), which had this as an entry, but I'm entirely unfamiliar with how to assess it from there. 

The same issue might be behind the Bike Buddy and Austin Recycles sites being down. Could you please help and point to docs on how we could diagnose these problems in the future?

**Comment by chip-rosenthal** [comment]
@werdnanoslen  - I believe the problem may have been that when open-austin.org DNS was migrated to Cloudflare, entries for the microsites were dropped. Whoever is running the DNS would need to add a proper CNAME record.

Also, I think you could delete the CNAME file from the gh-pages branch and just run the app at:

open-austin.github.io/atx-restaurant-scores

**Comment by VictoriaODell** [comment]
@mscarey has agreed to audit 
after auditing the comms team will review.

**Comment by mscarey** [comment]
Probably Cycle Nearby, Bike Buddy, and Austin Recycles all have a similar CNAME issue to the one the restaurant scores app had, but I don't have Cloudflare access at the moment and I'm not sure how I'd fix it even if I did.

**Comment by mscarey** [comment]
### Dormant

- https://www.open-austin.org/projects/lobbying-in-austin.html
(https://github.com/open-austin/lobbying-in-austin/) [Lobbyist chart](https://www.open-austin.org/lobbying-in-austin/)
Data about lobbyist clients is no longer on the data portal, so the incomplete-looking visualization is no longer updated.

### Up:

- [Appleseed School to Prison Pipeline content/map](https://www.open-austin.org/projects/appleseed.html) (https://github.com/txappleseed/txappleseedmap) Online as [Texas Discipline Lab](http://www.texasdisciplinelab.org/)

...many more...

**Comment by chip-rosenthal** [comment]
@mscarey - The three legacy projects you cited (Cycle Nearby, Bike Buddy, and Austin Recycles) probably shouldn't be live on the web. Bike Buddy and Austin Recycles have legacy data (contact info and old recycling pickup routes) that shouldn't be used. If somebody wants to run them, I'd suggest doing something with a Docker container or Vagrant.

**Comment by VictoriaODell** [comment]
Hey @mscarey is the full audit done? Looks good now we just need to figure out the steps moving forward.

**Comment by mscarey** [comment]
@VictoriaODell Yeah, I've looked at all the projects now. I think the biggest need is to make a [separate page on the website for archived projects](https://github.com/open-austin/open-austin.github.io/issues/150) to keep them separate from active ones.

Andy's original goal for the audit was to turn projects back on that are no longer working. I think "Liberate Appraisal Data" is the only one that we should clearly try to stand back up, and there's an active Slack channel working on that. We could also consider "Construction Permits" but I think it's better to ask if there's a consensus the broken scraper for that project should just be turned off.

I think another high priority is to [better anonymize the records](https://github.com/open-austin/harris-county-bookings/issues/12) on the harris-county-bookings project.

**Comment by chip-rosenthal** [comment]
If you need any assistance with the legacy apps or the ch3data VPS, let me know. I'd be glad to get together sometime.

**Comment by mscarey** [comment]
Thanks @chip-rosenthal. I didn't even realize data.open-austin.org and Cute Pets had the same hosting as Bike Buddy and Austin Recycles, on ch3data. Are data and Cute Pets the only two projects hosted on ch3data that we should keep live?

**Comment by VictoriaODell** [comment]
Hey @mscarey should we close out this issue and break it up into pieces? We know where are projects are at now. It's just prioritizing our action.

**Comment by mscarey** [comment]
Yeah, this can be closed. Work on the appraisal data is in [their repo](https://github.com/open-austin/liberate-appraisal-data), and there's an open issue about the [fate of the broken construction permit scraper](https://github.com/open-austin/construction-permits/issues/26).
