### ISSUE TITLE
Vote on and onboard new leadership

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#291]
We've had a few people interested in joining and I'm working on wrapping up a few conversations with more potential leaders. 

**IN THE PIPELINE**
- **Aditi** // following up. Expressed interested in helping on the comms side. If not a core leadership position then would like to have her contribute. 
- **Vicky Pridgen** // Interested in taking on a small project to help with Biz Dev. I approached her to help with our partnership development packet. 
- **Leslie Barrientos**// Also interested in the comms side. Followed up with her to set some time up to chat and discuss a role 

**READY** 
- **Sarah Shields**// We need to get a vote in on adding her to our core leadership team as "Brigade Evangelist. 
- **Happiness Kisoso**// engaged and ready to work. Need to pitch the "Communication lead" specifically to her. 

Can we do a digital vote? I asked this in iced-coffee. Will this platform be suitable? 
https://www.adoodle.org/

**Comment by werdnanoslen** [comment]
Looks good to me, let's get it set up?

**Comment by VictoriaODell** [comment]
@werdnanoslen will do! 

I met with Leslie today and I believe her and Happiness would be perfect for sharing the comms role.

Also, am keeping answers in this spreadsheet for the leadership application. 
https://docs.google.com/spreadsheets/d/17lbXF4a_H0ikjB5Z7JTK3Sd98JJ0p_uiqpKRZTBxhUY/edit?usp=sharing

Also, 2 new people are on the list. Will have to do some follow up with them in the coming week. 

Next steps: 
- [ ] Ask Happiness how she would feel about being co-comms lead with Leslie
- [ ] get Leslie + Happiness talking
- [ ] Send out digital vote for Sarah shields, Happiness, and Leslie.

**Comment by mapineda** [comment]
This can be closed. Congrats Happiness, Leslie,  & Sarah!
