### ISSUE TITLE
Inclusive hosts

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/iced-coffee#292]
1. Update our "please host us" one-pager to include asking about inclusivity concerns like gender-neutral restrooms, mobility equipment accessibility, directions and accessibility features available for visually impaired folks
1. Check this with our current hosts

**Comment by VictoriaODell** [comment]
We have a sheet that could use some major updating to help with this. Here is is: 
https://docs.google.com/spreadsheets/d/1ktqM298IiEtj5_fpwlRoxlv8sWPHrzxfvxU285fosO0/edit?usp=sharing

I pulled it apart from another sheet. @mapineda would be the one to help with this.

**Comment by mapineda** [comment]
@victoriaodell did you see the latest email from Cap Fac RE: Saturdays for rest of the year? It looks like they're cool with us booking long term but I still want to meet with you and Joshua to discuss. Right now I'm thinking we request Q1  - Q2 dates and then set up a meeting when you get back. Thoughts?

**Comment by mapineda** [comment]
Ref #287

**Comment by VictoriaODell** [comment]
@mapineda replied to #287 let's catch up after the retreat and make a plan of action for getting our venue spaces filled!

**Comment by VictoriaODell** [comment]
Also, idk if we have a "please host us" one-pager. 🤔

**Comment by VictoriaODell** [comment]
We don't currently have a one-pager but I added this to our community action night playbook under "Pre-event communications" 
https://docs.google.com/document/d/15TOa0-pXkHlmMTGZBWTq9yf3KIQW_3ViCFfLsg7eK1U/edit?usp=sharing
