### ISSUE TITLE
Meeting Notes for Communication team 11/6/17

### ISSUE THREAD

**Issue by happinessk** [open-austin/iced-coffee#295]
**Participants:** 
- Happiness Kisoso 
- Leslie  Barrientos

**Discussion**
- The importance of user centered design 
- Establish personas in order to tailor our content and customer touch points in an appealing way
- The importance of establishing a vision
- Plan a ideation session with leadership in December  
-  Focus on desk research 

**Project Tracking Process**
- Develop a Trello Board (https://trello.com/b/9aWpc0T8/open-austin-comm)
- Scrum approach using agile while developing sprints and building a backlog
- Sprint  planning beginnings on November 17th & ends on the 27th 
- Communication team plans to meet on Fridays 3-5pm

**Comment by VictoriaODell** [comment]
Hey y'all! 

We don't have a trello but we use waffle which has a similar interface but uses Github. It is linked in our iced-coffee [readme](https://github.com/open-austin/iced-coffee/blob/master/README.md): [https://waffle.io/open-austin/iced-coffee](https://waffle.io/open-austin/iced-coffee)

![image](https://user-images.githubusercontent.com/10767430/32581081-052525a4-c4ae-11e7-8229-07157d5e6493.png)

When you say "project tracking" do you mean specifically comms projects or open austin volunteer projects? 

Also for the comms team meeting is this reoccuring every Friday? If so I can add it to the Open Austin calendar in case other want to join in. :) 

Additionally, I encourage you to put a profile picture on your account and add a short bio to your page. :) Excited for y'alls participation!

**Comment by VictoriaODell** [comment]
Hey, @lesliebarrientos and @happinessk let's keep meeting notes in google drive. There is a folder here: https://drive.google.com/open?id=1HqJ-xsidawp3uUOQ8YJ8cDH32IxPKqE0

You can make an issue for the meeting though and post things you're going to speak about and link to related material. Once the meeting is over then you can post the agenda/notes and close the issue.  If you have action items those can move into new issues

Let me know if that makes sense.

**Comment by VictoriaODell** [comment]
Closing this out! Some of these items are in issues now and we seem to be moving forward.
