### ISSUE TITLE
Plan December Leadership Retreat

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#298]
**Discuss potential future leadership retreat**
Last year we did a leadership where we worked to identify some goals for the year. We would like to gather again for some additional time to consider what we want to change in 2018 with the feedback we receive from the community and the partnerships we've grown this past year. 

- [x] Reach out to potential facilitators: 
- Shellee
- Daniel 
- [x] Determine time & Date with a doodle poll 
- [x] Create calendar item
- [x] Determine location 
- [x] Determine Agenda
- [x] Create/obtain artifacts needed for retreat
- [x] Figure out & order food

[Artifacts from last year](https://drive.google.com/open?id=0B1cMlEZm_nJ0OG5Ta0lUSDd5RUU)

**Comment by VictoriaODell** [comment]
@sortizsh sent out a doodle poll and scheduled time on the calendar. We chose Saturday, December 9th from 10am-4pm. 

Location TBD but we discussed booking rooms in the library. The schedule is TBD right now too!

Shellee said she is holding time for the dates we picked.

**Comment by danielryne** [comment]
So sorry about the late reply on this, y'all. I'll not be able to make that day, probably until after 3:00 pm because of work. I'm happy to help plan and brainstorm about goals, topics and flow/facilitation, if you want to get together before then @VictoriaODell and @stepwinder ! Let me know!

**Comment by VictoriaODell** [comment]
Thanks for replying @danielryne! We are chatting with @stepwinder about meeting sometime this coming Sunday, December 3rd, right now. 

Here are some current materials we have for planning. 

- **Feedback stickies from input session** 
Still working some on cleaning it up and we are adding more comments in the notes section over this week. Happiness will work to create a blog post of what we've found next week. 


- **Planning and Retreat docs from last year** https://drive.google.com/open?id=0B1cMlEZm_nJ0OG5Ta0lUSDd5RUU

Agenda to come.

**Comment by danielryne** [comment]
Cool! Are you also going through the leadership feedback survey results you
got a few months ago? Those responses might be helpful in providing a
lookback and framing for going forward.

Let me know if I can be helpful. Right now, I should be open on Sunday if
that's where y'all land on.

Danny


LinkedIn <https://www.linkedin.com/in/danielrynelucio> | Twitter
<https://twitter.com/danielrynelucio> | Facebook
<https://www.facebook.com/danielrynelucio>
(pronouns: he/him)

**Comment by VictoriaODell** [comment]
Yesterday @stepwinder, @sortizsh, and I met to talk about the Agenda for the retreat. These were the to-dos as I understand them: 
- Create retreat Agenda- Shellee 
- Create values Slide- Vickie
- Create User Personas- Sarah

I'll be getting an iteration of the deck on Wednesday and will pilot the format at Civic Hack Night for Civic Hacking 101. I've been throwing documents and notes in #oa-leadership_retreat.

Also, need to figure out what we are doing about food.

**Comment by VictoriaODell** [comment]
Retreat planned! @sarah and I are talking next steps this week.
