### ISSUE TITLE
11/8 Button Machine 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#3]
- [x] Look up pricing for button machine and supplies. 
- [x] Recieve feedback on pricing and sizes
- [x] Send to @mateoclarke to order

Button machine pricing: 
[1" button machine for $200](http://www.thelashop.com/1-badge-machine-pin-button-maker-w-1000-parts-circle-cutter.html?gclid=CjwKEAjwwbyxBRCS74T049iEp0wSJACkO5v1a9_-z48noSTRm486ChKti8rJ58_lYSad-1MlQSVgjxoC0ODw_wcB) + Shipping and Handling 
[1.5" button machine for $256](http://www.thelashop.com/1-badge-machine-pin-button-maker-w-1000-parts-circle-cutter.html?gclid=CjwKEAjwwbyxBRCS74T049iEp0wSJACkO5v1a9_-z48noSTRm486ChKti8rJ58_lYSad-1MlQSVgjxoC0ODw_wcB) + Shipping and Handling
[1.25" button machine for $205](http://www.ebay.com/itm/like/311011319522?ul_noapp=true&chn=ps&lpid=82) + Shipping and Handling
Once we pick one of these we should then order pin backings, plastic covers, and a button shape puncher for the appropriate size. 

Bankings range from $30-$60 but depends on what size we choose and how many and the mylar(plastic outeshell) will likely run around $20 dollars but depnd on size and how many.

**Comment by VictoriaODell** [comment]
@mateoclarke thoughts on sizing and pricing appreciated. I think either the 1.25" or 1.5" would work the best for us with the 1.5" being more versitile. 

@amaliebarras @luqmaan

**Comment by mateoclarke** [comment]
Not my area of expertise at all, but I'd vote for 1.25". Also playing devil's advocate here, how many buttons do we make before this machine pays off? Looking at button making services, it seems like you can get down to $1 per button at around 200 units. Am I wrong? How much labor goes into making that many buttons. I think Chip make have a surplus of those light blue CfA buttons too.

**Comment by VictoriaODell** [comment]
Yeah, the 1.25" is pretty standard. I think after all cost it may come to be around $350ish dollars. That including the machine, the backings, mylar, and getting color printings for the button imagery. 

So things that could be **cons**:
- up-front cost 
- We have to do the button making ourself (time-commitment)
- Maintaining the button machine and supplies 

It takes time to cut and put the buttons together but it's a pretty easy activity and if we get a circle cutter that makes things easier. I've worked with a button machine at a previous job and it's def a busy activity. We'd also have to budget to do our own color printing and think about cost for maintaining supplies. 

Things that could be **pros**:
-  Short turn-around time for production depending on how much we want. No shipping/handling after recieving the machine and a good stockpile of supplies
- With proper care will last years~
- Will ~eventually~ pay for itself w/continued use
- More button variation. Ordering online you can usuaslly only choose one design. We could print out a sheet with all different designs and do limited runs, etc. 

I think part of the value is that we won't have to rely on ordering anything for future events unless we run low on buttton making supplies, which isn't something that happens fast. Even then supplies are much cheaper than ordering made buttons(Button backings for 100 is about $20 and the mylar runs as low as $3-$5, then the cost of printing but we can get squeeze a good amount of circles on a color 8.5"x11"). Plus, this is a nice giveaway we can customize for events and turn-around relatively fast compared to ordering anything, like stickers or buttons online. 

Overall, buttons are just a good brand-awareness item that people tend to love to pick up. If we have to fundraise we could also make little button packs or sell certain buttons or button designs. If we plan out our supplies and how to use it I think it'll be a great asset moving forward and make for fun prizes, giveaway, etc.

**Comment by mateoclarke** [comment]
Buttonfrog.com seems like a better deal. I'm worried the button creation process would be A LOT of work.

<img width="1003" alt="screen shot 2015-11-18 at 8 16 41 pm" src="https://cloud.githubusercontent.com/assets/5697474/11260489/6cd0146c-8e31-11e5-8393-df8e67cde6e8.png">

**Comment by VictoriaODell** [comment]
Thinking on this. As much as I'd like to be able to do it, it may be better to just order buttons. :disappointed:

**Comment by VictoriaODell** [comment]
@mateoclarke You think we can get 2 variations made?

**Comment by mateoclarke** [comment]
sure!

**Comment by VictoriaODell** [comment]
Alright, I'm almost done. Is it better to post the pdf here?

**Comment by VictoriaODell** [comment]
Ah, I made them to 1.25. Do we want 1.5?

**Comment by VictoriaODell** [comment]
There are 3 options of 1.25 becaue I couldn't pick :see_no_evil: 
Thoughts? the on the first 2 is going to be on the edge of the button. 
[Button_125Inch_BlackOrange.pdf](https://files.zenhub.io/567593ba46e449450c50f7bf)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[Button_125Inch_FullColor.pdf](https://files.zenhub.io/567593c046e449450c50f7c0)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[Button_125Inch_FullLogo.pdf](https://files.zenhub.io/567593c546e449450c50f7c1)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by luqmaan** [comment]
Great work on the logo. By opinion is bigger text is better since it's easier to see from a distance.

**Comment by VictoriaODell** [comment]
@luqmaan on the logo or the button?

**Comment by luqmaan** [comment]
Button

**Comment by VictoriaODell** [comment]
@luqmaan 
Only 1 of the button options would have the full logo visable w/text. 
The other 2 would have the words on the rim of the button.

**Comment by amaliebarras** [comment]
I think those words along the rim are gonna show up too tiny :( May I submit a couple other concepts?

**Comment by VictoriaODell** [comment]
@amaliebarras That's the point.

**Comment by VictoriaODell** [comment]
<img width="619" alt="screen shot 2015-12-19 at 4 27 55 pm" src="https://cloud.githubusercontent.com/assets/10767430/11915473/7d4bae24-a66d-11e5-866a-e45a4d4a7e57.png">
Here is a photo for refrence. I followed the template that buttonfrog has

**Comment by amaliebarras** [comment]
oooooooh okay!

**Comment by VictoriaODell** [comment]
The "Fulllogo" pdf file is the only button idea that would have the words on the button.
Feel free to take the PDFs into illustrator and make variations.

**Comment by VictoriaODell** [comment]
Might actually be good to put the website link on the edge too.

**Comment by amaliebarras** [comment]
Yeah, I didn't understand. The picture example helped :) These r great.

**Comment by mateoclarke** [comment]
I like FullLogo the best. Not crazy about the all orange and dark grey. too halloweeny. :jack_o_lantern: I feel like you said you didn't like it but I'd like to see an all white star on grey or dark grey.

**Comment by amaliebarras** [comment]
<img width="368" alt="screen shot 2015-12-19 at 4 43 57 pm" src="https://cloud.githubusercontent.com/assets/11826646/11915533/e5f323ec-a66f-11e5-8c5a-7a259208fda3.png">

Is the weight of the Raleway up for discussion? Don't know if it's logo discussion or button discussion. But I put them side by side and I strongly prefer the light... 

1) I think it looks more modern
2) It's narrower so the logo w/ the font underneath is closer to square (which I remember you talking about w/ Kay from IBM)

**Comment by VictoriaODell** [comment]
It's actually a modified raleway~ I went in and made some of the edges more round to better match the logo, per feedback from others.

I think the difference in the weight of the logo and the weight of the type is kind of stark with the light option. But it looks like you also made the type larger and actually made it more rectangular in shape since by doing so. 

I also believe there is a legibility increase from light to medium.

**Comment by VictoriaODell** [comment]
Logo files are here now btw: https://drive.google.com/drive/u/0/folders/0BwKb2oghmQldX2FRNmw1XzVPc1U

**Comment by amaliebarras** [comment]
Oh, nice. Yeah I do like the more rounded corners, I just don't know how to do that on the light. 

And I personally liked the contrast btw the weight of the type and the weight of the logo. If I'm outnumbered on that that's fine. :)

Also yeah, I didn't match the size of yours, I just slapped the weights side by side to compare, I just assumed that a light font would be narrower but it seems I was not correct. 

Did you mean to say light to medium? I find the light easier to read. But again, if I'm outnumbered that's fine.

**Comment by VictoriaODell** [comment]
@mateoclarke Yeah but I was building out the color combos and stuff and I think White would make sense to add as option. I'm leaning torwards Canvas for the shirts and a dark grey option. 

@amaliebarras Generally light to medium is increased legibility and medium to bold is where things get harder to read/scan for people. I think if we were to go lighter then "regular" would be something needed to be seen. 

But also at this point I've packaged everything up and started working on other things so would need feedback/consensus asap.

**Comment by VictoriaODell** [comment]
I'm taking a break until tomorrow. 
Hopeful I can get final buttons out and t-shirt tomorrow. 
Then stickers and banner next.

**Comment by VictoriaODell** [comment]
Bump?

**Comment by amaliebarras** [comment]
Do yo thing, I think you have consensus

**Comment by VictoriaODell** [comment]
<img width="1035" alt="screen shot 2015-12-22 at 11 21 04 am" src="https://cloud.githubusercontent.com/assets/10767430/11961436/342ad55c-a89e-11e5-8155-2baffb83e829.png">

@mateoclarke does this seem reasonable for buttons? They have a discount if you get multiple designs of buttons. 
We can get 2 styles one with full logo and one with just the mark.

**Comment by mateoclarke** [comment]
yeah that sounds good.

**Comment by VictoriaODell** [comment]
I believe these are done @mateoclarke 

Order 1.25" buttons [here](https://www.buttonfrog.com/products/1-25-inch-round-buttons) 

Full color logo with white background here: 
[Button_125Inch_FullLogo.pdf](https://github.com/open-austin/iced-coffee/files/70332/Button_125Inch_FullLogo.pdf)


White logo mark with Orange background here: 
[Button_125Inch_OrangeWhite.pdf](https://github.com/open-austin/iced-coffee/files/70334/Button_125Inch_OrangeWhite.pdf)
[Button_125Inch_OrangeWhite.pdf](https://github.com/open-austin/iced-coffee/files/70337/Button_125Inch_OrangeWhite.pdf)

**Comment by mateoclarke** [comment]
Order placed, we should receive proofs to info[at]open-austin within the next 24 hours. :shipit:

**Comment by mateoclarke** [comment]
![screen shot 2015-12-23 at 8 52 01 am](https://cloud.githubusercontent.com/assets/5697474/11978629/a43e1dc2-a952-11e5-9165-5a9ad685864f.png)

**Comment by mateoclarke** [comment]
Proof #1 looks great!
![screen shot 2015-12-23 at 10 25 08 am](https://cloud.githubusercontent.com/assets/5697474/11980308/90f796c8-a95f-11e5-9d6a-8b87136a41eb.png)

**Comment by amaliebarras** [comment]
I loooooove it!

**Comment by mateoclarke** [comment]
![screen shot 2015-12-23 at 10 35 04 am](https://cloud.githubusercontent.com/assets/5697474/11980496/e0b262aa-a960-11e5-8fba-3ecdf8a6b95e.png)
