### ISSUE TITLE
November,  December, & January Library Meetup Planning 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#300]
I started a rough outline of what I'm thinking for our upcoming library meetups. 

## November 20th 
Community Feedback + Input round 1

## Before December 9th 
- [x] Send out survey to partners + Members @sortizsh 

## December 9
Leadership retreat

## December 18
Open Government lightning talk and community workshop 

## Week of Januaray 8 
- [x] Schedule doodle poll for date/ time
- [ ] Shareout with partners on what we are thinking and get feedback. 

## Monday January 23 
Share out of what we learned and what's ahead for 2018 + 2 lightning talks from the community

**Comment by sortizsh** [comment]
link to working ideation doc @happinessk @VictoriaODell  https://docs.google.com/document/d/1hOn1HAV-yhTt6qGOga11KBDPx8L7j6ose57Vc76Bp3Y/edit

**Comment by sortizsh** [comment]
Please vote on the EOY Leadership planning poll https://doodle.com/poll/8a32t5gavt2hdnf3

**Comment by sortizsh** [comment]
@happinessk  @VictoriaODell @mapineda @lesliebarrientos @seandellis @jonplaca @mscarey can you take a look at the community feedback questions and comment/add questions? https://docs.google.com/document/d/1hOn1HAV-yhTt6qGOga11KBDPx8L7j6ose57Vc76Bp3Y/edit?usp=sharing

**Comment by VictoriaODell** [comment]
Sure thing @sortizsh! Also we have @open-austin/leadership if you want to get in touch with everyone. :)

**Comment by VictoriaODell** [comment]
Update on this! 
- We had the November meetup with 2 lightning talks and community input session 
- December we will have a more general Open Government meeting with a schedule tbd
- January we will present our changes and what's coming up for the new year.

**Comment by VictoriaODell** [comment]
Completing this today! We rolled the partner shareout and general shareout to the one library meeting. Made more sense and gave us time to prepare.
