### ISSUE TITLE
Archive old hackathon wikis

### ISSUE THREAD

**Issue by mscarey** [open-austin/iced-coffee#301]
While auditing which old projects are still working, I found some deactivated wikispaces wikis for old hackathons. Maybe we should keep the wikis so we'll have a record of defunct projects to help new people avoid repeating old mistakes. The wikis were probably created by @chip-rosenthal. I don't know the email address for login; it's not the open austin info address. Chip might have archived the wikis before they were deactivated, or wikispaces support might still be willing to export archives. The project pages for each wiki are inaccessible, but you can still read the names:

http://codeacrossaustin.wikispaces.com/
Austin LocalWiki
Bike Project
Campaign Finance
Civic Improvement Wiki
GardenMatch
Google Places API Challenge
Homeless Services
NeighborlandAPI
Prepared.ly Updates
Tools
Transportation Projects

http://codeatx.wikispaces.com/
Art Mapper
Bike Accident and Route Safety
Digital Divide
Find It
Food and Drinks
Garden Dating
Google Group
IRC
Project Criteria
Projects
Skills List
Tools
Transit Improvements
Transit Mash
WebATX URL Shortener

http://atxcivichack3.wikispaces.com/
App Deployment
Campaign Finance Database
Data Project
Detour Planning App
Frugal RSVP
Open Map Curation
Podcast Portal
Project Breadcrumbs
Proposed Legislature
Recycling Pickup App
Stray Mapper

http://atxhackforchange.wikispaces.com/
Agenda Alerts
Art Finder
Austin Recycles
Bike Share Locator
Connect2Good
Food Lab Mapathon
Getting Them Home
Keep Austin Fed
TEC Filer

http://atxhack.wikispaces.com/
Austin Recycles
Bike Buddy
Open Austin Website
Restaurant Scores
TEC Filer
plus hack nights 2013-03-18 through 2013-08-19

https://atxdataportal.wikispaces.com/
This one's still online. "How to Use the City of Austin Open Data Portal"

**Comment by VictoriaODell** [comment]
oh this is an interesting find @mscarey. Now I'm curious to see if we can get access.

**Comment by chip-rosenthal** [comment]
In 2014, Wikispaces service terminated their free accounts.

http://blog.wikispaces.com/2014/09/wikispaces-is-no-longer-offering-free-non-education-wikis.html

At that time, all of the wikis were exported and the results saved.

(Except one -- the atxdataportal wiki. There was a wiki setup as a documentation site for the data portal that Wikispaces agreed to continue. I may have credentials for that if somebody wants access.)

The exports were posted to the old website  -- along with some other legacy assets that existed prior to the Wordpress blog. That old website is on the VPS that CH3 Data donated to the group and (I believe) is still in operation.

I was sad to see that content jettisoned. I think it's of historical interest. This includes the very first wiki that the Code for America fellows setup for the very first civic hackathon in Austin.

If you've got a person that wants to do Linux admin work on that VPS, I'd be glad to show them what's there.
