### ISSUE TITLE
Get CloudFlare Pizza

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#302]
@prestonp shared this with us. 

## [Cloudflare Wants to Buy Your Meetup Group Pizza](https://blog.cloudflare.com/cloudflare-wants-to-buy-your-meetup-group-pizza/)

- Here are the rules for [reimbursable pizza](https://docs.google.com/document/d/1wvJjiS1iuzf_XYNaah20xTwNfjcBQeiqjmrHi9CEFWM/edit?usp=sharing)
- Here are the [slides we have to present](https://docs.google.com/presentation/d/1afluXpf2eYeQ7SkmV2ONrojeZwosMTNifhnZR1chNTw/edit?usp=sharing)

We should reach out tell them who we are and figure out if we're a good fit before ordering. I think we would be. I think we might be using cloudflare for something too. I'm not entirely sure but it looks helpful for projects and their [app gallery](https://www.cloudflare.com/apps/) is pretty neat. Also, If we do start getting pizza on a regular basis I think we need to be more aware of gluten free, vegan, and vegetarians options. I have a friend who can't have cheese on her pizza 🍕 😢  . 

Here is the email we should reach out to. 
community@cloudflare.com

Any thoughts on this @mapineda? 

Next Meetup I think would be Wed, December 6th.

**Comment by mapineda** [comment]
I don't think we are using them for anything but i'll look into what they have to offer. They have graciously hosted us in the past. I'll reach out in the next few days. Wish github had a "!Remindme x days" feature like reddit...

**Comment by VictoriaODell** [comment]
look, @mapineda we do use Cloudflare 

<img width="761" alt="screen shot 2017-11-17 at 9 03 27 am" src="https://user-images.githubusercontent.com/10767430/32953577-4bf601dc-cb76-11e7-952e-51c8b18c273c.png">


Unsure of what other services are floating out there.

**Comment by mateoclarke** [comment]
Yeah, we us them for DNS for open-austin.org, austinparkequity.com, austinbudget.party. 

The login details are stored in Lastpass

**Comment by VictoriaODell** [comment]
Hey @mapineda You think we can try the pizza thing this Wednesday or should we plan for Tacos?

**Comment by mapineda** [comment]
@VictoriaODell I reached out. If we hear back we can buy pizza and follow the steps on their process form here https://docs.google.com/document/d/1wvJjiS1iuzf_XYNaah20xTwNfjcBQeiqjmrHi9CEFWM/edit

**Comment by mapineda** [comment]
@victoria_odell Cloud Flare approved the pizza! We can go ahead and order for the next hack night. We just have to include their slides, take pictures during the event and tweet their handle and fill out the reimbursement form.  Then we wait a month for the check. The amount is capped at $250

**Comment by mapineda** [comment]
Stickers came in!
