### ISSUE TITLE
Identify what success looks like

### ISSUE THREAD

**Issue by happinessk** [open-austin/iced-coffee#304]
The Comms team is working on identifying the vision and mission for Open Austin 5 - 10 years from now ..... what does success look like for Open Austin in currently and in the future?

**Comment by lesliebarrientos** [comment]
This ties in with defining the vision for Open Austin. What is the vision for Open Austin 5, 10 years from now? 

As of now, success ties into launching a project and serving it's purpose. For example, BudgetParty was a prototype with the permitting team (research, documentation, and a prototype) and the prototype itself was the project serving it's purpose. After this, the Innovation lab was able to get the research and prototype and build something off the prototype Open Austin created.

**Comment by VictoriaODell** [comment]
Wish we could have kept working on this together but closing this out.
