### ISSUE TITLE
Define who we will interview

### ISSUE THREAD

**Issue by happinessk** [open-austin/iced-coffee#305]
@lesliebarrientos  plans to go to the meeting on Monday (nov 20th ) and try to interview users.

Task for @lesliebarrientos:
- [ ] - Try to discover their purpose and what value they see in attending
- [ ] - How did they hear about the event?
- [ ] - Look at list of questions developed for this meet up.

**Comment by VictoriaODell** [comment]
We did our community feedback survey and in-person meeting and have since made changes to our programming. We are continuing to work to improve the experiences. 

Closing this since it no longer has leads.
