### ISSUE TITLE
Develop research plan

### ISSUE THREAD

**Issue by happinessk** [open-austin/iced-coffee#307]
Currently the Comms team is working on a Communication research plan...a few things we should do:
- [ ] Identify who we should interview
- [ ] interview Open Austin participants/members/attendees/supporters 
- [x] Collect data from November 20th meetup 
- [x] Synthesis the feedback collect from November 20th meetup
- [x] Review Open Austin Mission and Vision 
- [ ] Develop Communication Plan 
- [ ]  Develop the Instrumentation Plan
- [ ] Conduct desk research
- [ ] Identify questions to ask for the ideation session

**Comment by VictoriaODell** [comment]
Hey! Just want to contribute here. 

**Our bylaws is a good place to find our mission and objective**
> **Section 1.02 Mission:** 
> The mission of Open Austin is to help communities and governments exchange ideas through the use of data, technology, and design. 
>
> **Section 1.03 Organizational Objective:** 
> We are organized for the purposes of: hosting educational events and workshops, facilitating community workspaces, facilitating access to open data,providing support and resources for projects and research, and any or all lawful purposes for which a nonprofit may be organized in the State of Texas.
>source: https://docs.google.com/document/d/1HwgQ9lDcJohBLZPyRVvMqvf282mGJOGM17KFNkvBmfA/edit?usp=sharing

**On our website, we have our values**
> Open Community Spaces
> Allowing citizens from all backgrounds and skill levels to get involved and engaged in the process of bettering their community through technology and design by providing space both in person or online.
> 
> Open Government
> Supporting initiatives and policies to provide clearer paths for residents to engage with government.
> 
> Open Data
> Being stewards, evangelists, and a resource for learning about, finding, using, and freeing public data.
> 
> Open Research
> Supporting data management and publishing practices that help governments, journalists, scientists, and members of the community share their interpretations of open data, from raw datasets to published conclusions.
> 
> Open Source Technology
> Creating and using free and open tools to expand public knowledge and civic engagement.
>source: https://www.open-austin.org/about/

**Comment by lesliebarrientos** [comment]
Thanks very much for this, @VictoriaODell

**Comment by VictoriaODell** [comment]
Closing this since it no longer has leads.
