### ISSUE TITLE
Define how to promote types of projects

### ISSUE THREAD

**Issue by happinessk** [open-austin/iced-coffee#308]
How might we better promote the different types of projects? 
**Ideas:**
- [x]  promote via newsletter
- [ ] tweet new projects

**Comment by VictoriaODell** [comment]
We've started to feature projects in our newsletter thanks to @sortizsh and Allison. Stuck on the tweeting part right now because of bandwidth. Working more on what is essential to projects rather than promotion is a priority right now.
