### ISSUE TITLE
Audit current customer touch-points

### ISSUE THREAD

**Issue by lesliebarrientos** [open-austin/iced-coffee#310]
Look at website, social media, events and look at what is working, what we can improve on, and conduct a SWOT (Strengths, weaknesses, opportunities, threats) analysis.

**Comment by VictoriaODell** [comment]
Can we include instagram on this? We don't have Instagram now but it might be nice to have one. 

And we'd like to think about the process for posting if we were to start using facebook events along with meetup.

**Comment by VictoriaODell** [comment]
Still would love this but closing until we can get a marketing lead.
