### ISSUE TITLE
Compile December social media calendar 

### ISSUE THREAD

**Issue by lesliebarrientos** [open-austin/iced-coffee#315]
- Address log-in issues via desktop and mobile
- Identify best calendar options (excel or trello) 
- Determine where to upload the calendar (perhaps upload calendar to an issue)
- Identify OA events 
- Use Nov. 20th research to guide content
- Address an easy way to identify all OA events for the monthhttps://www.open-austin.org/events/

@VictoriaODell are the events on the OpenAustin website events OA is hosting? Asking so I can know how to promote these events via social. If they're promotional, it'd be nice to identify which are strictly that.

**Comment by VictoriaODell** [comment]
Hey, @lesliebarrientos for strictly open Austin events Meetup would be the best to use: 
https://www.meetup.com/Open-Austin/

The Google Calendar has OA events and community events
I started putting "Community" in front of some of the calendar items that we aren't directly involved in more recently. I've started to use "leadership" for things that only apply to leadership and those who want to join leadership. We could consider creating a different calendar for community events but I'd prefer managing one with some tags or other ways to show that it's a community event.

**Comment by lesliebarrientos** [comment]
Hi @VictoriaODell. Yeah I agree that it'd be best to have one calendar and utilize the tags. Utilizing the "Community" or "Leadership" tag would help identify. We'll be looking out for that then. :) Thank you!

**Comment by VictoriaODell** [comment]
Here is the calendar: 
![image uploaded from ios](https://user-images.githubusercontent.com/10767430/35698875-f61ea222-0753-11e8-95a6-25683aab912f.jpg)

**Comment by VictoriaODell** [comment]
It should be digitized but I've placed it in the communications digital folder for now. We don't currently have any marketing leads so we are running a little lean and are not posting as often on social.
