### ISSUE TITLE
Setup Help Wanted issue page

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#317]
If someone wants to help set this up this would be helpful in getting people working on issues of featured projects. 

http://helpwanted.team/

**Comment by mateoclarke** [comment]
I'll take this!

**Comment by mateoclarke** [comment]
I created the "Collection" for Open Austin, but when I went to add the organization, I hit the exception error shown here:

https://helpwanted.team/open-austin

<img width="1552" alt="screen shot 2018-01-23 at 4 21 43 pm" src="https://user-images.githubusercontent.com/5697474/35304082-e79a1bd8-0059-11e8-8f13-9245d201ea82.png">

Going to ping @ondrae to see if he can help us troubleshoot.

**Comment by VictoriaODell** [comment]
@mateoclarke any updates on this?

**Comment by mateoclarke** [comment]
I just slacked Andrew to see if he see the logs for the error.

**Comment by mateoclarke** [comment]
https://helpwanted.team/collections/open-austin-857362b4-dcaa-4df9-bb81-7a124ffac020

Next step is going to create a better url for it like helpwanted.open-austin.org

**Comment by ondrae** [comment]
Have a fresh clean url for you at https://helpwanted.team/open-austin

You can always embed it using https://helpwanted.team/collections/open-austin/embed if that is cleaner.

**Comment by VictoriaODell** [comment]
So cool! Thanks y'all!

**Comment by VictoriaODell** [comment]
Closing this since it's done! I put it as an item on our leadership agenda to chat about the best use. I'm thinking for our most active project repos.
