### ISSUE TITLE
Move twitter bot spam out of #general channel

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#32]
The twitter bot spams the #general channel and interrupts conversation. #announcements is a better place for it.

**Comment by mateoclarke** [comment]
agree

**Comment by mateoclarke** [comment]
done! :snowflake: :coffee: 
<img width="915" alt="screen shot 2015-11-22 at 10 16 37 pm" src="https://cloud.githubusercontent.com/assets/5697474/11329813/d0ea9264-9166-11e5-9bcb-da8104fd08eb.png">
