### ISSUE TITLE
Change Registered Agent Address

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#325]

**Comment by VictoriaODell** [comment]
Hey, @jonplaca let's just put it at my place. I can change it when necessary. Where to find how to do that would be helpful!

1817 East Oltorft Street 
APT 1024

Austin, Texas 78741

**Comment by jonplaca** [comment]
Well, if you want to help with a side-project, you can try companydocs.io :)

Try *updating* the *registered agent address* of our *Texas*  *Non-profit*. Add "DI$C0UNT" to the discount code for a free checkout. 

If you have any questions, or find the form pretty confusing, please let me know and I'll handle the work directly.

**Comment by VictoriaODell** [comment]
Hey, Jon.

I can try this today! Also, I'm speaking with CFA on Thursday about
transferring the funds.

**Comment by VictoriaODell** [comment]
Hey, @jonplaca . sorry for not being on top of this. I tried out your app and it's awesome! Actually exactly what we would have needed for work today too (Capital City Innovation is also doing an address change).

I downloaded the correct documents to update the address. 

To be clear, changing address is separate from our address as an org right? I think that's still an open issue I need to discuss with leadership.

**Comment by JMensch** [comment]
@VictoriaODell what's the status here?

**Comment by VictoriaODell** [comment]
@VictoriaODell let me come back to this.

**Comment by mateoclarke** [comment]
Should we add this issue to the docket of things @JMensch and I should tackle under the 501c3 working group?

**Comment by mscarey** [comment]
Looks to me like Jon is still the registered agent. The form to change the registered agent is at https://www.sos.texas.gov/corp/forms/401_boc.pdf
