### ISSUE TITLE
Transfer funds to UFCU Bank Account

### ISSUE THREAD

**Issue by jonplaca** [open-austin/iced-coffee#326]
Victoria,
Can you please transfer funds to the UFCU account. Furthermore, it looks like we haven't executed any expenses from the UFCU account - have we been requesting reimbursement from CFA for the past few weeks?

**Comment by VictoriaODell** [comment]
John, I followed up with Veronica and am waiting for a response.

We haven't used funds from our account because we've have had the
following: funding to use from the cities grant and food provided at our
hack events by Conde Nast.

**Comment by jonplaca** [comment]
@VictoriaODell That's fine that we haven't used the UFCU bank account - but is there a record of the transactions? This is primarily to understand our monthly expenses and help categorize them

**Comment by jonplaca** [comment]
@VictoriaODell have these funds been transferred

**Comment by VictoriaODell** [comment]
Not yet @jonplaca but I have a list of to-do's from Code for America. 

Veronica Young will handle the offboarding process. 
Be patient for a few days or a couple of weeks. We currently have a $3,000 balance

- [ ] Send copy of 501c3 status determination letter from the       IRS
- [ ] Point of contact (I think this was another form. Might need to go back and clarify)
- [ ] Provide Official new address associated with Open Austin (I think this is a standing to-do)
- [ ] Get wired the remaining balance - must provide numbers and wiring information.

**Comment by jonplaca** [comment]
@VictoriaODell Do you need me to assist with the checklist above?

**Comment by jonplaca** [comment]
Hey sorry I just got this message!
I will text you some dates when I am available - note that I will be on vacation from end of August to Mid-September so I may be unavailable during then (although, it might be good to use this time to work on non-work related topics such as Open Austin). 

No need to feel overwhelmed - I, like others, are here to help!
