### ISSUE TITLE
Ship It Weekend followup

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#34]
- [x] Blog post
- [x] Thank you email to attendees
- [x] Add attendees to google group
- [x] Attendance spreadsheet

**Comment by mateoclarke** [comment]
- in the thank you email, we should push the next Hack Night. You could send it out through Eventbrite.
- @amaliebarras, can you make sure to get the folks that opted into emails from us onto the google group? And get all the attendees added to our attendance spreadsheet?

**Comment by amaliebarras** [comment]
Yes!

**Comment by mateoclarke** [comment]
The blog post is drafted and scheduled to publish Dec 1 at noon. _still time for revisions and more pictures_

**Comment by mateoclarke** [comment]
Opening a new issue for sponsorship followup.
