### ISSUE TITLE
Status update on Request Yo Racks

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#343]
**Task description:** 
In our last leadership sync, we had the question of what the status is on Request Yo Racks and wanting to understand why Remi has switched focus to ScraPD.

We'd like to be able to better communicate about if its paused or ended, why so. And be able to communicate that 

**Owner:** Person who completes the task. Also the "Assignee"
@mscarey 

**Supporter:** People available to help with the task
Tech & Projects Team 

**Next Steps:** 
- [x] DM/Slack msg Remi on status and report back to leadership

**Comment by mscarey** [comment]
[Rémy's update](https://open-austin.slack.com/archives/C82FGEPMZ/p1552835531023800)

I asked for more detail about what buy-in is needed from the city.

**Comment by mscarey** [comment]
Rémy said he's confident the experience for city employees will be exactly the same when requesters use RYR, so he's not too worried about buy-in.
