### ISSUE TITLE
Draft an MOU with Innovation Office around space use at Faulk and OGP commitments through 2019

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#344]
**Task description:** 
There's been informality in our agreement to use Faulk. This had made event planning for this year hard. And there is room to improve the "co-creation" and reporting that is supposed to happen with civil society partners related to OGP commitments. It would help to get expectations down on paper.

**Owner:** Person who completes the task. Also the "Assignee"
Vickie 

**Supporter:** People available to help with the task
Leadership Team 

**Next Steps:** 
- [x] Draft an MOU regarding space and OGP expectations
- [x] Schedule time to meet with Sabine/IO team in person for an update on OGP

**Comment by VictoriaODell** [comment]
I'm emailing Sabine today about connecting! I'll draft something and have it ready prior to our meeting.

**Comment by mateoclarke** [comment]
sounds good! happy to review prior or after the meeting, whatever is best

**Comment by VictoriaODell** [comment]
Sabine agreed to meet prior to our 4/1 meeting at 4:00pm to discuss using the space and OGP agreements. @mateoclarke when I have a draft I'll share!

**Comment by mateoclarke** [comment]
Just updating this on your behalf @VictoriaODell. Draft is complete with feedback and suggestions and in person has been scheduled:
https://docs.google.com/document/d/1hUkA8WN4DCTviEpItSplWMM-EABJ6vQSz6IITVbzrIY/edit
