### ISSUE TITLE
Research what our tax burden could look like with different scenarios

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#349]
The idea here is to start mapping out how our financial reporting overhead increases if we had more revenue and labor/contractors to pay. This research will help present the roadmap/501c3 options

**Comment by mscarey** [comment]
Is this question really about the burden of recordkeeping, rather than a "tax burden"?

**Comment by mateoclarke** [comment]
Yeah, I think so @mscarey. Good distinction. I'll let @JMensch clarify since this was something he brought up and was going to look into.

**Comment by JMensch** [comment]
Talked to our fractional CFO at Magnifai (also happens to be my dad, but fractional CFO sounds better) and got some info. This is all new to me, sorry if this isn't news to anyone.

General/Misc
  - If our fiscal year ends December 31, we have until May 15 to file taxes.
  - If income is <$25,000, we can bypass filing taxes and simply send some sort of notification to the IRS instead. (Didn't catch the formal name for this).
  - Filed tax docs are public.

Income
  - All income is non-taxable (sponsorships, membership dues, donations). 
  - Donations >$250 require us to send written acknowledgement. 

Staff
  - All paid staff are treated the same way as for-profit employees.
    - e.g. quarterly payroll, withholdings, etc.
  - Independent contractors have less paperwork.

Liability
  - Board members shoulder 100% of the liability in the event of litigation.
    - e.g. mishandling funds, stealing funds, tax issues.


@open-austin/leadership Happy to take any specific questions anyone has and get more answers!
