### ISSUE TITLE
Find Lightning Talk Presenters for Jan Meetup (1/11)

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#35]
~~We need to find a speaker for our January meetup. Open to suggestions...~~

UPDATED: Looking for 5-6 short (5-10min) presentations from community members. Can be any topic, sharing a story, skillshare, or lessons learned.

**Comment by luqmaan** [comment]
Maybe somebody from http://civicanalytics.com/?

I don't know anything about them other than austin + civic, so maybe they're not a good fit.

Can we open an issue for finding/suggesting speakers in general?

**Comment by amaliebarras** [comment]
I still think it'd be cool to hear from someone from community impact, statesman, or tribune working on data apps. Does anyone know people working in that space personally?

**Comment by mateoclarke** [comment]
At our core team huddle, we decided to go with Lighting Talks from the community. We're all going to reach out to a couple people.

Going to save the ideas above for future events.

**Comment by mateoclarke** [comment]
JAN 11: Lighting Talks
  - Policy 101
  - Preston Pham - a technical topic
  - Slot 3
  - Slot 4
  - Slot 5

Contact(ed/ing):
- Angela Hanson, Innovation Office (@amaliebarras)
- Daniel, GIS Public Works (@mateoclarke)
- John C's manager, Code (@mateoclarke)

**Comment by mscarey** [comment]
If you're still looking for lightning talks, I think I could easily talk 10 minutes about "Free law on the web." That would cover resources for downloading law under an open license, metadata standards for organizing it, and maybe lessons learned from the Open Austin Bill Tracker project.

**Comment by amaliebarras** [comment]
Awesome! I haven’t yet heard from Angela, (reached out again via email) so if she doesn’t respond this could fill that slot.

**Comment by amaliebarras** [comment]
Angela is a go!

**Comment by mateoclarke** [comment]
@mscarey That sounds awesome! Let's plan on adding you to the lineup! (Sorry for the delaying in responding. Just back back from my holiday vacation abroad.)

**Comment by mateoclarke** [comment]
Think we're good on presenter, just need to confirm lightning talk names. Going to close this issue for now.
