### ISSUE TITLE
Schedule/announce a board vote to replace outgoing board members

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#351]
We've discussed formally removing Sarah Shields from the board upon her request and adding James Mensch in her place. We need to decide the date of this meeting and make an announcement in accordance with our bylaws.

Tentative date: April 24 - Board meeting - Share out announcement 2 weeks prior to the meeting.

**Comment by mscarey** [comment]
I could designate the video call scheduled for Wednesday the 24th as the
board meeting, and send out notices about it. Would that work for everyone?

**Comment by VictoriaODell** [comment]
24th would work for me!

**Comment by mateoclarke** [comment]
I think we can safely close this issue post 4-24 board meeting.

minutes here: https://docs.google.com/document/d/1qSi4SZwqclslfwIXICVYYBKrzEDjHj-NHd6fnWtGtmE/edit#
