### ISSUE TITLE
Onboard Steve to leadership

### ISSUE THREAD

**Issue by JMensch** [open-austin/iced-coffee#371]
I'd like to document the process as Steve goes through it. 

@open-austin/leadership please add any steps I forgot.
@smarrison (need to find his handle) please list anything you've already done as part of onboarding that I missed.

### Onboarding Task List

- Give edit perms on our Google Drive
- Add to Github Org (if not already)
- Update email (@mscarey I don't full understand the history of the process we currently have. Is there any way to remove Courtney Rosenthal as a dependency?)
- Update leadership comms (Slack @leadership, Github @leadership)
- ???

#### Documents
TODO (overview of gdrive and important docs / locations)

#### Getting work done
TODO (overview of github and issues list)

**Comment by mscarey** [comment]
> Update email (@mscarey I don't full understand the history of the process we currently have. Is there any way to remove Courtney Rosenthal as a dependency?)

Not that I know of. I think Courtney is the only one with access to the email server.

**Comment by mateoclarke** [comment]
@mscarey @JMensch Would this be a possibility? 

Could we have Courtney direct all OA email to our shared gmail account and then from the gmail UI, we could update email forwarding for ourselves as we have new folks join/leave leadership?

https://support.google.com/mail/answer/10957?hl=en

**Comment by smarrison** [comment]
@JMensch So far I've just met with Vickie and Mateo. Vickie has sent over articles/docs on the affordable housing hub, OGP, etc. to get me up to speed. I want to compile some of these to make it easy for people to get briefed on the history/current state of these projects, a la Vickie's great timeline of the affordable housing hub.

**Comment by hubrisnxs** [comment]
(isn't just a disembodied thumb pointed approvingly to the sky, and doesn't want to cast aspersions, but I do have to say : the better you are, the more awkward I am)

*becomes an emote? Ughh [$ic], sorry, ignore above *

**Comment by VictoriaODell** [comment]
For future reference, this is the list we used for you @JMensch. It would be good for us to copy paste this to a template. What has already been done? :

## Onboarding Steps

- [x] invite to #icedcoffee Slack channel
- [x] Update leadership page on website
- [x] add to [github org admin group](https://github.com/orgs/open-austin/teams/leadership/members)
- [x] add to [@leadership slack user group](https://open-austin.slack.com/admin#user_groups)
- [x] access to open austin google drive
- [x] access to google calendar
- [x] access to lastpass
- [x] link to core team roles
- [x] set up with [email](https://github.com/open-austin/server-configs/blob/master/email/virtual)
