### ISSUE TITLE
Open Austin Boilerplates

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#39]
Make a short, medium, and long "About" for Open Austin that can be easily shared for press releases and more. This will help reinforce the Open Austin brand and ensure that our members and the others can best articulate our mission and background.  

A Good ref site: http://www.cision.com/us/2012/11/press-release-boilerplate-examples/

**Comment by VictoriaODell** [comment]
Going to dum what I currently see out there on here: 

### Facebook ###
**Short:** Promoting open government, open data, and civic application development in Austin, TX.
**long:**Open Austin is a citizen volunteer group that promotes open government, open data, and civic application development in Austin, TX.

We were formed in 2009 by citizens interested in the City of Austin web strategy and approach. Through a series of conversations, common ground was developed between the City and Open Austin to work together in a formal and recurring way. A strategic alliance was formalized between Open Austin and the City, expressing our mutual interests to partner, innovate and improve on these civic issues.

### Twitter ###
Open Austin is a member-driven organization that promotes open government, open data, and civic application development in Austin, TX.

###Open-Austin.org About##
Open Austin is a citizen volunteer group that promotes open government, open data, and civic application development in Austin, TX.

We were formed in 2009 by citizens interested in the City of Austin web strategy and approach. Through a series of conversations, common ground was developed between the City and Open Austin to work together in a formal and recurring way. A strategic alliance was formalized between Open Austin and the City, expressing our mutual interests to partner, innovate and improve on these civic issues.

The outcome of this process was when, at the end of 2011, the City of Austin unveiled its new website. The new site developed by city staff, working in conjunction with local technology companies, based on a free and open source content publishing platform. Also, a dedicated open government data portal, was released. Further, the City announced that Austin would sponsor a Code for America open government fellowship.

Presently, Open Austin focuses on ensuring that all local public sector agencies embrace open data and open government principles, provide adequate oversight over public information, and support civic software developers.

We continue to actively engage the city on open government issues.

**Comment by VictoriaODell** [comment]
**Shortest: **
Open Austin is a citizen volunteer-driven organization that promotes open government, open data, civic applications in Austin, Texas.

**Comment by luqmaan** [comment]
Check out the About Open Austin section here http://www.open-austin.org/candidate-questionnaires/documents/2014_OpenAustin_OpenGovBriefing.pdf

**Comment by mateoclarke** [comment]
Closing this out because its old. It is now referenced in the wiki:
https://github.com/open-austin/iced-coffee/wiki/Templates-and-Docs
