### ISSUE TITLE
2016 Strategic Plan & Budget

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#40]
Templates:
[CfA Strategic Planning Template](https://docs.google.com/document/d/12EGMSZL2wGKpxwcxCFCTMoeRfx95h4eF493Bh5kdkkA/edit?usp=sharing)
[CfA Budget Template](https://docs.google.com/spreadsheets/d/1r09ttR56hAUi_h5tZOxKQONG4D_WTcEaYHLLA2PCaMA/edit?usp=sharing)

**Comment by mateoclarke** [comment]
our goals: (from #41)
- continue to grow our community and create a comfortable space for people to come hack
  - to grow the community we have to know the community: create a cms
- taking open data policy recommendations through the city council process
- capitalize on the presidential election year
   - make sure voteatx.us works
- consistency with our brand and message
  - one place to send people
- more blogging and outreach to news organizations
- foster community with the data liaisons
- contact local tech press and let them know we exist if they need a blurb

**Comment by mateoclarke** [comment]
(some notes from Dec 2015 feedback meeting wins from this year and opportunities)

### Wins
- Getting invited to UT Annette Strauss Institute Breaking Through conference. Getting on their radar as a civic engagement org.
- Open Data Terms of Use
- Engaging with other groups like McChris' presentation at Maptime
- Hack: 801 vs 1, cited in academic paper


### Opportunities
- candidate survey & visibility, consulting from Carol E.
- Austin City Up, more engagement
- Policy: monthly posts to Open Data Bloomfire
- Hack: aggregate candidate questionares.
- Hack: partner with media
- Hack: reengage Lochlin on Juvenile expungement project.
- Hack: Ideathon/Problemathon to engage other orgs
- Hack: City projects coming to us through Innovation Office as filter/ problem statement framing.
- Org: Reach out to more groups, potential present at Hacks/Hackers
- Org: Too many channels to stay up with
- Hack: Pet Alerts, data problem
- Hack/Org: monthly digest, tweeting new project ideas

**Comment by mateoclarke** [comment]
pointing to full notes from Core Team Huddle post Dec Planning & Feedback Meeting: https://github.com/open-austin/iced-coffee/issues/41#issuecomment-164624479

**Comment by VictoriaODell** [comment]
I'd like to take a closer look at our goals. I've written down things that I've been thinking about. Original list in bold. I felt like things were kind of vague to me. 


our goals: (from #41)
- **Continue to grow our community and create a comfortable space for people to come hack**
  - **to grow the community we have to know the community: create a cms**
    - How many members would we like to see or what size of growth(maintain, 2x)? What kind of people do we need as members for a good balance for meetings and hack teams? Policy people, non-profits, devs, designers, analyst, etc. What can we do to appeal to the people we may be lacking in? 
    - How should we encourage and collect feedback?  
    - If we start getting larger what are our other options for spaces or is where we are at okay? If the space is too small it will detract people from wanting to come back. 
- **Taking open data policy recommendations through the city council process**
      -  How many recommendations?
      - Who would be best to lead this? 
      - How long is the proces?
      - How much work is this estimated to be? 
- **Capitalize on the presidential election year**
   - **make sure voteatx.us works**
      -  What are we hoping to get from the elections? Exposure, enthusiasm, engagement?
      -  Who can lead/is leading voteatx?
      -  What does a succesful election year look like for us?
- **consistency with our brand and message**
  - **one place to send people**
      -  Where are all the places that our brand touches? 
      -  What needs to be standardized? Social media, website, assets, etc. 
- **more blogging and outreach to news organizations**
      -  What specific things would we reach out to news organizations for? 
      -  Do we have any current news contacts? If not we need to make a list. 
      -  How often should we have a blog up? What's the best schedule for blog post. 
- **foster community with the CoA data liaisons**
      -  What are ways that we can do this? Where is a good starting point? 
- **contact local tech press and let them know we exist if they need a blurb**
      -  Do we have a list of local tech? If not then we should start by making one
      -  Would also need to get the boilerplates solid and messaging down.

**Comment by mateoclarke** [comment]
Here is our link to our [2016 BUDGET](https://docs.google.com/spreadsheets/d/1r09ttR56hAUi_h5tZOxKQONG4D_WTcEaYHLLA2PCaMA/edit#gid=0).

Main things in here to note out of **$4,900 total**:
- Budgeting **$3,900 for Events**.
    - $2,400 for snacks and drinks at Civic Hack Night & Civic Hack Saturday
      - $100 for each event
    - $500 in case we need to rent a venue
      - This does not include the in kind donation that we get from WeWork & Urban Co Lab (and maybe other future coworking spaces) to use their space once a month. We may want to include this in the future so they can get tax benefits for their venue sponsorship/donation.
    - $500 in case we need to rent chairs, equipment, etc.
    - $500 in case we need to buy supplies, post-it, projector replacement, etc.
- **$500 for Swag refills**
- **$500 for other Marketing**

Don't expect us to actually need all this money, but I think we can get there and want to have a plan on how to spend it in case we do get there. 

**The first focus should be the $2,400 for snacks and drinks at our hack nights.**

_cc/ @mapineda_

**Comment by mateoclarke** [comment]
btw, very open to changes to the Budget if i missed something above.

**Comment by mateoclarke** [comment]
The [2016 Strategic Plan](https://docs.google.com/document/d/12EGMSZL2wGKpxwcxCFCTMoeRfx95h4eF493Bh5kdkkA/edit?usp=sharing) is all but done. We should accept suggestions but let's try to get this sent to CfA by the end of the week.

The main incomplete item is #62 that is linked from the Strategic Plan.

**Comment by mapineda** [comment]
Is there a gCal where all planned events are listed? If so, is there access
to add events n' such?

On Sat, Jan 16, 2016 at 3:54 PM, Mateo Clarke <notifications@github.com>
wrote:

> The 2016 Strategic Plan
> <https://docs.google.com/document/d/12EGMSZL2wGKpxwcxCFCTMoeRfx95h4eF493Bh5kdkkA/edit?usp=sharing>
> is all but done. We should accept suggestions but let's try to get this
> sent to CfA by the end of the week.
>
> The main incomplete item is #62
> <https://github.com/open-austin/iced-coffee/issues/62> that is linked
> from the Strategic Plan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-austin/iced-coffee/issues/40#issuecomment-172260631>
> .
>



-- 
Marco Pineda
m | 314-401-2324

Author | "The Bitcoin Book: A Comprehensive Guide To Bitcoin"
Founder | Sanitation Project <http://www.sanitationproject.com>

Connect with me on Linkedin <http://www.linkedin/in/pinedamarco>
Follow me on Github <http://www.github.com/mapineda>
www.marcopineda.com

**Comment by VictoriaODell** [comment]
@mateoclarke looks good to me.

**Comment by VictoriaODell** [comment]
@mapineda there is this calendar: 
http://www.open-austin.org/calendar#events

I don't know how to add stuff but @luqmaan has.

**Comment by mateoclarke** [comment]
Sent to Monique at CFA.

We should not leave this document to die on the vine but refer back to it on a quarterly basis to see how our activities are aligning towards our goals.
