### ISSUE TITLE
Core Team Dec 2015 Huddle Agenda

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#41]
# Agenda

- Summary of Community Feedback
  - 2016 Budget & 2016 Strategic Plan #40
  - 2015 Annual Report
    - is this worth doing?
    - infographics
- Logo Feedback #2
  - ready to ship?
    - order tshirts #11 & stickers & buttons? #3
- Website Checkin
- Code Across
  - another ideathon?
  - or a Waffle.io style Hackshop event? http://blog.waffle.io/nc-open-data-hackshop/
- Core Team Roles
  - Fundraising position necessary? #13
  - outreach for Policy Lead? #9
    - draft role description:
      - help lead putting together the toolkits
      - come up with processes for getting newbies a policy 101
      - run lead on candidate questionaries for Nov'16 elections 
  - committees #21
- Meetup speakers #35
- Austin Monitor meeting
- ATX Hack 4 Change

**Comment by luqmaan** [comment]
# Agenda

- Summary of Community Feedback
  - 2016 Budget & 2016 Strategic Plan #40
  - 2015 Annual Report
    - is this worth doing?
    - infographics
  - Notes
    - small sample size, should've avertised on meetup.com
    - notes
      - what do you like about civic hack night?
        - breakouts and groups
        - diversity of skills and learning from others
        - the people
      - what kind of project pitches would you like to see?
        - well framed projects with owners to see them through
        - collaborations with other cities
        - social justice & income equality
      - what could open austin to better or differently?
        - engage with more groups
          - like hacks & hackers, data visualization
          - disadvantaged groups, attornies, data liasions, business stakeholders
          - co-author blog posts
        - follow through of our work
          - matchmaking project champions with orphaned ideas
          - analytics on projects
        - what do you like about open gov civic tech meetups?
          - discussion
          - non-hack topics like policy
          - socializing
        - what kind of presentations would you like to see?
          - ut researchers
          - skill sharing at the hack nights
          - lightning talks
          - data visualization
          - tech demos
          - policy + history
          - failure stories
        - what would you like to learn from this community?
          - technology skills
- What are our goals/strategy for next year?
  - 
  - our goals
    - continue to grow our community and create a comfortable space for people to come hack
      - to grow the community we have to know the community: create a cms
    - taking open data policy recommendations through the city council process
    - capitalize on the presidential election year
      - make sure voteatx.us works
    - consistency with our brand and message
      - one place to send people
    - more blogging and outreach to news organizations
    - foster community with the data liasons
    - contact local tech press and let them know we exist if they need a blurb    
- Public operations/admin/planning channel
  - Started #iced-coffee channel
  - coreteam should default to using that channel for planning
- Logo Feedback #2
  - ready to ship?
    - order tshirts #11 & stickers & buttons? #3
- Website Checkin
- Code Across
  - another ideathon?
  - or a Waffle.io style Hackshop event? http://blog.waffle.io/nc-open-data-hackshop/
  - Notes
    - yes another ideathon
    - want to hear ideas from other groups, like aura, 
  - Todo
    - [ ] Reach out to Diana, Lope about UX stuff
    - [ ] figure out sponsorship
    - [ ] figure out venue
- Core Team Roles
  - Fundraising position necessary? #13
  - outreach for Policy Lead? #9
    - draft role description:
      - help lead putting together the toolkits
      - come up with processes for getting newbies a policy 101
      - run lead on candidate questionaries for Nov'16 elections 
  - committees #21
  - Notes
    - Maybe fundraising position should be part of an events position. Make sure everything goes smoothly event wise. Money helps us do things, but the fear is we become a fundraising-driven organization.
    - What sort of committees would we need?
      - Marketing, Events, Policy
      - Maybe we don't need committes formally yet, lets see how our policy/fundraising positions go. Lets let them form naturally as we have needs.
- Meetup speakers #35
  - Notes
    - Mateo reached out to a few speakers
    - Really need someone for January
      - Maybe a skillshare/lightning talks?
      - Maybe innovation office?
    - Skillshare/Lightning talks
      - 10 minutes
      - 7:30 - 8:45
      - potential?
        - preston
        - kneetree
        - mscarey
        - mateo: policy 101
- Austin Monitor Meeting
  - Notes
    - 3 events/game nights in 2016, starting late half of 2016
      - technology
      - urban planning
    - at google fiber, 6-9pm
    - want us to be on the panel of judges
  - Todo
    - [ ] plan the event in more detail
- ATX Hack for Change Planning Meeting
  - Notes
    - meeting tomorrow, Vickie attending
    - talking points
      - share project-ideas repo with them
      - team formations on friday night was very unclear
      - food friday night was insufficient
      - skillshares friday at 2pm
      - mayor's speech was good
      - less talking more doing
      - the panel took away from people getting to connect to projects
      - reach out to more organizations
        - gis bash groups
        - python, ruby language specific groups
