### ISSUE TITLE
Open Austin Deck

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#42]
Once we get our logo finalized I'd like us to create a template deck for our future Open Austin presentations. 

To include: 
- styling for quotes, callouts, etc. 
- font sizes, weights, and styles

probably missing something but essentially just a good template to use and reuse for our standard presentations.

**Comment by mateoclarke** [comment]
I like this idea. Something like this right?
https://docs.google.com/presentation/d/1g5U9XzxXoZ-iolBMejqu9LmP8Zf6D9aHIf8Vxcuv7vw/edit

**Comment by VictoriaODell** [comment]
Yea! That looks like an awesome base.

**Comment by VictoriaODell** [comment]
I updated the deck from the last meeting so ya'll can copy/paste for future meetup decks: https://docs.google.com/presentation/d/1QvCowZBzfkhN-rAjH4I0kYSBQZUGDTAj5ey1KiF-Ris/edit#slide=id.p

The master slides are fixed too. 
To use the theme you can:
-  import it to any presentation from the [Open Austin Slide Deck](https://docs.google.com/presentation/d/1TvporjT9u0AZ_z61DSr-FdJ1gMXNXSrfa1xSebt0ZQ4/edit#slide=id.g791a9664a_01)
- Click layout
- Pick which layout you want on the slide.

**Comment by mateoclarke** [comment]
:+1: That looks great!

**Comment by mateoclarke** [comment]
I think this is complete so I'm going to close it out. We'll use the deck for the Feb library meetup!
