### ISSUE TITLE
Organize the Google Drive

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#49]
So many docs :scroll: :page_facing_up: 
I think we should get a little more structed as we move forward. It'll make finding resources and useful information easier, especially if new people join the team or we have role changes.

**Comment by amaliebarras** [comment]
Worked on this today! I narrowed it down to a few folders... I think it makes more sense now, but we can always work on it more.

**Comment by VictoriaODell** [comment]
Awesome. I tried staring at everything and became overwhelmed. X|

*Victoria O'Dell* | Visual Designer & Activist
*c:*469.951.1576  *e:*victoria.d.odell@gmail.com  *w:*victoriaodell.com

**Comment by mateoclarke** [comment]
This looks good to me, going to close this issue. 

Reopen if there is more work to be done.
