### ISSUE TITLE
Get projects ready for Ship It Weekend

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#5]
We need to get some projects ready for ship it weekend. This means having something specific and useful to work on for the weekend.

Ideally we should get projects to:

- Create 3 issues
- Label those issues with `Ship It Weekend`
- The issues don't need to be technical. Good stuff to work on:
  - user testing
  - marketing materials
  - design

Projects that were worked on in some way this year:

- [x] Austin Green Map - 3 issues opened https://github.com/open-austin/austingreenmap/labels/Ship%20It%20Weekend
- [ ] Bill Tracker - Contacted
- [ ] Pet Alerts - Contacted
- [ ] My Building Doesn't Recycle - Contacted
- [ ] Texas Appleseed - Contacted
- [ ] Budget In A Box - Contacted
- [x] Open Data Progress Report
- [x] Austin Park Equity
- [x] Transitime
- [x] Instabus
- [ ] Construction Permits
- [x] ATX OSM Buildings Import - Contacted
- [x] Open Austin Website
- [x] Open By Default Policy Campaign
- [ ] MyCreekATX - Contacted
- [ ] Preterm Baby Warmer
- [ ] Pedestrian Infrastructure Insights
- [ ] Change Is
- [ ] Public Input for Infrastructure
- [ ] Occupy the Lege
- [ ] Monstralia
- [ ] Council Connect
- [ ] Civic Engagement Management System
- [x] Digital Empowerment
- [ ] Lone Star Heritage Tourism Resource
- [ ] Lesson Plan Wiki App - Contacted
- [ ] Stolen Bikes Database - Contacted
- [ ] EcoNetwork Civic Education
- [ ] Show Us Your Austin
- [ ] 211 Data
- [ ] Budget Out of the Box
- [ ] Capmetrics
- [ ] City Path User
- [ ] City Path Policy
- [ ] Civic Tech Project Planning Canvas
- [ ] Council Connect
- [ ] Granny Flats
- [ ] Map My Broadband
- [ ] Noise Complaints
- [ ] Streamlined City Portal UX
- [ ] Zero Waste

**Comment by mateoclarke** [comment]
- The Innovation Office has done outreach to all the project champions from the ATX Hack for Change.
- I sent an email to all attendees of Code Across.

Through those two emails we should have touched most of our past projects. Now we should just follow up with specific projects that we want to prioritize and do our best to gather needs from project champions.

Also created a table of projects, and links. We should try to fill this out as much as possible.
https://github.com/open-austin/ship-it-2015
