### ISSUE TITLE
Banner 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#50]
Need to produce a banner

should be cake~

Logo/website on the banner!

Reference: 
<img width="886" alt="screen shot 2015-12-21 at 10 50 42 am" src="https://cloud.githubusercontent.com/assets/10767430/11936011/bff6c3a8-a7d0-11e5-803e-cb17f965b409.png">

**Comment by VictoriaODell** [comment]
@mateoclarke 
<img width="758" alt="screen shot 2015-12-21 at 8 43 21 pm" src="https://cloud.githubusercontent.com/assets/10767430/11946743/89081498-a823-11e5-82d6-b6154d754f79.png">

**Comment by VictoriaODell** [comment]
[Banner_OpenAustin.pdf](https://files.zenhub.io/5678b8ef5f72d5e3728b6777)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by mateoclarke** [comment]
nice! The banner looks great @VictoriaODell ! One minor suggestion is more spacing between the text and vertical piping at the bottom.

Also interested in your thoughts around the "Open Government, Open Data and Civic Tech in Austin, Texas" tagline. Do you think the order denotes priority. 

Further, I kind of see us as having 3 main missions.
1. promote open gov & open data
2. build things with government data, civic tech
3. create a community of tech-interested, engaged citizens. civic engagement for the 21st century.

But using those three key words in the tagline works really well and doesn't have to directly align with these missions which aren't super formalized (_yet_).

**Comment by VictoriaODell** [comment]
I sure can. Once I get off work I'll make updates and should be finalized. 

I think if we feel iffy on the tagline then we should nix it. We can work on our messaging more before we solidify it on things like this. 

I can change where it says the tagline to say " Established 2009 in Austin, Texas" 
Is there anything else you think should go in that footer section?

**Comment by mateoclarke** [comment]
Nah, I actually like the tagline the more I look at it. Why not roll with it? Was mainly just talking out loud to get us thinking...

**Comment by VictoriaODell** [comment]
Alright, well I'm just going to fix the text so it's not so close to the bottom and upload.

**Comment by VictoriaODell** [comment]
<img width="740" alt="screen shot 2015-12-22 at 5 18 41 pm" src="https://cloud.githubusercontent.com/assets/10767430/11968275/3cdddf50-a8d0-11e5-8175-8640c859362a.png">

Order banner from [here](http://www.vistaprint.com/studio.aspx?pf_id=017&combo_id=134749&xnav=Tablet+Banners+Product+Page)

Here is the PDF: 
[Banner_OpenAustin_OutlinedType.pdf](https://github.com/open-austin/iced-coffee/files/70316/Banner_OpenAustin_OutlinedType.pdf)

**Comment by mateoclarke** [comment]
![screen shot 2015-12-23 at 9 29 04 am](https://cloud.githubusercontent.com/assets/5697474/11979327/12ae5f1a-a958-11e5-89aa-4250944d2abe.png)

:shipit:
