### ISSUE TITLE
T-shirt

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#51]
Shirt design ASAP~
Ordering from [Custom Ink](http://www.customink.com/).

@mateoclarke "i think around $7-10 per shirt is good if we are ordering around 100 total" plus a nice link about ordering shirts [here](https://medium.com/art-marketing/your-4-t-shirt-is-costing-you-millions-829bf4a7e440#.pw14k3p00)

Currently looking at the Canvas shirts. Leaning torwards a dark grey with the logo in white.

**Comment by VictoriaODell** [comment]
Quick quote for 100 t-shirts with 1 color printed on the front: 
<img width="334" alt="screen shot 2015-12-21 at 10 19 59 am" src="https://cloud.githubusercontent.com/assets/10767430/11935247/725cbbb0-a7cc-11e5-8f04-7fa8e04da319.png">
@mateoclarke does that seem okay? Should I look at other shirts?

**Comment by VictoriaODell** [comment]
Playing around yesterday with some concepts and I'm thinking of a front/back design. Working to get this completed tonight.

**Comment by mateoclarke** [comment]
I think $11 is high for 1 color printed on the front, but i think we can afford it. Would like to see other options or at least more info on the type of shirt.

**Comment by VictoriaODell** [comment]
The shirt I picked for this was the Canvas one [here](http://www.customink.com/styles/canvas-tri-blend-t-shirt/242000#title-link)
I'll explore a few more options though tonight.

**Comment by VictoriaODell** [comment]
<img width="505" alt="screen shot 2015-12-23 at 5 52 24 pm" src="https://cloud.githubusercontent.com/assets/10767430/11987053/f47fde60-a99d-11e5-8703-74292cf95fc0.png">
Thoughts?

**Comment by VictoriaODell** [comment]
Also here is the link to the shirts [Shirts](http://www.customink.com/styles/next-level-tri-blend-t-shirt/186900#title-link)

**Comment by mateoclarke** [comment]
Like the color. White on grey looks good. The small logo off to one side looks nice but it also seems super simple. I'd kinda like to see a larger centered logo. $10 per unit is good too.

**Comment by VictoriaODell** [comment]
@mateoclarke 
<img width="503" alt="screen shot 2015-12-26 at 10 51 00 am" src="https://cloud.githubusercontent.com/assets/10767430/12007183/93ef7542-abbe-11e5-9ba3-6afda0fb74c4.png">
Here is the file for the white logo:
[OpenAustin_White_front.eps](https://files.zenhub.io/567ec59cbbfdbd437514b950)

**Comment by mateoclarke** [comment]
I kinda like the centered and bigger option. What does everyone else think?

**Comment by amaliebarras** [comment]
Bigger is better!

**Comment by mateoclarke** [comment]
Ok, going to go ahead and order the second option.

**Comment by mateoclarke** [comment]
@VictoriaODell, Do these look like good numbers to buy? Not seeing a women's option for Next Level Tri Blend. Maybe we get 50 Canvas Jersey V-Necks and 50 Next Level Tri Blend? Probably cost quite a bit more to do smaller volumes.
https://docs.google.com/spreadsheets/d/1FHADyiV88DAgHF6hn8a1sL6pLQBwuVY0ZTLK4M9Asko/edit#gid=0

<img width="504" alt="screen shot 2015-12-26 at 6 06 56 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008404/e0e70e84-abfd-11e5-9889-f71f61b89a65.png">

**Comment by VictoriaODell** [comment]
We should probably get Xsmall(a few) and 2XL for both women and men @mateoclarke

**Comment by VictoriaODell** [comment]
uh, which shirts have "women's options"?
Also, I think we should more evenly distribute to large/extra large.

**Comment by mateoclarke** [comment]
I went of the percentages that the [Josh Baer article](https://medium.com/art-marketing/your-4-t-shirt-is-costing-you-millions-829bf4a7e440#.pw14k3p00) recommended.

There are some shirts that are have a "women's fit" but maybe that is a separate shirt option. I was just trying to follow the advice of the article.

**Comment by mateoclarke** [comment]
60 Crew Necks & 40 V Necks. Any objections?
<img width="514" alt="screen shot 2015-12-26 at 7 01 25 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008466/2842efa0-ac03-11e5-9f76-025b681a7e83.png">
<img width="507" alt="screen shot 2015-12-26 at 7 01 35 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008467/284af9e8-ac03-11e5-83d2-ce644a7a043c.png">

**Comment by mateoclarke** [comment]
<img width="715" alt="screen shot 2015-12-26 at 7 41 29 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008585/324b5872-ac0b-11e5-9f40-f534ea9eb9cd.png">

**Comment by mateoclarke** [comment]
<img width="546" alt="screen shot 2015-12-26 at 7 54 18 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008589/7150d8e4-ac0b-11e5-8bab-ac51ad6aead7.png">

Final cost with tax

:shipit:
