### ISSUE TITLE
1/3 2015 in Review Blog Post

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#52]
All the cool kids are doing it so we should to:

- http://www.codeforamerica.org/blog/2015/12/22/this-year-in-civic-tech-2015-in-review/
- http://chihacknight.org/blog/2015/12/22/chi-hack-night-2015-year-in-review.html
- https://medium.com/@CodeForMiami/the-year-in-review-for-miami-civic-tech-2015-7b8a6e397279#.p5kpumcoj

This could benefit from a completed infographic #43.

**Comment by amaliebarras** [comment]
k. I plan to get this done by 1/3,  coreteam agreed that was an okay deadline at the huddle. is it still?

**Comment by mateoclarke** [comment]
Sounds good!

**Comment by VictoriaODell** [comment]
Do we know all what we should put on it?

**Comment by amaliebarras** [comment]
There is a list in the github issue. but if you have anything to add, have at it

**Comment by mateoclarke** [comment]
Think this should be the first blog post once the site is live. Would make sense to make use of the Infographic in this post. #43

**Comment by VictoriaODell** [comment]
Maybe next year? ~
lol maybe if we have a b-day or something we can try this again.

**Comment by amaliebarras** [comment]
Nooooo :( 

Haha it’s okay, something to build on for next year. :)

Ams

**Comment by mateoclarke** [comment]
I think we should still post it.

**Comment by mateoclarke** [comment]
first day of spring! is that a good enough reason to post it?
