### ISSUE TITLE
OA Stickers

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#53]
We got the logo! Let's decide what stickers we want and how many and order them through StickerMule.com ASAP!

I think [clear stickers](https://www.stickermule.com/products/clear-stickers) would look great with our base logo. Also like the idea of an orange [circle sticker](https://www.stickermule.com/products/circle-stickers) to match the orange button.

Maybe we get two styles/sizes? What are you thinking @victoriaodell?

**Comment by VictoriaODell** [comment]
Yeah, We can do what we did with the buttons.

**Comment by VictoriaODell** [comment]
I think we should do small [1 inch](https://www.stickermule.com/products/circle-stickers) stickers similar to the buttons in orange. 
[OpenAustin_Sticker_1Inch_Orange.pdf](https://github.com/open-austin/iced-coffee/files/71346/OpenAustin_Sticker_1Inch_Orange.pdf)

<img width="300" alt="screen shot 2015-12-23 at 6 37 56 pm" src="https://cloud.githubusercontent.com/assets/10767430/11987409/5776c0fa-a9a4-11e5-9b18-d72bc3223424.png">

Working on mockup up the clear sticker.

**Comment by VictoriaODell** [comment]
Also, we should def get the stickers all at once for that discount~

**Comment by VictoriaODell** [comment]
Okay, [clear sticker](https://www.stickermule.com/products/clear-stickers) of our full color logo. I think we should order them 2"x2" if we opt for the above 1"x1" to compliment. Let me know if any adjustments should be made. 
<img width="357" alt="screen shot 2015-12-23 at 8 25 39 pm" src="https://cloud.githubusercontent.com/assets/10767430/11988323/5d30bf3c-a9b3-11e5-86e0-c5d0d017a8cb.png">


[OpenAustin_Sticker_logo_Clear.pdf](https://github.com/open-austin/iced-coffee/files/71388/OpenAustin_Sticker_logo_Clear.pdf)

Let me know if any adjustments should be made.

**Comment by mateoclarke** [comment]
At first I thought 1x1 & 2x2 seemed super small. Was thinking 1in and 3in would be better, but now I'm not totally sure. The full logo being 3 inches wide and a little less than that on the height seems good. The 1 inch circle would be nice though. Like that size.

<img width="456" alt="screen shot 2015-12-24 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/5697474/11996739/8709f284-aa2f-11e5-85f6-7e56856e4f76.png">

**Comment by VictoriaODell** [comment]
@mateoclarke So why don't we do the 1inch round and then make the clear one 3inch?

If that's fine you can go ahead and put the order in with the above pdfs .

**Comment by mateoclarke** [comment]
on it!

**Comment by mateoclarke** [comment]
ordered

<img width="1000" alt="screen shot 2015-12-26 at 8 45 37 pm" src="https://cloud.githubusercontent.com/assets/5697474/12008662/ae2b683c-ac11-11e5-8ceb-ac64203eee1a.png">

:shipit:
