### ISSUE TITLE
Instabus Stickers

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#54]
@luqmaan and I talked about buying Instabus stickers with the extra CfA budget. We gotta do that asap. Might as well bundle the order with #53. 

"There is no need to bus upset"
Unicorn :unicorn_face: 
Instabus.org

**Comment by VictoriaODell** [comment]
Speaking of Instabus and marketing stuff, how is that going?
I think this is a really cool thing and we should get some more material/info out on that.

**Comment by mateoclarke** [comment]
![](https://raw.githubusercontent.com/luqmaan/instabus-stickers/master/instabus-sticker.png)
https://github.com/luqmaan/instabus-stickers/blob/master/instabus-sticker.png

**Comment by mateoclarke** [comment]
ordered :shipit:
