### ISSUE TITLE
Update Logos across the web

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#56]
- [x] Twitter
- [x] Facebook
- [x] Website
- [x] Github

Did I miss anything?

**Comment by mateoclarke** [comment]
Just updated Github...

**Comment by VictoriaODell** [comment]
@mateoclarke I had trouble trying to figure out Wordpress.

**Comment by mateoclarke** [comment]
Just added it to Meetup.com which we had left out.
