### ISSUE TITLE
Open Austin New Logo Blog Post

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#57]
I'm updating the slides now and would like to translate them into a blog post.

**Comment by VictoriaODell** [comment]
Posted in wordpress as a draft! 
Can someone review it for me? 
@mateoclarke @amaliebarras @luqmaan

**Comment by mateoclarke** [comment]
Hey @VictoriaODell, just saw this now. Great job!

I fixed the embedded slideshow. It wasn't working with that wierd Wordpress shortcode thing. Not sure how that is supposed to work so I just used the <iframe> embed option instead.

Scheduled it to publish Monday morning at 9am. Feel free to change that time.
