### ISSUE TITLE
[Code Across] Register event with CfA

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#59]
Cfa has a registration form so they have an accurate list of all the brigades participating.

https://cfa.typeform.com/to/rvfNMX

The main thing we need to do first is create an event URL.

**Comment by VictoriaODell** [comment]
Would we want this to be an Eventbrite page?

**Comment by mateoclarke** [comment]
yeah eventually, but I don't think it matters too much for this registration page. It would probably be best to create page like open-austin.org/codeacross2016 which would have an event description and links to an eventbrite.

**Comment by VictoriaODell** [comment]
Did you regsiter us @mateoclarke

**Comment by mateoclarke** [comment]
REGISTERED!
![screen shot 2016-02-17 at 11 29 56 pm](https://cloud.githubusercontent.com/assets/5697474/13134649/6c439700-d5ce-11e5-8630-5c4148c8c1a1.png)
