### ISSUE TITLE
Share lightning talk slides

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#60]
Share them on our website and post to Meetup.

• [Matt Carey, OA Policy Lead](https://github.com/mscarey) - [Free Law on the Web](https://github.com/open-austin/iced-coffee/files/88240/Law.on.Web.slides.pdf)
• [Preston Pham](https://github.com/prestonp) - [Leaflet Primer: Developing with Open Source Web Maps](http://open-austin.github.io/leaflet-talk/)
• [Gus Ireland](https://github.com/gusIreland) - [Mapping with Urthecast](http://gusireland.github.io/urthecast-api-presentation/)
• Angela Hanson, Innovation Office - [Productive Brainstorming and Issue Framing](https://prezi.com/hqtbt_jtme2y/innovation-method/)
• [John Clary](https://twitter.com/spatialaustin) (and others) - [Austin Code](https://github.com/open-austin/iced-coffee/files/88242/ACD.Presentation.To.Open.Austin.Jan.2016.pdf)
• [Chris McConnell](https://twitter.com/McCnnll) - [Open Records In Texas](https://github.com/open-austin/iced-coffee/files/88241/OA_OpenRecordsInTexas.pptx)

**Comment by luqmaan** [comment]
I scheduled a basic blog post to be published on Jan 13, 2016 @ 12:36. Feel free to change it. https://www.open-austin.org/wp/wp-admin/post.php?post=1685&action=edit

**Comment by mateoclarke** [comment]
Thanks for doing that @luqmaan! Added some images from twitter, intro slides link and a little elaboration about the topics covered.
