### ISSUE TITLE
Update US City Census entries

### ISSUE THREAD

**Issue by wilsaj** [open-austin/iced-coffee#61]
A lot of Austin entries in the Open Knowledge Foundation's US City Census could be updated: 
http://us-city.census.okfn.org/place/austin

Notably:
- All datasets on the data portal or GIS FTP site are in the public domain, so the licensing column can be cleared up.
- Some of these datasets that were previously missing have been added to the data portal in the past year, so finding them and updating those would be great.

**Comment by mateoclarke** [comment]
Maybe this would be better under the project-ideas repo? Would be nice to start a collection of beginner friendly projects and tutorials we could point ppl at.

**Comment by mateoclarke** [comment]
Closing this out bc its old. But I did start an new issue thinking about beginner friendly projects we could point ppl at. #202
