### ISSUE TITLE
Fill out Brigade Prospective Programs/Projects/Events

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#62]
Document is here [Brigade Prospective Programs/Projects/Events](https://docs.google.com/spreadsheets/d/1icv29i4w0AcUKWs8klku5ciusWFesm2WVxaE9kFh59c/edit#gid=1193001767)

We need to get it filled out with everything we know now and then commit to updating it as needed.

**Comment by VictoriaODell** [comment]
@mateoclarke I put the document in our Open Austin Google Drive already too.

**Comment by amaliebarras** [comment]
Business Partners: 
What are our goals with these? I feel like lots of IBMers have shown interest in what we're doing, could they be a potential business partner too? 

Looks gorgeous and thorough: here are some thoughts we could add.

Membership goals: 
Also want to make a note on there about using the data we're already collecting around members skills / topic interests. Probably a couple more months and we'll have a somewhat significant sample to start analyzin'. 

Projects & Activities: It would also be cool to have a goal of tracking skills and topic components of the projects somewhere so we can help people find projects that they want. And if we notice a gap, that would help me target the growth efforts later in the year. 

Budget: Do we need a line item on here for hosting / servers / software licenses or anything like that? Or is the assumption that we can get those things in-kind

**Comment by mateoclarke** [comment]
Including some of Amalie's ideas in the Strategic Plan. Luqmaan filled out enough of this project document and I sent the Strategic Plan to CfA. We're good on this.
