### ISSUE TITLE
Event NanoSurvery

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#63]
We need to create a 2 question survey to pass out after each of our events to collect feedback. 

Surveys should be anonymous and ask 2 questions: 

1. What did you like about tonight's' meeting?
2. What didn't you like about tonights meeting?

Let's try to get these 4 or so to page so we can save some trees.

**Comment by amaliebarras** [comment]
Would it be alright if we changed question two to "what would you do differently?" that way we can involve the community in solutioning?

**Comment by VictoriaODell** [comment]
:+1:

**Comment by amaliebarras** [comment]
[NanoSurvey.pdf](https://github.com/open-austin/iced-coffee/files/114977/NanoSurvey.pdf)

Assigning to Vickie to proof and/or print!

**Comment by VictoriaODell** [comment]
Solid! 
I'll work to get these printed.

**Comment by mateoclarke** [comment]
i like

**Comment by VictoriaODell** [comment]
Closing this. We have them now just need to upkeep~
