### ISSUE TITLE
Demographic Survery

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#64]
We need to recognize the skill sets and types of volunteers we are lacking through a demographic survey:

CFA has a good survey that we could reference: https://cfa.typeform.com/to/BEKp9Y

This will help us see how we can better market ourself to reach those people who aren't currently coming.

**Comment by amaliebarras** [comment]
So our current survey does actually ask about skill sets and interests. Was there something else within those categories that these questions don't cover?

Totally get that demographics is a super important dimension to look at for diversity and inclusion reasons. Do y'all think we should have a separate survey for this? Or add it to current survey? I'm worried that too many questions would be a deterrent for people filling out the OA Membership survey.

**Comment by mateoclarke** [comment]
With Caroline P O'Meara, the UT grad student interested in collected data about our brigade, maybe this is a good time to revisit how and when we do intake info on skills, motivation, and demographics.

**Comment by VictoriaODell** [comment]
What if we put a survey in front of our slack invite?

**Comment by mateoclarke** [comment]
Interesting idea. Adds some friction to getting plugged in on Slack. But I can see the benefit.

What about existing slackers?

**Comment by VictoriaODell** [comment]
We can post it in slack.
Send out an email for it and include it in our event emails.
Tweet + Facebook.
Make sure that it's posted on our Meetup page. 

And also probably go around and check if people have taken it at hack nights and Saturdays?
That's kind of it. We just hope they see it and we catch them?

**Comment by amaliebarras** [comment]
Totally. I’ll dive in to this more on Saturday.

**Comment by mateoclarke** [comment]
Did we ever get results from Caroline O'Meara on her survey? 
It feels like we are doing a good job in reaching out to a diverse crowd but how do we quantify diversity and should we be setting goals? Is a survey the best way to do this?

**Comment by amaliebarras** [comment]
I reached out to her today to ask! Will update this thread if / when she responds

**Comment by amaliebarras** [comment]
Sent an email to y'all with her survey. She won't be sending the quantitative data but it's a very insightful paper. Please keep internal for now.
