### ISSUE TITLE
Create News Contact List

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#67]
We need to ceate a list of news contacts so that we can proactively reach out them letting them know we are available to give quotes related to civic tech & city gov tech.

**Comment by VictoriaODell** [comment]
I created a master contact list we just need to get some contacts on it! 
https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=516533352

Closing this but we need to input our contacts~

**Comment by mateoclarke** [comment]
Chip actually had created a press list here: https://docs.google.com/spreadsheets/d/1qyglFdsLeC4JMhWsPCupEBGwn9fLp12CXsdK59JgEpU/edit#gid=0

Going to move over some of this info into the new contact list

**Comment by VictoriaODell** [comment]
:star2:
