### ISSUE TITLE
Civic Hacking Roadmap

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#69]
Part of our goals are to communicate and clarify what our process is for moving projects through the pipeline. This will make it easier for people to navigate from idea to hack team to production. 
- [x] _In Process:_ Gather resources & Insite. What would best serve others, how can it best be distilled, where can it be presented?
- [ ] Draft roadmap
- [ ] Feedback
- [ ] Implement feedback/ Draft again
- [ ] Publish 

Great starting content: [Brigdate Organizers playbook from Code for America](http://www.codeforamerica.org/brigade/static/playbook_v1_nov2015.pdf). I like that it's an interactive PDF. 

Collecting concise notes [here](https://docs.google.com/document/d/1YaxGxQXbgIS9KJeevQH-rnhG_MKhxBAUTqtuCHbGUTc/edit#heading=h.dpbxl9x4lbvc)

**Comment by VictoriaODell** [comment]
[The Project Canvas](http://www.open-austin.org/wp-content/uploads/2015/03/project_canvas_v4-FINAL.pdf) is a stellar start. It ask all the appropriate questions for beginning a project and thinking about the life of it. I think we can make it in a way that breaks the parts down a little better and makes it available to fill out digitally.

**Comment by VictoriaODell** [comment]
I signed up for a design course with friends but was unable to complete it because of the time-commitment and timing. My friends had similar issues. I did save the coures material though might be good to look through and reference. 

[Human-Centered Design](https://drive.google.com/open?id=0BwKb2oghmQldcXdOVmg0a1NMWEk)

**Comment by VictoriaODell** [comment]
The workshop Mateo shared is great [slides 8-15 have a good starting point on what to do to start finding problem owners](https://docs.google.com/presentation/d/1-0-6YWDLOaQhjP0-PbxNhtF1k_7ZLM95JOWzY_1Jhek/edit#slide=id.gece7a391a_0_28).

**Comment by VictoriaODell** [comment]
**Onboarding new members to projects** [Video](http://forum.codeforamerica.org/t/2015-february-5-brigade-discussion-onboarding-new-members-to-projects/140) Note: for some reason the video stopped for me.

**How to welcome new coders to a civic hackathon**
[This one is my favorites so far though.](https://18f.gsa.gov/2015/04/03/how-to-welcome-new-coders-to-a-civic-hackathon/) 18F put together a nice document. 
I really like this 

> Added a section on how non-coders could have helped each project. It’s worth thinking about and then articulating — in writing — how people with other areas of expertise or knowledge can help during a hackday. If you don’t have time to write these issues out, you can open an issue that asks for someone to interview you about them. Voila! Problem solved.

**Comment by luqmaan** [comment]
Another thing we can do is ask people who open a project idea to come do a 5-minute pitch at the civic hack nights.

**Comment by mateoclarke** [comment]
Here is how OpenOakland describes their process: [PDF](http://www.openoakland.org/wp-content/uploads/2015/11/OpenOakland-Projects-04.pdf)

**Comment by luqmaan** [comment]
That PDF is a great starting point. Can we copypasta that text onto our site?

**Comment by mateoclarke** [comment]
Two options I see:

1) I could see some of this onboarding info going into a new section on the `/projects` page:
http://open-austin.github.io/open-austin-org/projects/

Regardless, I think we should move the "Project Status" section below the Project Gallery but add a table of contents/anchor tag links to "Project Status" and "X Steps to Leading a Project".

2) Alternatively, we could create a page more focused on how to get involved on projects instead of showing them off like a project portfolio (which is currently the focus of /projects

ie: https://github.com/open-austin/open-austin-org/issues/8

**Comment by VictoriaODell** [comment]
1)Yeah, I could see some of this on the /projects page or maybe living in a blog post. I think we could benefit a lot from looking at this and making one unique for Open Austin. Also, this is specifically about leading a project and I'd like to see a partner to it about how to contribute. I think that is where [BASEDEF](http://begriffs.com/posts/2016-01-29-making-twenty-percent-time-work.html) fits in. 

I also agree that adding some anchor tags and links would be good. Sticky nav may help jumping around. 

2)We should def look more into creating an in-depth projects page and I think that correlates with fleshing out the roadmap. There are a few things people may want to do with projects(Am I missing something?). 
- **Learn** more about what kind of projects there are/ how they work/the process
- **View** the different projects
- **Contribute** to a project
- **Purpose** a project
- **Ask** a question.

And that echos some comments @mateoclarke made in [open-austin- projects page issue](https://github.com/open-austin/open-austin-org/issues/8)

>It should include a link to see all the projects we've done. **View** 
It should point people to projects/issues they can contribute to. **Contribute**
It should explain why we github/open source. **Learn**
It should point to resources like data.austintexas.gov. **?This would be pointing to resources.I didn't initially think about this but think it's important if we want people to see us as a hub~**

I think there are a few ways we can move forward with a more comprehensive Projects section and roadmap. I'd love to brainstorm. 

I input the PDF from Open Oakland into a goog doc [here](https://docs.google.com/document/d/1QvssEVp0K51qePEDouD2USfnXmmysiSWT6B0aGrH-Yk/edit?usp=sharing). 

Hope all that makes sense. :monkey:

**Comment by mateoclarke** [comment]
This is a good thread. I think we should revisit this after our Dec 18 Leadership Retreat and looking into 2017

**Comment by werdnanoslen** [comment]
I think the current work on this subject are captured in those issues :point_up: , so I'm closing this one.
