### ISSUE TITLE
Fill out Prospective Project & Events Google Spreadsheet

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#70]
https://docs.google.com/spreadsheets/d/1icv29i4w0AcUKWs8klku5ciusWFesm2WVxaE9kFh59c/edit#gid=1193001767

**Comment by VictoriaODell** [comment]
@mateoclarke I already made that an issue.

**Comment by VictoriaODell** [comment]
#62

**Comment by mateoclarke** [comment]
oops
