### ISSUE TITLE
Update/revise Open Austin Advocacy Agenda for 2016

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#73]
Chip (@chip-rosenthal) made this really nice list of Open Austin Advocacy Agenda Items back in July 2015.
https://docs.google.com/document/d/12LhAoZYSO4gRmGDrcMmQiu1PExepkXvdrZ2v3N6UdT4/edit#heading=h.8etlohtj8lub

A handful of these items have moved forward, others need new focus. Can we take some of the [Policy priorities](https://docs.google.com/document/d/1SAwpRkuTDZamxTHlxL_WJlpJ573yRu36OR8cCExYxRg/edit?usp=sharing) we've received from our members and distill them into a list like this?

**Comment by mscarey** [comment]
Here are what I see as the most actionable suggestions in the Open Data Priorities document. Any feedback on whether we should add or subtract any requests from this list?

1. Centralized ticketing systems for citizen request for information about datasets published through Socrata.
2. Survey data collected by, or on the request of the City should be “Open by Default,” meaning the data should be made publicly available and accessible in appropriate formats including raw data, data maps, questionnaires, details about survey methodology
3. Survey data should include demographic questions, but should not capture any personally identifiable information.
4. Release 3-Year Open Data Inventory: a publicly available inventory of all datasets, which should specify which department is owner of the data, a description of the dataset, and a release/update schedule.
5. Campaign finance: release lobbying and dark money disclosures as open data.
6. Release city council agendas as open data (probably by converting the agenda management system from SIRE to Legistar).
7. Advance Open Government Resolution to Ordinance.
8. Charge data-creating agencies with recommending an appropriate citation form.
9. (If I get the drift of the cited Medium article) The city should use a "digital first" strategy for collecting data so it will be easy for the city to release and update its open datasets with new records.
10. Convert the Open Data Progress Report to an Open Data Dashboard, like New York's.

**Comment by mateoclarke** [comment]
@mscarey this is a great list! :tada:  Thanks! 

As a next step, let's move these items into a Google Doc (maybe in the style of this [Recommendations doc](https://docs.google.com/document/d/1ZAGcMuLitb0MRjRk8UZKNvm2flc_lGq29KDcur7Kr4I/edit?usp=sharing)).

We can add some supporting info under each Recommendation and start circulating it to City Council Members, Committees and Boards, and revising it as we learn more. Once we have some talking points, I'll feel like we have more ammo to take into meetings. :muscle:

**Comment by mscarey** [comment]
Here's a [new Advocacy Agenda document](https://docs.google.com/document/d/1G-2yEphw1igKpaFQfSwPevWH3mMOACav9n-tDBViDro/edit?usp=sharing). Most of this material was adapted from [last year's policy priorities](https://docs.google.com/document/d/1HJBP3FHDU4mxYzSy6XRC6BwL5WcRNFW5n-4uSmJvRyo/edit?usp=sharing), from the [community engagement task force document](https://docs.google.com/document/d/1ZAGcMuLitb0MRjRk8UZKNvm2flc_lGq29KDcur7Kr4I/edit?usp=sharing), or from the ["discussion/commenting" Google doc](https://docs.google.com/document/d/1SAwpRkuTDZamxTHlxL_WJlpJ573yRu36OR8cCExYxRg/edit?usp=sharing).

**Comment by VictoriaODell** [comment]
Beautiful~ :two_hearts:
