### ISSUE TITLE
Tweet about Projects that need help

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#75]
Go through project idea repo and identify open issues and help-wanted to schedule tweets. 

Link to issues/project main page.

**Comment by mateoclarke** [comment]
:+1:

**Comment by mateoclarke** [comment]
This is a good idea, but it takes more work than it seems and we didn't do it all year so it can't be that important. 

I think discussing a roles around project connecting and project management would help with this and could be a strategy that individual chooses. Burying this as a good idea that could come back to life.
