### ISSUE TITLE
[Code Across] Make "Civic Hacking 101" better

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#78]
I made this presentation in like 5 minutes. Its not very good, and we ask every new person that comes to a Civic Hack Night to listen to it.

"Let's Make 'Civic Hacking 101' Great Again!"

![](http://media0.giphy.com/media/xTiTnlYp7fOmTLD0Yw/giphy.gif)

**Comment by mateoclarke** [comment]
https://docs.google.com/presentation/d/1EylkNx3IjwPy3ow2NsmgxHSeG_I9cxAGbKTILoeV-Lo/edit?usp=sharing

**Comment by VictoriaODell** [comment]
I'll be making edits at this link:
[Civic Hacking 101 Edits](https://docs.google.com/presentation/d/1tceKempW_8ZoxzeGcfuC1K96kBz0zaMkBxmT1pgv1bo/edit?usp=sharing)

**Comment by luqmaan** [comment]
Lets talk about BASEDEF since it shows the many ways you can contribute to an open source project. http://begriffs.com/posts/2016-01-29-making-twenty-percent-time-work.html

**Comment by VictoriaODell** [comment]
:+1:

**Comment by VictoriaODell** [comment]
Making progress on this:https://docs.google.com/presentation/d/1tceKempW_8ZoxzeGcfuC1K96kBz0zaMkBxmT1pgv1bo/edit#slide=id.gd22b63b33_0_12

Still need to input BASEDEF but I'm combing through now with some edits. If ya'll have any suggestions write comments.

**Comment by VictoriaODell** [comment]
At a stopping point on this for tonight: https://docs.google.com/presentation/d/1tceKempW_8ZoxzeGcfuC1K96kBz0zaMkBxmT1pgv1bo/edit#slide=id.p

@luqmaan BASEDEF is an awesome add. :+1: 
@mateoclarke you've been giving these presentations. Can you review?

**Comment by mateoclarke** [comment]
Yeah these improvements are great. Let's plan to use this moving forward. I'd also like to eventually do a narrated screen capture of this slide deck to post as a video to the website.

**Comment by mateoclarke** [comment]
Oh, not sure how this fits into use for a CodeAcross workshop because that is on Sarah S and Keith C to decide. But I'll share this link with them and tell them we can help.

**Comment by mateoclarke** [comment]
Going to close this out for now. We may need to repurpose this a bit if ATXH4C wants to use this for a pre-hackathon workshop but this is already a big improvement.

**Comment by VictoriaODell** [comment]
Sweet. 
I'd like to do an iteration of this specifically geared towards designers. I'm sure other groups could benefit towards tailored presentations but that's a further out thought.
