### ISSUE TITLE
[Code Across] Set up eventbrite page

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#81]
Set up eventbrite page

**Comment by mateoclarke** [comment]
Sarah Sharif from St. Ed's wanted to be looped in on this. We talking about how to make the registration process between Code Across and ATX Hack for Change as seamless as possible.

**Comment by mateoclarke** [comment]
invited her to the 2/2 Civic Hack Night.

**Comment by mateoclarke** [comment]
Added the event to the OA Google calendar.

**Comment by mateoclarke** [comment]
Could we just use Meetup for registration? I guess one negative is they don't have as good export features for email and participant info as Eventbrite. In the past, we've made a Meetup page which is mainly to notify ppl, and then we ask them to go somewhere else (like Eventbrite) to register. That feels clumsy. But maybe its best.

**Comment by mateoclarke** [comment]
waiting on St Eds to confirm venue before setting this up. But we need to do this ASAP.

**Comment by mateoclarke** [comment]
http://codeacrossaustin2016.eventbrite.com
