### ISSUE TITLE
[Code Across] Write up in-depth program

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#84]
Goals

1. Reach out to non-profits, designers and people who we are interested but don’t wan’t to come  to hack nights. Involve the people that wouldn’t normally come to hack nights. People that have problems we can solve.
2. Have project ideas / problem statements for teams ready to start building things around. For example a design document for how to represent an intersection or a styleguide for the city. But we need to encourage people to think beyond just an app.

Program

1. Speaker(s)
2. Breakout into groups based on themes. See https://www.open-austin.org/article/1484. Come up with problem statements and prioritize.
3. Speaker
4. Breakout civic hack canvas
5. Group presentations
6. Closing statement. Open Austin project pipeline.

**Comment by VictoriaODell** [comment]
[Took this document](https://docs.google.com/document/d/1b1ng9rSpwC1NauI4-mpGEbi1sKDh1Cvc8sghOB3c5Gk/edit#) from last year and am writing comments/working on updates to language and process.

**Comment by mateoclarke** [comment]
A format for interactive brainstorming to consider incorporating:

CityCamp:
http://citycamp.com/oakland/
https://docs.google.com/document/d/1AWfTSB1MMbWCdgzuESQF4izY8vKBxRAC_Afch-8uRCQ/edit#
http://www.citycamp.govfresh.com/start-a-camp/

**Comment by mateoclarke** [comment]
Vickie & I got a draft agenda started today:
https://docs.google.com/document/d/18WwQ0ttA_M73nk16jkCcU7afIGPZjkkXOBNxOPmFPB8/edit?usp=sharing

**Comment by VictoriaODell** [comment]
Updated these today

[Playbook](https://docs.google.com/document/d/18WwQ0ttA_M73nk16jkCcU7afIGPZjkkXOBNxOPmFPB8/edit#heading=h.k7gl8vcc11u5)
[Program](https://docs.google.com/document/d/1zg3RE5ue203FxL01eSn3m3Nx81IdZs0TUz6YPnfymA4/edit#)
