### ISSUE TITLE
[Code Across] Food sponsor

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#85]
Find sponsors. We would like to provide lunch, snacks, post-its, etc.

Sponsorship Outreach ([contact info](https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit))
- [x] Google Fiber (providing $1,000 via donation)
- [x] Socrata
- [ ] USAA
- [ ] Atlassian
- [x] General Assembly UX
- [ ] Bloomfire
- [ ] IBM Design
- [x] Rackspace
- [ ] Booz Allen
- [x] Github via [this issue](https://github.com/benbalter/feedback/issues/14)
- [ ] more...

**Comment by mateoclarke** [comment]
[Potential 2016 Sponsors](https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit)

**Comment by VictoriaODell** [comment]
Here is the [Sponsor Prosepctus for 2015](https://docs.google.com/document/d/1-XSgvvxjTKrAida_T_OfNNsRi-onkNyhyOkqdroZMcI/edit) I copied over into the 2016 folder. We need to update it.

**Comment by mateoclarke** [comment]
haha, we're duplicating work. I already started a similar one-pager/prospectus.
https://docs.google.com/document/d/1Uuepsj7Ssx4Wo2fQ_IbZ3u1q0d77vIQJk1sKS_Nr7UA/edit?usp=sharing

**Comment by VictoriaODell** [comment]
@mateoclarke where was the link at though?!!

**Comment by mateoclarke** [comment]
¯\_(ツ)_/¯

**Comment by mateoclarke** [comment]
I did my first pass. Rip it up!

**Comment by mateoclarke** [comment]
Going to start sending out emails tomorrow and Friday. Have a look and make suggestions if you haven't already.

**Comment by mateoclarke** [comment]
Note to self: To #38 as a part of this

**Comment by mateoclarke** [comment]
Sent emails to folks at Socrata and Google Fiber and cc/ed Marco. Added a checklist to the issues description [:arrow_up: at the top] of other good targets. Think we wait to target more technical product companies and bootcamps for events more aimed at coder audiences (like civic hack nights)

Going to let you take it from here @mapineda

**Comment by mapineda** [comment]
Thanks @mateoclarke reached out to Rackspace today, waiting for a response.

**Comment by mateoclarke** [comment]
@mapineda, heard back from Ben Balter form Github. You mind filling out this form?
https://community.github.com/r/benbalter

**Comment by mapineda** [comment]
Traditional sponsorship request seeking money?

**Comment by mapineda** [comment]
Filled out the form and submitted.

**Comment by mateoclarke** [comment]
nice, thanks man!

**Comment by VictoriaODell** [comment]
@mapineda any updates? Should we close this or reach out to more sponsors? 
We will probably have enough budget but may be cutting it close. A couple $100 sponsors would be awesome.
