### ISSUE TITLE
[Code Across] Set up Code Across committee

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#87]
We briefly talked about this, but I'm not sure what specific steps we need to take for it.

**Comment by mateoclarke** [comment]
We decided this would start with a huddle at the Hack Night on Tuesday. @VictoriaODell is going to invite some UX folks from the Design meetup. If enough people are interested in doing a break out on this, we'll form the committee then, or schedule another time to discuss the event planning.

**Comment by mateoclarke** [comment]
this didnt really get off the ground. closing
