### ISSUE TITLE
[Code Across] Location sponsor

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#88]
We need a venue! We have some outlined [here](https://docs.google.com/document/d/1bVXYSpO5J7xV9blq-pUVIuxj568JhSHYxr9pk-lKgfA/edit)

### Some options (checks indicate we've reached out):
- [x] St. Ed's Munday Library (Sarah is running point on this)
- [x] Capital Factory (Sarah has a spaced reserved as a backup plan but it will cost.)
- [x] WeWork/GA (@mapineda is having the discussion)
- [x]  Object Rocket/Rackspace (@mapineda)
- [ ] Galvanize (concerned their facilities might not be available)
- [ ] Iron Yard (may have to do table/chair rentals. Sounds like they have landlord and construction issues that won't fit our timeframe.)
- [x] [Livestrong](http://www.livestrong.org/who-we-are/our-history/our-home/tours-community-space/) (@mapineda)
- [x] ~~City Hall, Boards and Commission Room. (Daniel Honker from CoA innovation reached out. unavailable)~~
- [x] Vuka/Impact Hub Austin. (Booked 3/5 but maybe a different date.)
- [x] Asian American Resource Center Ballroom (kinda north, booked 3/5, maybe a different date)
- [x] ~~Zilker Botanical Garden. Daniel Honker from CoA innovation reached out. (booked)~~
- [x] ~~Google Fiber space (booked)~~
- [x] ~~Carver Library (booked)~~

**Comment by mateoclarke** [comment]
I've emailed Dave Waldron & Sarah Sarif at St Ed's. cc/ed Marco too.

**Comment by mateoclarke** [comment]
Dave Waldron responded back. He's agree St Ed's would be a good host. He's checking availability.

**Comment by mateoclarke** [comment]
Some options:
- [ ] [Livestrong](http://www.livestrong.org/who-we-are/our-history/our-home/tours-community-space/)
- [ ] WeWork/GA
- [ ] Galvanize
- [ ] Iron Yard (may have to do table/chair rentals)
- [ ] City facility like Jones Building Room 400A or Boards and Commission Room?
- [ ] Vuka

**Comment by mapineda** [comment]
I'll start following up with those venues this week. Do we have a contact
at Livestrong?

**Comment by mateoclarke** [comment]
[This page](http://www.livestrong.org/who-we-are/our-history/our-home/tours-community-space/) has some info about Livestrong's space. It leads to this [broken form](https://secure.livestrong.org/site/SSurvey?ACTION_REQUIRED=URI_ACTION_USER_REQUESTS&SURVEY_ID=2343), but I'm worried that the space there won't be large enough (says it only holds 40, we need more like 60). Worth sending in the form and/or giving a call to learn more. They have some space in their office that would be great, but I'm not sure if thats what they make available. And if its hard capped at 40, that kinda stinks. The ideal space would be large and open. With room for circular tables for groups. Ideally, everyone could be in the same room and work in groups but also present to the rest of the audience. 

This is the venue (Iron Yard) from last year: https://drive.google.com/folderview?id=0BwKb2oghmQldUzIzbjhtNTE0Ums&usp=sharing

**Comment by mateoclarke** [comment]
Thanks for helping to reach out @mapineda. Here's some language you can use when you reach out: https://docs.google.com/document/d/1Uuepsj7Ssx4Wo2fQ_IbZ3u1q0d77vIQJk1sKS_Nr7UA/edit?usp=sharing

I'll reach out to City facilities and Vuka. Can you try some of the others? And throw any others you think of on the list?

**Comment by mateoclarke** [comment]
reached out to innovation office folks about City Facilities, waiting to hear back now.

**Comment by mateoclarke** [comment]
Best option from the City so far would be Asian American Resource Center. Very new facility but pretty far north. East of I-35, on Cameron, North of 183.
https://austintexas.gov/page/asian-american-resource-center-rentals

They are booked on 3/5 but available on 3/6

**Comment by mapineda** [comment]
Reached out to Livestrong. Iron Yard looks like it could fit 60 people. Are
they willing to work with us again?

**Comment by mateoclarke** [comment]
Yeah, Iron Yard would work. But the space was kinda noisy because of all the concrete and glass and we had to rent tables and chairs. Let's hold off on reaching out to them just yet.

**Comment by mateoclarke** [comment]
I reached out to Chelsea from Impact Hub Austin/Vuka.

**Comment by amaliebarras** [comment]
Remember, Iron Yard did just push back a bunch of cohorts because of unforeseen construction. They're supposed to be back up and running Feb 29 but it may be cutting it close

**Comment by mateoclarke** [comment]
gotcha, so Iron Yard is probably a no go.

Also got an update from Sarah at St Ed's yesterday. Sounds like the Munday Library isn't totally out of play. It's just taking some time to figure out because of internal politics and she didn't want to hold us back from securing a spot. I have a walk through scheduled over there on Friday at 8:30 (anyone is welcome to join). We should have resolution about Munday Friday by EOD.

**Comment by mateoclarke** [comment]
- got No's back from City Hall & Zilker Botanical. 
- Daniel recommend Carver library branch but they are booked. 
- I submitted a form to request For the City Center on the east side. 
- Vuka is booked on 3/5. We could try them on 3/6?

Here's a good list of some more options: 
https://library.austintexas.gov/sites/default/files/u20/meeting_spaces_2015.pdf

Any update on your end @mapineda?

**Comment by mapineda** [comment]
No update from Livestrong (venue too small anyways) or GA/WeWork

**Comment by mapineda** [comment]
I'm at the OpenStreetMap event at Object Rocket/Rackspace. Place seems
pretty big, plenty of tables. I'll ask if they would be willing to help.

**Comment by mateoclarke** [comment]
cool, thanks for reaching out to Object Rocket! I've updated the list up above :arrow_up:. Let's add venues and their responses at the top of this issue.

**Comment by mateoclarke** [comment]
We should have final word from St Ed's Monday or Tuesday. If that doesn't work out and we don't hear back from any of the other potential hosts, I guess we fall back on Capital Factory and just shorten the length of the event. 

Instead of a 10am-4pm, we could do 12:30pm-4:30pm. Not offer a full meal and instead afternoon snacks. That way we'd spend less on food and around $250 for Cap Fac.

**Comment by mateoclarke** [comment]
closing this out as St. Ed's gave us the green light

**Comment by mateoclarke** [comment]
Here is another venue available to rent at $25/hr: http://sustainablefoodcenter.org/about/rental-space

**Comment by VictoriaODell** [comment]
Working on making a comprehensive list here: 
https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=170603235

Before we start inputting more info, any thoughts about the format?

**Comment by mateoclarke** [comment]
think you could add columns for public transit and parking availability. Other than that... :ok_hand:

**Comment by VictoriaODell** [comment]
I added some stuff to the events list and spiffed it up some. 
If ya'll have a good idea of the venue or new venues can ya'll add them? 

https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=170603235

We need a [Work Hard Anywhere](http://workhardanywhere.com/) for event spaces~  :cat2:
