### ISSUE TITLE
Schedule Speaker for March Library Meetup

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#89]
reference #46 to speaker ideas

**Comment by mapineda** [comment]
I have a possible speaker.  He does cool things with python, libs and data.  He'll be attending the February Library Meetup to get a feel for how his talk should go.

**Comment by mateoclarke** [comment]
Kathy Mitchell of Texas Electronic Privacy Coalition, the presenter from EFF Austin tonight would be a great for Open Austin. http://www.meetup.com/EFF-Austin/events/228376517/

Especially because she is proposing some policy action around Body Cameras and Police Open Data policy that is right in line with our positions around procurement, transparency and data publication. There is also a short timeline for action. APD is supposedly piloting their program staring March 1.

I chatted with Kathy after the event and am emailing to confirm she can do 3/21.

**Comment by mateoclarke** [comment]
@mapineda: if you're potential speaker is interested after attending, throw his name into #46. 

Keep in mind we want the library meetup talks to be beginner friendly so a deep dive on python might be a better presentation for a Lightning Talk or a potential skillshare event. We were able to mix in a couple technical talks into the Lightning Talk format at that seemed to go pretty well for folks. I think we should do them again in June or July.
