### ISSUE TITLE
Find a Policy Core Team member

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#9]
- [x] Description of role
- [x] Announce at December meetup

**Comment by mateoclarke** [comment]
Some possible responsibilities:
- lead research and drafting of policy language
- lead putting together informational policy toolkits
  - come up with processes for getting newbies a policy 101
- run lead on candidate questionaries for Nov'16 elections

**Comment by amaliebarras** [comment]
In the description I'd clarify that this person would lead a committee to help w/ all those things plus: 

- craft blog posts updating community on policy progress
- lead policy breakouts at hack nights

**Comment by amaliebarras** [comment]
Drafting stuff out here: https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit

**Comment by amaliebarras** [comment]
"The Director of Policy leads policy and advocacy related discussions and projects related to Open Government & Open Data at the City of Austin, Travis County and State of Texas. They provide updates to the rest of the community on policy initiatives and their progress. They act as leader of the Gov Team who execute on the policy activities. Responsibilities include: leading research and drafting language of policy documents, putting together informational policy toolkits, coming up with policy 101 process for newbies, representing and speaking on behalf of Open Austin at community events and council meetings, and serving as lead on candidate questionnaires for local elections."
