### ISSUE TITLE
Open Austin connect cards

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#96]
We need to print cards for when we go to things like CityUp and other meetups, so that we can look legit when we approach potential new members and sponsors

**Comment by amaliebarras** [comment]
[OA Cards.pdf](https://github.com/open-austin/iced-coffee/files/115051/OA.Cards.pdf)

First pass - basically just copied the banner. Would y'all include anything else? @VictoriaODell for proof & feedback then I'll order 'em.

**Comment by mateoclarke** [comment]
I think that looks good. Don't think they really need to be two sided. Might be good to leave the back blank so you can scribble your info for people since the print won't be personalized.

But it looks fancy either way. If there is a cost difference, i'd just go with one-sided.

**Comment by luqmaan** [comment]
Even if cost wasn't an issue, the back should be blank so you can write extra stuff there.

**Comment by amaliebarras** [comment]
Good points y'all. I'll just do the one side

**Comment by mateoclarke** [comment]
@amaliebarras: Sounds like we ordered 1,000 at $30. Going to close this out but don't forget to send me the recipient and I'll reimburse once we have money in our CfA account
